### DISCUSSION TITLE
RA not detecting device via Bluetooth on HA

### DISCUSSION THREAD

**Discussion by FlyingPersian** [mKeRix/room-assistant#1010] [Q&A] [answered]
Hello,

I have installed RA on two of my RPIs. One is running HAOS and the other Raspberry Pi OS. On HA, I installed it as a addon via the HA addon store. On the other RPI I installed it via docker. Here are the relevant files:

HA:

local.yml:
```
global:
  instanceName: bedroom
  integrations:
    - bluetoothClassic
    - homeAssistant

bluetoothClassic:
  interval: 20
  minRssi: -20
  addresses:
    - 'xxx'             #my Phone (OnePlus 8)
  entityOverrides:
    'xxx':              #my Phone (OnePlus 8)
        id: my-phone
        name: OnePlus
homeAssistant:
  mqttUrl: mqtt://192.168.178.54:1883    # IP of the current RPI
  discoveryPrefix: homeassistant
cluster:
  port: 6425
  peerAddresses:
    - 192.168.178.36:6425    # IP of the other RPI running RPIOS
```

RPIOS:

docker-compose.yaml:
```
version: '3'
services:
  room-assistant:
    image: mkerix/room-assistant
    container_name: rass
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/dbus:/var/run/dbus
      - ./config:/room-assistant/config
```

local.yml
```
global:
  instanceName: livingRoom
  integrations:
    - bluetoothClassic
    - mqtt
bluetoothClassic:
  interval: 20
  minRssi: -20
  addresses:
    - 'xxx'                #my Phone (OnePlus 8)
  entityOverrides:
     'xxx':                #my Phone (OnePlus 8)
         id: my-phone
         name: OnePlus
mqtt:
  mqttUrl: mqtt://192.168.178.54:1883          #the RPI running HAOS
  mqttOptions:
    username: xxxx
    password: xxxx
  retain: false

cluster:
  port: 6425
  peerAddresses:
    - 192.168.178.54:6425         #the RPI running HAOS
```

The presence detection worked once. It detected it in my bedroom, I then changed to the living room and my phone was detected again. I came back to the bedroom, but it was detected with quite a long delay (1-2mins). I turned off Bluetooth on my phone and it was correctly detected as "not_home" after a short time. From then on,  no change was detected anymore. I rebooted both RPIs and my phone multiple times. Bluetooth on my phone is obviously on. Distance to the RPIs is <1m.

Here the log of my RPI running HAOS:

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> [01:26:41] INFO: Setting up Home Assistant configuration
> [01:26:41] INFO: Copying room-assistant configuration from /config/room_assistant
> [01:26:41] INFO: Starting room-assistant
> *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
> *** WARNING *** Please fix your application to use the native API of Avahi!
> *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
> *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
> *** WARNING *** Please fix your application to use the native API of Avahi!
> *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
> 12/31/2021, 1:26:53 AM - info - IntegrationsModule: Loading integrations: bluetooth-classic, home-assistant
> 12/31/2021, 1:26:57 AM - info - NestFactory: Starting Nest application...
> 12/31/2021, 1:26:57 AM - info - InstanceLoader: AppModule dependencies initialized
> 12/31/2021, 1:26:57 AM - info - InstanceLoader: ConfigModule dependencies initialized
> 12/31/2021, 1:26:57 AM - info - InstanceLoader: NestEmitterModule dependencies initialized
> 12/31/2021, 1:26:57 AM - info - InstanceLoader: IntegrationsModule dependencies initialized
> 12/31/2021, 1:26:57 AM - info - InstanceLoader: DiscoveryModule dependencies initialized
> 12/31/2021, 1:26:57 AM - info - InstanceLoader: PrometheusModule dependencies initialized
> 12/31/2021, 1:26:57 AM - info - InstanceLoader: EventsModule dependencies initialized
> 12/31/2021, 1:26:57 AM - info - InstanceLoader: TerminusModule dependencies initialized
> 12/31/2021, 1:26:57 AM - info - InstanceLoader: ClusterModule dependencies initialized
> 12/31/2021, 1:26:57 AM - info - InstanceLoader: ScheduleModule dependencies initialized
> 12/31/2021, 1:26:57 AM - info - InstanceLoader: BluetoothModule dependencies initialized
> 12/31/2021, 1:26:57 AM - info - InstanceLoader: EntitiesModule dependencies initialized
> 12/31/2021, 1:26:57 AM - info - InstanceLoader: BluetoothClassicModule dependencies initialized
> 12/31/2021, 1:26:57 AM - info - InstanceLoader: HomeAssistantModule dependencies initialized
> 12/31/2021, 1:26:57 AM - info - InstanceLoader: StatusModule dependencies initialized
> 12/31/2021, 1:26:59 AM - info - RoutesResolver: EntitiesController {/entities}:
> 12/31/2021, 1:26:59 AM - info - RouterExplorer: Mapped {/entities, GET} route
> 12/31/2021, 1:26:59 AM - info - RoutesResolver: StatusController {/status}:
> 12/31/2021, 1:26:59 AM - info - RouterExplorer: Mapped {/status, GET} route
> 12/31/2021, 1:26:59 AM - info - RoutesResolver: PrometheusController {/metrics}:
> 12/31/2021, 1:26:59 AM - info - RouterExplorer: Mapped {/metrics, GET} route
> 12/31/2021, 1:26:59 AM - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/default.json, config/local.yml (Current: /room-assistant)
> 12/31/2021, 1:26:59 AM - info - ClusterService: bedroom has been elected as leader
> 12/31/2021, 1:26:59 AM - info - ClusterService: Added 192.168.178.36:6425 to the cluster with id livingroom
> 12/31/2021, 1:27:00 AM - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://192.168.178.54:1883
> 12/31/2021, 1:27:00 AM - error - ClusterService: Failed to start mdns discovery (dns service error: unknown) #known issue w/ addon
> 12/31/2021, 1:27:00 AM - info - NestApplication: Nest application successfully started

On HA, when I go to Dev-Tools and search for both entities (device_tracker.oneplus_tracker & sensor.oneplus_room_presence), they stay on "not_home" no matter what. I'm not quite sure what to do now. Both instances of RA seem to run fine.

supervisor-2021.12.2
Home Assistant OS 7.0
