### DISCUSSION TITLE
Docker on Pi 0 - Bluetooth not finding anything..?

### DISCUSSION THREAD

**Discussion by mpfl** [mKeRix/room-assistant#1040] [Q&A]
Has anyone got Room Assistant working with bluetoothClassic on a Pi Zero in docker?

I was running Room Assistant on two Pi Zeroes deployed with Ansible just fine until one tracked device went unavailable and wouldn't come back.

I couldn't work out where Room Assistant logs were after two minutes of looking so I decided to blow away deployment, be a masochist and migrate Room Assistant to docker because at least I know `sudo docker-compose logs -f` works.

No issue with forming the cluster (well, none that I couldn't solve), but neither node seems to be noticing one of the two Apple watches they're configured to track.

Here is my docker-compose.yml: (this node has a really nifty UGreen adapter that provider power and ethernet (but not PoE) over one micro-USB port. The other node is using wifi).

```yaml
version: '3'
services:
  room-assistant:
    image: mkerix/room-assistant
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/dbus:/var/run/dbus
    environment:
      NODE_CONFIG: >
        {
          "global": {
            "instanceName": "bedroom",
            "integrations": ["homeAssistant", "bluetoothClassic"]
          },
          "cluster": {
            "autoDiscovery": false,
            "networkInterface": "enx000ec686d732",
            "port": 6425,
            "weight": 20,
            "peerAddresses": ["192.168.1.158:6425"]
          },
          "homeAssistant": {
            "mqttUrl": "mqtt://192.168.1.3:1883",
            "mqttOptions": {
              "username": "homeassistant",
              "password": "xxx"
            }
          },
          "bluetoothClassic": {
            "addresses": ["DE:AD:BE:EF:00:00", "DE:AD:BE:EF:00:01"],
            "entityOverrides": {
              "DE:AD:BE:EF:00:01": {
                "id": "his-watch",
                "name": "His watch"
              },
              "DE:AD:BE:EF:00:01": {
                "id": "her-watch",
                "name": "Her watch"
              }
            }
          }
        }
    restart: unless-stopped
```

Logs show everything starting up just find, cluster being formed, but nothing showing anything being tracked. No telemetry about tracked devices is popping up on MQTT either.

```
room-assistant_1  | *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
room-assistant_1  | *** WARNING *** Please fix your application to use the native API of Avahi!
room-assistant_1  | *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
room-assistant_1  | *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
room-assistant_1  | *** WARNING *** Please fix your application to use the native API of Avahi!
room-assistant_1  | *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
room-assistant_1  | 1/22/2022, 3:33:25 AM - info - IntegrationsModule: Loading integrations: home-assistant, bluetooth-classic
room-assistant_1  | 1/22/2022, 3:33:33 AM - info - NestFactory: Starting Nest application...
room-assistant_1  | 1/22/2022, 3:33:34 AM - info - InstanceLoader: AppModule dependencies initialized
room-assistant_1  | 1/22/2022, 3:33:34 AM - info - InstanceLoader: ConfigModule dependencies initialized
room-assistant_1  | 1/22/2022, 3:33:34 AM - info - InstanceLoader: NestEmitterModule dependencies initialized
room-assistant_1  | 1/22/2022, 3:33:34 AM - info - InstanceLoader: IntegrationsModule dependencies initialized
room-assistant_1  | 1/22/2022, 3:33:34 AM - info - InstanceLoader: DiscoveryModule dependencies initialized
room-assistant_1  | 1/22/2022, 3:33:34 AM - info - InstanceLoader: PrometheusModule dependencies initialized
room-assistant_1  | 1/22/2022, 3:33:34 AM - info - InstanceLoader: EventsModule dependencies initialized
room-assistant_1  | 1/22/2022, 3:33:34 AM - info - InstanceLoader: TerminusModule dependencies initialized
room-assistant_1  | 1/22/2022, 3:33:34 AM - info - InstanceLoader: ClusterModule dependencies initialized
room-assistant_1  | 1/22/2022, 3:33:34 AM - info - InstanceLoader: ScheduleModule dependencies initialized
room-assistant_1  | 1/22/2022, 3:33:35 AM - info - InstanceLoader: BluetoothModule dependencies initialized
room-assistant_1  | 1/22/2022, 3:33:35 AM - info - InstanceLoader: EntitiesModule dependencies initialized
room-assistant_1  | 1/22/2022, 3:33:35 AM - info - InstanceLoader: BluetoothClassicModule dependencies initialized
room-assistant_1  | 1/22/2022, 3:33:35 AM - info - InstanceLoader: HomeAssistantModule dependencies initialized
room-assistant_1  | 1/22/2022, 3:33:35 AM - info - InstanceLoader: StatusModule dependencies initialized
room-assistant_1  | 1/22/2022, 3:33:41 AM - info - RoutesResolver: EntitiesController {/entities}:
room-assistant_1  | 1/22/2022, 3:33:41 AM - info - RouterExplorer: Mapped {/entities, GET} route
room-assistant_1  | 1/22/2022, 3:33:41 AM - info - RoutesResolver: StatusController {/status}:
room-assistant_1  | 1/22/2022, 3:33:41 AM - info - RouterExplorer: Mapped {/status, GET} route
room-assistant_1  | 1/22/2022, 3:33:41 AM - info - RoutesResolver: PrometheusController {/metrics}:
room-assistant_1  | 1/22/2022, 3:33:41 AM - info - RouterExplorer: Mapped {/metrics, GET} route
room-assistant_1  | 1/22/2022, 3:33:41 AM - info - ConfigService: Loading configuration from /usr/local/lib/node_modules/room-assistant/dist/config/definitions/default.js, $NODE_CONFIG (Current: /room-assistant)
room-assistant_1  | 1/22/2022, 3:33:42 AM - info - ClusterService: bedroom has been elected as leader
room-assistant_1  | 1/22/2022, 3:33:44 AM - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://192.168.1.3:1883
room-assistant_1  | 1/22/2022, 3:33:45 AM - info - NestApplication: Nest application successfully started
room-assistant_1  | 1/22/2022, 3:34:24 AM - info - ClusterService: Added 192.168.1.158:6425 to the cluster with id kitchen
room-assistant_1  | 1/22/2022, 3:34:24 AM - info - ClusterService: kitchen has been elected as leader
```
