### DISCUSSION TITLE
Rolling Average

### DISCUSSION THREAD

**Discussion by akalbfell-impelix** [mKeRix/room-assistant#1128] [Q&A]
From my testing, it seems rolling average isn't working. I am testing by keeping the device in range and then moving it out of range. Based on my settings below, I would assume it would take up to 120 seconds until a location change is sent to HA as the average changes, but as soon as I am in range, the update is sent to HA.

```
global:
  cluster:
     autoDiscovery: true
     port: 6425
  instanceName: Office
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.16.56:1883'
  mqttOptions:
    username: xxx
    password: xxx
bluetoothClassic:
  minRssi: -4
  hciDeviceId: 0
  addresses:
    - 'AC:AC:AC:AC:AC:AC' #My iPhone 13 pro'
entities:
  behaviors:
    bluetooth-classic-ac-ac-ac-ac-ac-ac-tracker:
      rollingAverage:
        window: 120
```
