### DISCUSSION TITLE
Fine tuning setup & questions

### DISCUSSION THREAD

**Discussion by Bruskey** [mKeRix/room-assistant#1131] [Q&A]
Hi

I have started to delve into setting up room assistant in my house, and currently have it setup on 3 different raspberry pi's. I have a very basic setup trying to use BLE to track my android phone running the HA companion app. After looking around various forums and videos, i am still confused around some of the settings and features which may be the reason why i am having so many issues making my system stable. My config for all 3 pi's is below. I'm constantly seeing my device jumping between the rooms even though its sitting stationary right next to a pi and the other one is a considerable distance away. I also dont seem to find much information at all about clusters apart from setting them up. What is the purpose of the cluster leader? I dont understand how they work. When i click on each of my Pi's in Home Assistant on the MQTT devices screen each device is showing a different cluster leader? Also, is the MaxDistance a reliable feature? I have my phone literally sitting on top of my Pi and its saying 4.8 which i assume is metres? In saying that, what is the best way to fine tune everything to avoid seeing these issues as there doesnt seem to be much information i can find about that either. What settings should i be looking to add / adjust?

```
global:
  instanceName: Office
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
cluster:
  port: 6425
  peerAddresses:
    - 192.168.1.56:6425
    - 192.168.1.71:6425
    - 192.168.1.72:6425
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.100:1883'
  mqttOptions:
    username: xxxxxxxxx
    password: xxxxxxxxx
bluetoothLowEnergy:
  timeout: 15
  maxDistance: 12
  allowlist:
    - xxxx-100-1
  updateFrequency: 0
  tagOverrides:
    xxxx-100-1:
      name: Andrew Pixel 4a
```

Thanks in advance for any information that can help me
Andrew
