### DISCUSSION TITLE
Room Assistant picks up phone with Bluetooth Classic, but not with BLE

### DISCUSSION THREAD

**Discussion by Hikkepakke** [mKeRix/room-assistant#1176] [Q&A] [answered]
Hi,

Currently setting up Room Assistant using the Home Assistant add-on. When using Bluetooth Classic, my S21 is picked up just fine, but with BLE it doesn't work. Logs show many auto-discovered BLE devices, but none are my phone. Configs to follow:

```
global:
  instanceName: Bedroom
  integrations:
    - homeAssistant
    - bluetoothClassic
bluetoothClassic:
  minRssi: -20
  addresses:
    - '78:46:d4:91:ae:f8'
cluster:
  weight: 10
  autoDiscovery: false
  networkInterface: wlan0
  port: 6425
  peerAddresses:
    - ipaddress:6425
```
  
```
global:
  instanceName: Bedroom
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
bluetoothLowEnergy:
  allowList:
    - 7846d491aef8
cluster:
  weight: 10
  autoDiscovery: false
  networkInterface: wlan0
  port: 6425
  peerAddresses:
    - ipaddress:6425
```

I'm starting to think that the issue might be with my phone. Any ideas?
