### DISCUSSION TITLE
Blue Charm - BLE Tag

### DISCUSSION THREAD

**Discussion by cyphoryx** [mKeRix/room-assistant#1239] [Q&A]
I have a 6 device cluster set up. Everything seems to be working fine with BlueToothClassic but when I tried to allow a BLE tag on the list I am not seeing it in both the room-assistant APIs or the Hass Entities like I do the apple watch. I have searched and can't find the solution but has led me to some questions.

- Clusters. Do you have to add the same integrations to local.yml or does the cluster share the config around?
- I allowed the BLE tag and have the ID but nothing is showing up in the endpoint
- No errors 

I feel like I am doing something wrong. Posting configs below:

```
global:
  instanceName: Living Area
  integrations:
  - homeAssistant
  - bluetoothClassic
  - bluetoothLowEnergy
cluster:
  port: 6425
  autoDiscovery: true
  weight: 100
  timeout: 60
  peerAddresses:
  - 192.168.0.110:6425 #room-assist-office
  - 192.168.0.112:6425 #room-assist-workroom
  - 192.168.0.113:6425 #room-assist-theater
  - 192.168.0.114:6425 #room-assist-master
  - 192.168.0.115:6425 #room-assist-front-room
  - 192.168.0.116:6425 #room-assist-kitchen
homeAssistant:
  mqttUrl: 'mqtt://192.168.0.41:1883'
bluetoothClassic:
  minRssi: -5
  hciDeviceId: 0
  addresses:
  - '18:55:E3:B4:46:EA' 
  - '3C:22:FB:A3:E1:C7' 
  - '88:C0:8B:E1:58:77' 
bluetoothLowEnergy:
  timeout: 60
  allowlist:
  - dd340206dddf
  - 426c7565436861726d426561636f6e73-3838-4949
  maxDistance: 7
  tagOverrides:
    dd340206dddf:
      name: Blue Charm Tag
      measuredPower: -61
      batteryMask: 0x0000FF00
```

Logs

```pi@room-assist-living-area:~/room-assistant $ room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
15/08/2022, 02:29:48 - info - IntegrationsModule: Loading integrations: home-assistant, bluetooth-classic, bluetooth-low-energy
15/08/2022, 02:29:51 - info - NestFactory: Starting Nest application...
15/08/2022, 02:29:51 - info - InstanceLoader: AppModule dependencies initialized
15/08/2022, 02:29:51 - info - InstanceLoader: ConfigModule dependencies initialized
15/08/2022, 02:29:51 - info - InstanceLoader: NestEmitterModule dependencies initialized
15/08/2022, 02:29:51 - info - InstanceLoader: IntegrationsModule dependencies initialized
15/08/2022, 02:29:51 - info - InstanceLoader: DiscoveryModule dependencies initialized
15/08/2022, 02:29:51 - info - InstanceLoader: PrometheusModule dependencies initialized
15/08/2022, 02:29:51 - info - InstanceLoader: EventsModule dependencies initialized
15/08/2022, 02:29:51 - info - InstanceLoader: TerminusModule dependencies initialized
15/08/2022, 02:29:51 - info - InstanceLoader: ClusterModule dependencies initialized
15/08/2022, 02:29:51 - info - InstanceLoader: ScheduleModule dependencies initialized
15/08/2022, 02:29:51 - info - InstanceLoader: BluetoothModule dependencies initialized
15/08/2022, 02:29:51 - info - InstanceLoader: EntitiesModule dependencies initialized
15/08/2022, 02:29:51 - info - InstanceLoader: BluetoothLowEnergyModule dependencies initialized
15/08/2022, 02:29:51 - info - InstanceLoader: BluetoothClassicModule dependencies initialized
15/08/2022, 02:29:51 - info - InstanceLoader: HomeAssistantModule dependencies initialized
15/08/2022, 02:29:51 - info - InstanceLoader: StatusModule dependencies initialized
15/08/2022, 02:29:54 - info - WebSocketsController: EventsGateway subscribed to the "subscribeEvents" message
15/08/2022, 02:29:54 - info - RoutesResolver: EntitiesController {/entities}:
15/08/2022, 02:29:54 - info - RouterExplorer: Mapped {/entities, GET} route
15/08/2022, 02:29:54 - info - RoutesResolver: StatusController {/status}:
15/08/2022, 02:29:54 - info - RouterExplorer: Mapped {/status, GET} route
15/08/2022, 02:29:54 - info - RoutesResolver: PrometheusController {/metrics}:
15/08/2022, 02:29:54 - info - RouterExplorer: Mapped {/metrics, GET} route
15/08/2022, 02:29:54 - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/local.yml, /usr/lib/node_modules/room-assistant/dist/config/definitions/custom-environment-variables.yml (Current: /home/pi/room-assistant)
15/08/2022, 02:29:54 - info - ClusterService: living-area has been elected as leader
15/08/2022, 02:29:55 - info - ClusterService: Added 192.168.0.113:6425 to the cluster with id movie-theater
15/08/2022, 02:29:55 - info - ClusterService: Added 192.168.0.224:6425 to the cluster with id master-bedroom
15/08/2022, 02:29:55 - info - ClusterService: Added 192.168.0.115:6425 to the cluster with id front-room
15/08/2022, 02:29:55 - info - ClusterService: Added 192.168.0.112:6425 to the cluster with id basement
15/08/2022, 02:29:55 - info - ClusterService: Added 192.168.0.116:6425 to the cluster with id gym
15/08/2022, 02:29:55 - info - ClusterService: Added 192.168.0.216:6425 to the cluster with id office
15/08/2022, 02:29:55 - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://192.168.0.41:1883
15/08/2022, 02:29:55 - info - ClusterService: Starting mDNS advertisements and discovery
15/08/2022, 02:29:55 - info - NestApplication: Nest application successfully started
15/08/2022, 02:29:56 - info - BluetoothLowEnergyService: Discovered nearby BLE peripheral 5c153122c47d with ID 5c153122c47d and RSSI -77
15/08/2022, 02:29:56 - info - BluetoothLowEnergyService: Discovered nearby BLE peripheral 0a8f212750cb with ID 0a8f212750cb and RSSI -59
15/08/2022, 02:29:56 - info - BluetoothLowEnergyService: Discovered nearby BLE peripheral 2e936c3f0a94 with ID 2e936c3f0a94 and RSSI -66
15/08/2022, 02:29:56 - info - BluetoothLowEnergyService: Discovered nearby BLE peripheral e1a1769f14e9 with ID e1a1769f14e9 and RSSI -70
15/08/2022, 02:29:56 - info - BluetoothLowEnergyService: Discovered nearby BLE peripheral 1138a1034482 with ID 1138a1034482 and RSSI -75```
