### DISCUSSION TITLE
Cluster Won't Agree on a Leader

### DISCUSSION THREAD

**Discussion by pkscout** [mKeRix/room-assistant#1272] [General] [answered]
My cluster never seems to agree on a leader.  The bedroom thinks it's the lead of a 3 instance cluster.  The study things it's the lead of a 3 instance cluster.  And the living room thinks it's in an anarchist cluster of 3 instances where there is no leader.  I've tried everything I can think of to make this work to no avail.  Here's my ansible config:
```
all:
  hosts:
    'xxx.xxx.xxx.xxx':
      ansible_user: xxxxxx
      ansible_password: xxxxx
      room_assistant_config: 
        global:
          instanceName: livingroom
        cluster:
          weight: 100
          quorum: 2
    'xxx.xxx.xxx.xxx':
      ansible_user: xxxxxx
      ansible_password: xxxxx
      room_assistant_config: 
        global:
          instanceName: study
        cluster:
          weight: 1000
          quorum: 2
        bluetoothLowEnergy:
          maxDistance: 3
    'xxx.xxx.xxx.xxx':
      ansible_user: xxxxxx
      ansible_password: xxxxx
      room_assistant_config: 
        global:
          instanceName: bedroom
        cluster:
          weight: 10
          quorum: 2
        bluetoothLowEnergy:
          maxDistance: 5.5
  vars:
    room_assistant_version: latest
    room_assistant_global_config:
      global:
        integrations:
          - homeAssistant
          - bluetoothLowEnergy
      homeAssistant:
        mqttUrl: mqtt://xxx.xxx.xxx.xxx:1883
      bluetoothLowEnergy:
        timeout: 60
        updateFrequency: 30
        allowlist:
        - xxx
        - xxxx
        - xxxxx
        tagOverrides:
          xxx:
            name: xxx iBeacon
          xxxx:
            name: xxxx iBeacon
          xxxxx:
            name: xxxxx iBeacon
```
