### DISCUSSION TITLE
updateFrequency set to zero - but still seem to have throttled messages

### DISCUSSION THREAD

**Discussion by eBoon123** [mKeRix/room-assistant#338] [General]
Hello upgraded from a prior version (version 1.xx??????) and am having a problem with messages being throttled even though I am setting updateFrequency to the default of 0. I am still only seeing 1 message every 1 second or so. In prior version (using update_frequency) - I would get many messages per second. Here is my local.yml file:

```
global:
  instanceName: garage
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
cluster:
  autoDiscovery: false
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.105:1883'
bluetoothLowEnergy:
    name: garage_presence
    updateFrequency: 0
    processIBeacon: true
    onlyIBeacon: true
```
Same issue when I just remove the updateFrequency parameter altogether.

Thanks for this great package!
