### DISCUSSION TITLE
Raspberry pi zero w best settings for home assistant

### DISCUSSION THREAD

**Discussion by alexbell62** [mKeRix/room-assistant#353] [Show and tell]
Hi There, 
I'm fairly new to RA, i have a few raspberry pi zero w devices and two users with fitbit watches (sense, versa 1) on their wrists.

The idea of room-assistant is appealing and the amount of work done by developers is remarkable!  So I really wanted to make it work in my smart home setup. At the start i had a few issues getting it right. Well, tbh it's still work in progress.

My understanding is that raspberry pi zero w is the most used device running RA and most probably new users are getting similar issues. Just wanted to suggest that raspberry pi zero w users share their configs here so its easier for new users to set things up.

here is mine:
```
global:
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://ip.a.dd.ress:1883'
  mqttOptions:
    username: mqtt_username
    password: mqtt_passw
bluetoothLowEnergy:
  hciDeviceId: 0
  whitelist:
    - mac1
    - mac2
  maxDistance: 5
entities:
  behaviors:
    ble-mac1-tracker:
      rollingAverage:
        window: 3
    ble-mac2-tracker:
      rollingAverage:
        window: 3
```

The only problem im having is that delay is unacceptable for turning lights on.
And sometimes it shows 'not_home' even with a rolling window of 3 sec. 

Also if you notice any issues with my config please give me a shout.
