### DISCUSSION TITLE
Help dialing in speed of node handoffs...

### DISCUSSION THREAD

**Discussion by Menethoran** [mKeRix/room-assistant#359] [Q&A]
Hello fellows...
So, Ive got 8 RPi Zero Ws at the moment throughout my house... looking to add an additional 10 (or so)... but dont want to keep moving in 1 direction unless i can get these things dialed in..
So, for starters... the length of time to drop from one node to the next is INSANE... like, 30 seconds or more... 
(That is on my Galaxy S10+ using bluetooth classic... im having a heck of a time getting BLE to work with any kind of consistency on my Galaxy Watches, but am less worried about that at the moment...)

I have to assume theres something i screwed up...
I set up following the general guidelines on romeassistant.io for classic bluetooth... i then followed the few instructions for BLE... I then installed the newest version of BlueZ (i was having major issues with i/o using hcitool lescan (I would get: Set scan parameters failed: Input/output error, unless i restarted the dbus service... still have issues after updating BlueZ)...

Anyway, below is my config file... its the same on my HA build running a plugin for RA as it is on each RPiZw

```
global:
  cluster:
    autoDiscovery: false
    port: 6425
    peerAddresses:
      - '192.168.2.51:6425'
      - '192.168.2.52:6425'
      - '192.168.2.53:6425'
      - '192.168.2.54:6425'
      - '192.168.2.55:6425'
      - '192.168.2.56:6425'
      - '192.168.2.57:6425'
      - '192.168.2.58:6425'
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.7:1883'
  mqttOptions:
    username: robert
    password: James1979
bluetoothClassic:
  minRssi: -4
  hciDeviceId: 0
  addresses:
    - '58:B1:0F:D9:BE:CB'
    - '6C:00:6B:59:C6:3E'
    - '08:BF:A0:C1:82:9B'
    - 'D8:63:1E:B3:7D:97'
    - 'C8:7F:41:83:05:37'
bluetoothLowEnergy:
  updateFrequency: 1
  maxDistance: 5
  whitelist:
    - 58b10fd9becb
    - 6c006b59c63e
    - 08bfa0c1829b
    - d8631eb37d97
    - c87f41830537
```
(I am unsure how to bracket CODE... 

Additionally, i get spam errors in RA:
```
11/23/2020, 5:37:44 PM - error - BluetoothService: Command failed: hcitool -i hci0 cc "08:BF:A0:C1:82:9B" && hcitool -i hci0 rssi "08:BF:A0:C1:82:9B"
Invalid device: Network is down

11/23/2020, 5:37:50 PM - error - BluetoothService: Command failed: hcitool -i hci0 cc "D8:63:1E:B3:7D:97" && hcitool -i hci0 rssi "D8:63:1E:B3:7D:97"
Invalid device: Network is down

11/23/2020, 5:37:56 PM - error - BluetoothService: Command failed: hcitool -i hci0 cc "C8:7F:41:83:05:37" && hcitool -i hci0 rssi "C8:7F:41:83:05:37"
Invalid device: Network is down

11/23/2020, 5:38:02 PM - error - BluetoothService: Command failed: hcitool -i hci0 cc "58:B1:0F:D9:BE:CB" && hcitool -i hci0 rssi "58:B1:0F:D9:BE:CB"
Invalid device: Network is down
```

**Comment by Menethoran** [comment]
So, Ive updated the config file... and its actually worse...
here is updated config:
```
global:
  cluster:
    autoDiscovery: false
    port: 6425
    peerAddresses:
      - 192.168.2.51:6425
      - 192.168.2.52:6425
      - 192.168.2.53:6425
      - 192.168.2.54:6425
      - 192.168.2.55:6425
      - 192.168.2.56:6425
      - 192.168.2.57:6425
      - 192.168.2.58:6425

  instanceName: XXXXXXXXX
  integrations:
    - homeAssistant
#    - bluetoothLowEnergy
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.7:1883'
  mqttOptions:
    username: robert
    password: James1979
bluetoothClassic:
  updatefrequency: 1
  maxdistance: 5
  minRssi: -2
  hciDeviceId: 0 
  addresses:
    - '58:B1:0F:D9:BE:CB'
    - '6C:00:6B:59:C6:3E'
    - '08:BF:A0:C1:82:9B'
    - 'D8:63:1E:B3:7D:97'
    - 'C8:7F:41:83:05:37'
#bluetoothLowEnergy:
#  updateFrequency: 1
#  maxDistance: 5
#  whitelist:
#    - 58b10fd9becb
#    - 6c006b59c63e
#    - 08bfa0c1829b
#    - d8631eb37d97
#    - c87f41830537
```
