### DISCUSSION TITLE
BLE State not available in Home Assistant

### DISCUSSION THREAD

**Discussion by frdbonif** [mKeRix/room-assistant#368] [Q&A]
Hello,

I'm not sure if this is a bug so I'm asking here - if it was a bug I think there would be other reports.

## The Problem
I have bought some cheap Bluetooth low energy keyrings to act as presence detection.  For us, this works better than using our phones.  I have found the MAC addresses of the tags and set these up in Room Assistant and it all appears to be working on that end.  The entity has been auto-discovered by Home Assistant but the state isn't updating.

## What have I tried?
I have searched for a solution, the only solution that I found was a bug report but the solution was an incorrectly setup quorum - My nodes report that quorum has been acheived.

## Relevant Configuration
This is the relevant lines of the configuration file, I am using Ansible to provision the nodes.
```
        integrations:
        - homeAssistant
        - bluetoothLowEnergy
      homeAssistant:
        mqttUrl: mqtt://mqtt.fjla.uk:1883
        mqttOptions:
          password: *Password*
          username: room-assistant
      bluetoothLowEnergy:
        hciDeviceId: 0
        whitelist:
          - ffff0002c843
          - ffff0002c848
        tagOverrides:
          ffff0002c843:
            name: Fred's Keys
          ffff0002c848:
            name: Jade's Keys
```

This is the output from the API endpoint:
```
  {
    "attributes": {},
    "id": "ble-ffff0002c848-tracker",
    "name": "Jade's Keys",
    "distributed": true,
    "state": true
  },
  {
    "attributes": {
      "distance": 3.9,
      "lastUpdatedAt": "2020-11-26T17:36:31.336Z"
    },
    "id": "ble-ffff0002c848",
    "name": "Jade's Keys Room Presence",
    "distributed": true,
    "distances": {
      "Kitchen": {
        "lastUpdatedAt": "2020-11-26T17:36:31.336Z",
        "distance": 3.9,
        "outOfRange": false
      },
      "Bedroom": {
        "lastUpdatedAt": "2020-11-26T16:27:07.756Z",
        "distance": 23.6,
        "outOfRange": false
      },
      "Living Room": {
        "lastUpdatedAt": "2020-11-26T16:27:09.723Z",
        "distance": 23,
        "outOfRange": false
      }
    },
    "timeout": 5,
    "measuredValues": {
      "Kitchen": {
        "rssi": -71.00001103698922,
        "measuredPower": -59
      },
      "Bedroom": {
        "rssi": -90.08799655152883,
        "measuredPower": -59
      },
      "Living Room": {
        "rssi": -89.78009007111474,
        "measuredPower": -59
      }
    },
    "state": "Kitchen"
  }
```

## Other Information

* The auto-discovered entity in Home Assistant is named: sensor.jade_s_keys_room_presence.
* I also have an identical device named `Fred's Keys` which exhibits identical issues.
* In Home Assistant the entity shows with a value of 'Unknown'.
* I am also using Xiaomi devices with the same nodes and they report properly.

Hopefully, it is a simple mis-configuration that I have applied as I've not used any BLE devices with RA before.

Thanks for any suggestions.
