### DISCUSSION TITLE
Room Assistant on HASS.io issues

### DISCUSSION THREAD

**Discussion by DutchCoban** [mKeRix/room-assistant#376] [Q&A]
I've installed Room Assistant on my Raspberry Pi 3B with HASS.io. I'm trying to track my MiBand 4, but so far no luck. I've managed to track my iPhone :-)

My config is:
```
global:
  instanceName: Voordeur
  integrations:
    - homeAssistant
    - bluetoothClassic
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://10.25.10.9:1883'
  mqttOptions:
    username: null
    password: null
bluetoothClassic:
  addresses:
    - 'ip:ho:ne:xx:xx:xx'
bluetoothLowEnergy:
  whitelist:
    - mibandyyyyyy

```
Room Assistant creates a device with an entity for the ip:ho:ne:xx:xx:xx-device (and shows it's location), but none for the mibandyyyyyy-device. The mibandyyyyyy doesn't show up in the logs. Has anyone experience setting up a MiBand 4 with Room Assistant?

Also the logs show some confusing message:

`12/2/2020, 9:03:02 PM - info - HomeAssistantService: Device tracker requires manual setup in Home Assistant with topic: room-assistant/device_tracker/bluetooth-classic-ip-ho-ne-xx-xx-xx-tracker/state`
This device has been created in Home Assistant, so why the "manual setup"?

Also the logs show a bunch of messages that I couldn't figure out:
```
noble warning: unknown handle 11 disconnected!
noble warning: unknown handle 11 disconnected!
noble warning: unknown handle 11 disconnected!
noble warning: unknown handle 11 disconnected!
noble warning: unknown handle 11 disconnected!
noble warning: unknown handle 11 disconnected!
noble warning: unknown handle 11 disconnected!
noble warning: unknown handle 11 disconnected!
```

Any help would be appreciated.
