### DISCUSSION TITLE
Pls help, I'm stuck.  HASSIO bluetooth integration issues

### DISCUSSION THREAD

**Discussion by paproctor8** [mKeRix/room-assistant#382] [Q&A]
I am sure hoping one of you guys (or gals) can point me in the right direction here.

I have 4 instances of room assistant installed on PiZeros around the house, with our iPhone and Garmin watch bluetooth MACs identified, but despite turning on mqtt discovery in the HASSIO Mosquitto add-on, none of them are detected as entities within HomeAssistant anywhere that I can tell (no sensors in the developer list or devices listed in Configuration > Integrations > MQTT).  I followed the popular online setup guides as best I could.

I know each of the Pi Zeros can detect the bluetooth MACs because they show up normally when I check using: terminal > bluetoothctl > scan on.

My room assistant config files are as follows (obvious edits for privacy):

```yaml
global:
  cluster:
    autoDiscovery: false
    networkInterface: eth0
    port: 6425
    peerAddresses:
      - '192.168.x.xx:6425'
      - '192.168.x.xx:6425'
      - '192.168.x.xx:6425'
      - '192.168.x.xx:6425'
  instanceName: basement_den
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.x.xx:1883'
  mqttOptions:
    username: my_username
    password: my_password
bluetoothClassic:
  minRssi: -20
  hciDeviceId: 0
  addresses:
    - 'mygarmin_watch_bluetooth_MAC'
    - 'iphone_bluetooth_MAC'
    - 'wifesgarmin_watch_bluetooth_MAC'
```

**Comment by boardwarp** [comment]
You might need to create sensors manually for them to appear in Home Assistant. First you can verify that Room Assistant is talking to MQTT properly by going into Config > Integrations > MQTT (Configure) > Listen to a topic, enter "room-assistant/#" and click Start Listening. If MQTT messages appear, you can try setting up the [device tracker described here](https://www.room-assistant.io/integrations/home-assistant.html#device-trackers), but otherwise you'll need to work out why Room Assistant isn't talking to MQTT

**Reply by paproctor8** [reply]
I really appreciate you taking the time to help.  Using your suggested method I see that Room Assistant isn't talking to MQTT.  That narrows down my search for the solution.

In case it is useful to you or whoever else is nice enough to drop me some advice, here is the most recent stuff from Supervisor > Mosquitto > Log:

[INFO] found Patrick on Home Assistant
1607122941: New client connected from 192.168.1.69 as mqttjs_c6037265 (p2, c1, k60, u'Patrick').
1607122967: Socket error on client mqttjs_0b1ee0b7, disconnecting.
1607122994: New connection from 192.168.1.40 on port 1883.
1607122995: New client connected from 192.168.1.40 as mqttjs_f918c6bc (p2, c1, k60, u'Patrick').
1607123003: Socket error on client mqttjs_f2df350d, disconnecting.
1607123044: New connection from 192.168.1.33 on port 1883.
1607123044: New client connected from 192.168.1.33 as mqttjs_f04a650b (p2, c1, k60, u'Patrick').
1607123079: New connection from 192.168.1.71 on port 1883.
1607123079: New client connected from 192.168.1.71 as mqttjs_cef458cd (p2, c1, k60, u'Patrick').

**Reply by mKeRix** [reply]
mqttjs is room-assistant trying to connect (we could probably improve the name). Socket errors can be a lot of different things, but since you don’t seem to be using MQTT via TLS this error most commonly appears when the credentials are wrong. Can you double check if the password you set in the MQTT options matches the password for the Patrick account in Home Assistant? If you have any special characters also double check that the YAML is formatted correctly for that. You could also try to add a separate user in the Mosquitto add-on options and then use that one for room-assistant.

**Reply by paproctor8** [reply]
Great idea mKeRix, and thanks very much for your time.  I made a new username (mqtt) and password, using them just for room-assistant and Mosquitto.  Unfortunately, my new Mosquitto add-on log looks much the same as before (pasted below).  Never underestimate the odd ways I am able to screw up software configuration ;)

1607125367: New connection from 192.168.1.40 on port 1883.
[INFO] found mqtt on local database
1607125368: New client connected from 192.168.1.40 as mqttjs_d66e6f1d (p2, c1, k60, u'mqtt').
1607125390: Socket error on client mqttjs_f04a650b, disconnecting.
1607125411: New connection from 192.168.1.69 on port 1883.
1607125411: New client connected from 192.168.1.69 as mqttjs_ed4cc940 (p2, c1, k60, u'mqtt').
1607125429: Socket error on client mqttjs_cef458cd, disconnecting.
1607125454: New connection from 192.168.1.62 on port 1883.
1607125454: New client connected from 192.168.1.62 as 66KW7D0I2tOt0HdMCw3RHF (p1, c1, k60, u'mqtt').
1607125454: Client 66KW7D0I2tOt0HdMCw3RHF disconnected.
1607125457: Socket error on client 1LYmSbWvfKGkMKrDYJoDCb, disconnecting.
1607125457: New connection from 192.168.1.62 on port 1883.
1607125457: New client connected from 192.168.1.62 as 60istCJNn6NCj70plzjcb8 (p2, c1, k60, u'mqtt').
1607125462: New connection from 192.168.1.33 on port 1883.
1607125463: New client connected from 192.168.1.33 as mqttjs_795712d2 (p2, c1, k60, u'mqtt').
1607125485: Socket error on client 60istCJNn6NCj70plzjcb8, disconnecting.
1607125500: New connection from 192.168.1.62 on port 1883.
1607125500: New client connected from 192.168.1.62 as 1HBvUxnnZAVSdDjCBEXhWA (p2, c1, k60, u'mqtt').
1607125506: New connection from 192.168.1.71 on port 1883.
1607125506: New client connected from 192.168.1.71 as mqttjs_fab01eca (p2, c1, k60, u'mqtt').
1607125889: Socket error on client 1HBvUxnnZAVSdDjCBEXhWA, disconnecting.
1607125902: New connection from 192.168.1.62 on port 1883.
[INFO] found mqtt on local database
1607125903: New client connected from 192.168.1.62 as 7nFwGIGhyZ2mlfAHlOQ3VB (p2, c1, k60, u'mqtt').

**Reply by mKeRix** [reply]
To be honest I'm a bit puzzled as to what the issue here is. :/ If you have the opportunity to re-install the MQTT add-on I would give that a shot. Otherwise, one thing to check would be that the ports are all mapped correctly (at least 1883 should be mapped to 1883) in the add-on configuration. This is the config that is working for me:

```yaml
logins:
  - username: someuser
    password: somepass
anonymous: false
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
```
