### DISCUSSION TITLE
PIR Sensors on a PiZW and Room-Assistant/Home Assistant

### DISCUSSION THREAD

**Discussion by Menethoran** [mKeRix/room-assistant#392] [Q&A]
Hey guys... hoping someone may be able to kick me in the right direction for this...
I THINK ive got RA set up correctly with a PIR sensor for my PiZw...

How do i get HA to monitor the Pi for when there's motion... and subsequently, turn on lights? (I dont seem to be getting any devices popping up in Home Assistant for "motion"... just the bluetooth entities...)

**Comment by Menethoran** [comment]
Current config looks like this: (But im positive im missing something) (This is on room-assistant in HA)
```yaml
global:
  cluster:
    autoDiscovery: false
    port: 6425
    peerAddresses:
      - '192.168.2.51:6425'
      - '192.168.2.52:6425'
      - '192.168.2.53:6425'
      - '192.168.2.54:6425'
      - '192.168.2.55:6425'
      - '192.168.2.56:6425'
      - '192.168.2.57:6425'
      - '192.168.2.58:6425'
      - '192.168.1.101:6425'
  instanceName: homeassistant
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
    - gpio
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.7:1883'
  mqttOptions:
    username: robert
    password: James1979
bluetoothLowEnergy:
  updatefrequency: 1
  maxdistance: 3
  whitelist:
    - 58b10fd9becb
    - 6c006b59c63e
    - 08bfa0c1829b
    - d8631eb37d97
    - c87f41830537
    - 2a4d006f-1dfb-4d67-be87-c8857421721b
    - 10000000000000000000
    - 1000000000-0000-0000-0000-0000000001
    - 003916dc-c514-6ba1-964c-61538c7a1006
```

**Reply by mKeRix** [reply]
Two notes regarding your config: the `cluster` block needs to go up a level to be taken (= top-level) and you need to define the options for the `gpio` integration for any entities to be created ([docs](https://www.room-assistant.io/integrations/gpio.html)). So add something like this to your config on top-level:

```yaml
gpio:
  binarySensors:
    - name: My GPIO sensor
      pin: 8
      deviceClass: motion
```

**Reply by Menethoran** [reply]
This is my home assistant config... not one of the pis... i wouldnt want the PIN in there, would i?

And as for moving cluster up a level, do you men remove global and replace with cluster, or take the indent out of cluster?

This is a current config for one of the Pis...

(Sorry, I do not know how to bracket for code here)
```yaml
global:
  cluster:
    autoDiscovery: false
    port: 6425
    peerAddresses:
      - 192.168.2.51:6425
      - 192.168.2.52:6425
      - 192.168.2.54:6425
      - 192.168.2.55:6425
      - 192.168.2.56:6425
      - 192.168.2.57:6425
      - 192.168.2.58:6425
      - 192.168.1.101:6425

  instanceName: kitchen
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
    - gpio
#    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.7:1883'
  mqttOptions:
    username: robert
    password: James1979
#bluetoothClassic:
#  updatefrequency: 1
#  maxdistance: 5
#  minRssi: -2
#  hciDeviceId: 0 
#  addresses:
#    - '58:B1:0F:D9:BE:CB'
#    - '6C:00:6B:59:C6:3E'
#    - '08:BF:A0:C1:82:9B'
#    - 'D8:63:1E:B3:7D:97'
#   - 'C8:7F:41:83:05:37'
bluetoothLowEnergy:
  updateFrequency: 1
  maxDistance: 5
  whitelist:
    - 58b10fd9becb
    - 6c006b59c63e
    - 08bfa0c1829b
    - d8631eb37d97
    - c87f41830537
    - 2a4d006f-1dfb-4d67-be87-c8857421721b
    - 10000000000000000001
    - 10000000-0000-0000-0000-000000000001
    - 10000000000000000000000000000001
    - 003916dc-c514-6ba1-964c-61538c7a1006
gpio:
  binarySensors:
    - name: Kitchen Motion Sensor
    - pin: 16
    - deviceClass: motion
```

**Reply by mKeRix** [reply]
Take the indent out of cluster block, so that both global and cluster exist on the top-level. :)

From your second example config, could you change the block at the end to look like:

```yaml
gpio:
  binarySensors:
    - name: Kitchen Motion Sensor
      pin: 16
      deviceClass: motion
```

So remove the last two dashes, that way it becomes one list entry with all the settings instead of three entries with one setting each.

Other than that your config seems ok. Nothing should be required on the HA add-on, each instance can act independently.
