### DISCUSSION TITLE
I was under the impression room assistant can tell me which room a device is in?

### DISCUSSION THREAD

**Discussion by ljmerza** [mKeRix/room-assistant#405] [Q&A]
I have 3 raspberry pis setup with room assistant (one v3, one v4, and one zero w), one in the bedroom, office, and living room. In the logs they all say they connected to the mqtt server fine and the other 2 log out they've discovered another instance and will auto assign a leader in the cluster. Every thing looks good so far. Here's my general config for all 3:

```yaml
global:
  instanceName: office # this is office or livingroom or bedroom
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: mqtt://192.168.x.x:1883 # ip to my mqtt server via mosquitto
bluetoothClassic:
  minRssi: -20
  hciDeviceId: 0
  addresses:
    - 'xx:xx:xx:xx:xx:xx' # ble mac of my android phone
```

If I explore my mqtt messages though I'm only getting one topic - the topic of my phone and the distance but gives me no info to which instance is sending this message.. How am I supposed to know which device is saying my phone is x distance away? 

![image](https://user-images.githubusercontent.com/4085765/101967522-cea05e80-3be8-11eb-8e6e-938018741b44.png)

to be sure it's not the software, in nodered I'm connected to my mqtt server and listening to `room-assistant/#` messages. I'm getting the same results there. Is the the intended outcome? I thought each device would tell you have far it was *and* from what device so you could use those values to figure out what room the device was in?
