### DISCUSSION TITLE
Room Assistant isn't making entities in HA

### DISCUSSION THREAD

**Discussion by CommittotheIndian** [mKeRix/room-assistant#446] [Q&A] [answered]
I’ve clean installed room-assistant at least 4 times on a RPi 3b+. From what I can tell, everything is working properly and communicating but I don’t see any instances in HA except for the RPi itself. If I shut off the service, when I restart it, I get the following warning:  warn - ConfigService: No configuration found in /home/pi/config. I don't know how to clear the warning unless I reinstall.

```
global:
cluster:
  autoDiscovery: true
  port: 6425
  peerAddresses:
    - 10.10.*.*6425
instanceName: masterbedroom
integrations:
  - homeAssistant
  - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://10.1.*.*:1883'
  mqttOptions:
    username: omitted 
    password: omitted
bluetoothClassic:
  minRssi: -20
  hciDeviceId: 0 
  addresses:
    - ‘my phone mac’
    - ’my watch mac’
    - ‘wife's phone mac’
    - ‘wife's watch mac’
    - ’son's tablet'
  
 ```

I have doubled checked multiple times the MAC addresses are the Bluetooth MAC addresses.

When I run the service, I see this:

```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
1/10/2021, 20:36:27 - info - IntegrationsModule: Loading integrations: home-assistant, bluetooth-classic
1/10/2021, 20:36:29 - info - NestFactory: Starting Nest application...
1/10/2021, 20:36:30 - info - InstanceLoader: AppModule dependencies initialized
1/10/2021, 20:36:30 - info - InstanceLoader: ConfigModule dependencies initialized
1/10/2021, 20:36:30 - info - InstanceLoader: NestEmitterModule dependencies initialized
1/10/2021, 20:36:30 - info - InstanceLoader: IntegrationsModule dependencies initialized
1/10/2021, 20:36:30 - info - InstanceLoader: HttpModule dependencies initialized
1/10/2021, 20:36:30 - info - InstanceLoader: DiscoveryModule dependencies initialized
1/10/2021, 20:36:30 - info - InstanceLoader: ClusterModule dependencies initialized
1/10/2021, 20:36:30 - info - InstanceLoader: TerminusModule dependencies initialized
1/10/2021, 20:36:30 - info - InstanceLoader: BluetoothModule dependencies initialized
1/10/2021, 20:36:30 - info - InstanceLoader: ScheduleModule dependencies initialized
1/10/2021, 20:36:30 - info - InstanceLoader: EntitiesModule dependencies initialized
1/10/2021, 20:36:30 - info - InstanceLoader: HomeAssistantModule dependencies initialized
1/10/2021, 20:36:30 - info - InstanceLoader: BluetoothClassicModule dependencies initialized
1/10/2021, 20:36:30 - info - InstanceLoader: StatusModule dependencies initialized
1/10/2021, 20:36:31 - info - RoutesResolver: EntitiesController {/entities}:
1/10/2021, 20:36:31 - info - RouterExplorer: Mapped {/entities, GET} route
1/10/2021, 20:36:31 - info - RoutesResolver: StatusController {/status}:
1/10/2021, 20:36:31 - info - RouterExplorer: Mapped {/status, GET} route
1/10/2021, 20:36:32 - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://10.1.1.10:1883
1/10/2021, 20:36:32 - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/local.yml
1/10/2021, 20:36:32 - info - ClusterService: Starting mDNS advertisements and discovery
1/10/2021, 20:36:32 - info - NestApplication: Nest application successfully started
1/10/2021, 20:36:32 - info - ClusterService: master-bedroom has been elected as leader
1/10/2021, 20:36:32 - info - EntitiesService: Refreshing entity states

```

The only thing in HA is:
switch.master_bedroom_bluetooth_inquiries
sensor.master_bedroom_cluster_leader
sensor.master_bedroom_cluster_size

When I check http://IP:6425/entities I get:
```
[{"attributes":{"nodes":["raspberrypi"]},"id":"status-cluster-size","name":"raspberrypi Cluster Size","distributed":false,"state":1},{"attributes":{"quorumReached":true},"id":"status-cluster-leader","name":"raspberrypi Cluster Leader","distributed":false,"state":"raspberrypi"}]
```

**Comment by mKeRix** [comment, marked as answer]
The config error is likely because you are trying to start it from the wrong directory - room-assistant will look into `<working-directory>/config` for configuration files by default. You can override that with the CLI options, or simply run `cd /home/pi/room-assistant` (if you followed the quickstart guide) before starting room-assistant.

If the Bluetooth Inquiries switch is not marked as unavailable the integration is loaded successfully, as your service logs also say. BT devices will register entities the first time they a successful connection has been made, so that's where your issue likely lies.

Two different things that you could check:
- You seem to be running two instances, do both have bluetoothClassic enabled with the same list of devices? If not I would suggest to make instance that does have it enabled the [preferred leader](https://www.room-assistant.io/guide/cluster.html#usage-tips).
- With room-assistant stopped, can you try running `hcitool cc <your-phone-mac> && hcitool rssi <your-phone-mac>`? Ideally it should result in some text with a numeric RSSI value at the end.

**Reply by CommittotheIndian** [reply]
@mKeRix 

Thanks for replying. 

In HA my Bluetooth inquires state shows on but I still don't show any of my devices.

When I first started via `cd /home/pi/room-assistant ` 
I also had the follow errors pop up:
```
1/18/2021, 17:08:46 - error - ClusterService: getaddrinfo -3008
1/18/2021, 17:09:32 - error - ClusterService: getaddrinfo -3008
```

When I run the hcitool command I get the following for my phone:
```
rssi: too many arguments (maximal: 1)
Usage:
	rssi <bdaddr>
```

**Reply by mKeRix** [reply]
The cluster service errors are nothing to worry about unless your instances are not able to talk to each other - they happen in perfectly normal setups as well.

I just noticed something in your config snippet: the addresses array under bluetoothClassic have the wrong ticks, so that the interpreted YAML is likely slightly wrong. Instead of the `‘` you should use `'` characters surrounding your MAC strings. As it stands the `‘` are likely interpreted as part of the MAC, which will make room-assistant unable to find them (because they aren't valid that way).

**Reply by CommittotheIndian** [reply]
That was it the `'` made the difference. I got it to work on one of my PIs but I can't get the other one to work now.

Same code just different ip and instance name.
```
global:
  cluster:
    autoDiscovery: true
    port: 6425
    peerAddresses:
      - 10.10.*.*:6425   (opposite of the other pi)
  instanceName: master_bedroom
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://10.1.*.*:1883'
  mqttOptions:
    username: same omitted
    password: same omitted
bluetoothClassic:
  minRssi: -20
  hciDeviceId: 0
  addresses:
    - 'same omitted'
    - 'same omitted'
    - 'same omitted'
    - 'same omitted'
    - 'same omitted'
   ```

I then get the following error which repeats for all the above MAC address:

```
- error - BluetoothService: Command failed: hcitool -i hci0 cc "1st MAC" && hcitool -i hci0 rssi "1st MAC"
Invalid device: Network is down

1/30/2021, 19:23:32 - error - BluetoothService: Command failed: hcitool -i hci0 cc "2nd MAC" && hcitool -i hci0 rssi "2nd MAC"
Invalid device: Network is down

1/30/2021, 19:23:38 - error - BluetoothService: Command failed: hcitool -i hci0 cc "3rd MAC" && hcitool -i hci0 rssi "3rd MAC"
Invalid device: Network is down
```
