### DISCUSSION TITLE
Clarification on preferred leaders

### DISCUSSION THREAD

**Discussion by trymbill** [mKeRix/room-assistant#460] [Q&A] [answered]
First off, love this project! Fantastic effort!

I'm getting great results with the classic bluetooth integration and wanted to start monitoring a couple of BLE devices I have in various places. I noticed in another discussion on here (https://github.com/mKeRix/room-assistant/discussions/368) that you (@mKeRix) mention the need to have a preferred leader that has both classic and low-energy bluetooth enabled in order for it to send `state` information to mqtt.

I've got one raspberry pi in a central location in the house and it's the only one that's hard-wired in, so it makes sense for that one to be my preferred leader. I started setting that up and I got a bit lost in the documentation on the `weight` config under `cluster`. I'm not entirely sure how I can set the `weight` on my preferred leader. Here's my `ansible` config:

```yaml
all:
  hosts:
    'p-livingroom.local': # what I want to be the preferred leader
      room_assistant_config:
        global:
          integrations:
            - homeAssistant
            - bluetoothClassic
            - bluetoothLowEnergy

    'p-garage.local': # only checks for BLE
      room_assistant_config:
        global:
          integrations:
            - homeAssistant
            - bluetoothLowEnergy

    'p-bedroom.local': # only checks for classic bluetooth
      room_assistant_config:
        global:
          integrations:
            - homeAssistant
            - bluetoothClassic
  vars:
    room_assistant_version: latest
    room_assistant_global_config:
      homeAssistant:
        mqttUrl: mqtt://[url-to-mqtt]:1883

      bluetoothClassic:
        addresses:
          - '00:00:00:00:00:00' # an Android
          - '00:00:00:00:00:00' # an iPhone
        minRssi: -30
        interval: 8
        timeoutCycles: 3

      bluetoothLowEnergy:
        whitelist:
          - b1414141414141414141414141414141-1-14141 # a keychain
          - b1414141414141414141414141414141-1-14141 # an iBeacon
        maxDistance: 10

      entities:
        behaviors:
          bluetooth-classic-00-00-00-00-00-00-tracker: # the Android
            rollingAverage:
              window: 90
            debounce:
              wait: 1
              maxWait: 3
          bluetooth-classic-00-00-00-00-00-00-tracker: # the iPhone
            rollingAverage:
              window: 60
          b1414141414141414141414141414141-1-14141-tracker:
            rollingAverage:
              window: 300
            debounce:
              wait: 2
              maxWait: 10
```

I'd like the living room pi to be the preferred leader. I want the garage pi to only check for BLE and I want the bedroom pi to only check for classic bluetooth. How would I go about accomplishing that? Any help greatly appreciated!

**Comment by trymbill** [comment]
With the configuration above, my bedroom pi doesn't seem to be reporting any state changes. Here's the `/entities` response from the API on the p-bedroom pi:

```json
[
  {
    "attributes": {},
    "id": "bluetooth-classic-inquiries-switch",
    "name": "p-bedroom Bluetooth Inquiries",
    "distributed": false,
    "state": true
  },
  {
    "attributes": {
      "nodes": ["p-livingroom", "p-garage", "p-bedroom"]
    },
    "id": "status-cluster-size",
    "name": "p-bedroom Cluster Size",
    "distributed": false,
    "state": 3
  },
  {
    "attributes": {
      "quorumReached": true
    },
    "id": "status-cluster-leader",
    "name": "p-bedroom Cluster Leader",
    "distributed": false,
    "state": "p-livingroom"
  },
  {
    "attributes": {},
    "id": "bluetooth-classic-00-00-00-00-00-00-tracker",
    "name": "00:00:00:00:00:00",
    "distributed": true,
    "state": false
  },
  {
    "attributes": {
      "lastUpdatedAt": "2021-01-19T02:31:39.617Z"
    },
    "id": "bluetooth-classic-00-00-00-00-00-00",
    "name": "00:00:00:00:00:00 Room Presence",
    "distributed": true,
    "distances": {
      "p-livingroom": {
        "lastUpdatedAt": "2021-01-19T02:30:49.705Z",
        "distance": 23.3,
        "outOfRange": false
      }
    },
    "timeout": 48,
    "state": "not_home"
  },
  {
    "attributes": {},
    "id": "bluetooth-classic-11-11-11-11-11-11-tracker",
    "name": "11:11:11:11:11:11",
    "distributed": true,
    "state": false
  },
  {
    "attributes": {
      "lastUpdatedAt": "2021-01-19T02:31:29.835Z"
    },
    "id": "bluetooth-classic-11-11-11-11-11-11",
    "name": "11:11:11:11:11:11 Room Presence",
    "distributed": true,
    "distances": {
      "p-livingroom": {
        "lastUpdatedAt": "2021-01-19T02:30:41.253Z",
        "distance": 18.4,
        "outOfRange": false
      }
    },
    "timeout": 48,
    "state": "not_home"
  }
]
```

`p-bedroom` seems to be included in the cluster. And `p-bedroom Cluster Leader` is set to `p-livingroom`. But the only `distances` I'm seeing are coming from `p-livingroom`. I'm guessing this might have something to do with the `cluster` config, but I'm completely lost in the documentation for that portion 😕

**Comment by trymbill** [comment, marked as answer]
Ok, I think I've figured out the `cluster` settings. First time using ansible for anything so I think that's throwing me off a bit.

Added this to each `hosts:` portion of the config:
```yaml
all:
  hosts:
    'p-livingroom.local':
      room_assistant_config: 
        cluster:
          weight: 99

    'p-garage.local':
      room_assistant_config: 
        cluster:
          weight: 1
[...]
```
and they seem to be electing the p-livingroom node as their leader correctly, so that's good.
