### DISCUSSION TITLE
How to run bluetoothLowEnergy on only 1 of 3 nodes?

### DISCUSSION THREAD

**Discussion by trymbill** [mKeRix/room-assistant#462] [Q&A] [answered]
Here's my current ansible config:

```yaml
all:
  hosts:
    'p-livingroom.local':
      room_assistant_config:
        cluster:
          weight: 99 # the leader
        global:
          integrations:
            - homeAssistant
            - bluetoothClassic # only checks for classic bluetooth

    'p-garage.local':
      room_assistant_config:
        cluster:
          weight: 1
        global:
          integrations:
            - homeAssistant
            - bluetoothLowEnergy # only checks for BLE

    'p-bedroom.local':
      room_assistant_config:
        cluster:
          weight: 1
        global:
          integrations:
            - homeAssistant
            - bluetoothClassic # only checks for classic bluetooth
  vars:
    room_assistant_version: latest
    room_assistant_global_config:
      homeAssistant:
        mqttUrl: mqtt://[url-to-mqtt]:1883

      bluetoothClassic:
        addresses:
          - '00:00:00:00:00:00' # an Android
          - '00:00:00:00:00:00' # an iPhone
        minRssi: -30
        interval: 8
        timeoutCycles: 3

      bluetoothLowEnergy:
        whitelist:
          - b1414141414141414141414141414141-1-14141 # an iBeacon
        maxDistance: 10

      entities:
        behaviors:
          bluetooth-classic-00-00-00-00-00-00-tracker: # the Android
            rollingAverage:
              window: 90
            debounce:
              wait: 1
              maxWait: 3
          bluetooth-classic-00-00-00-00-00-00-tracker: # the iPhone
            rollingAverage:
              window: 60
          b1414141414141414141414141414141-1-14141-tracker: # the iBeacon
            rollingAverage:
              window: 300
            debounce:
              wait: 2
              maxWait: 10
```

How do I go about having one of these nodes using `bluetoothLowEnergy` and the rest using `bluetoothClassic` without forcing the node that's using `bluetoothLowEnergy` to also use `bluetoothClassic` **and** be the leader? I want the `p-livingroom` node to only use `bluetoothClassic` **and** be the leader (since it's the only node that's hard-wired in), and I don't want any other nodes to use `bluetoothLowEnergy`. Is that not possible?

I've got good results with 3 nodes all running `bluetoothClassic`, but as soon as I turn on `bluetoothLowEnergy` on one of them, or turn on `bluetoothLowEnergy` on all of them, I start seeing less accurate presence reporting. How do I run only one node with BLE, the rest with Classic, and select a leader without that node being required to run both?

Can I somehow add the `bluetoothLowEnergy` integration without it scanning? Can I provide it with a `null` for `whitelist` so that it enables the integration in order to include all of the nodes in the same cluster and allow the leader to send state information forward or is there some other way to achieve this?
