### DISCUSSION TITLE
Clusters Not Finding Each Other with Beta 2.13.0-beta.5

### DISCUSSION THREAD

**Discussion by Per4merKC** [mKeRix/room-assistant#463] [Q&A] [answered]
I'm using the Beta version of the Room-Assistant add-on and have updated my RPI (0w) to use the same 2.13.0-beta.5 versions.  All of the configurations have the following:
``` yaml
global:
        port: 6425
        cluster:
          autoDiscovery: false
          peerAddresses:
            - xxx.xxx.xxx.xx1:6425
            - xxx.xxx.xxx.xx2:6425
            - xxx.xxx.xxx.xx3:6425
```  
The instance on the Home-Assistant instance only has 1 item in its cluster.
The RPI see each other and have 2 in their clusters.

ALL of them show themselves as the leader.

What am I doing wrong?

![image](https://user-images.githubusercontent.com/9990420/105118956-fb238200-5a94-11eb-98d9-ca3c4527552e.png)

UPDATE:  I have rolled back to 2.12.0 on all systems and still can't get my HA instance to connect to the RPi instances.  RPi are communicating fine with each other.
Also... just realized that I didn't say that the HA instance is running on an Odroid N2+ (HA Blue) with a Bluetooth dongle.

**Comment by mKeRix** [comment, marked as answer]
In the Home Assistant add-on configuration, in the Network box, is 6425/udp mapped to port 6425 for you? This is the main communication port required by room-assistant instances to talk to each other. Also, the indentation of the config you posted is a bit off... but that may just be the GitHub formatting.

**Reply by Per4merKC** [reply]
Yes, it's mapped to 6425.  I also turned on the API interface and it works.  I agree that my config above looks funny; however, it is just the formatting here on GitHub.  Here is a partial screenshot of how ti actually looks:
![image](https://user-images.githubusercontent.com/9990420/106398246-65aeb900-63d7-11eb-820d-4192114b4521.png)

Here are the UDP settings:
![image](https://user-images.githubusercontent.com/9990420/106398200-0ea8e400-63d7-11eb-863a-ca2a810a0cd1.png)

Is there anything else you would like to see in order to troubleshoot?

**Reply by mKeRix** [reply]
Your cluster configuration is indented a bit wrong, it needs to be on top level. Try it like this:

```yaml
global:
  instanceName: ra-something
cluster:
  autoDiscovery: false
  peerAddresses:
    - 192.168.86.xx
```

I need to make the docs a bit more clear in that regard at some point.
