### DISCUSSION TITLE
Multiple Grid Eye (AMG8833) on same Raspberry Pi - Is it Possible?

### DISCUSSION THREAD

**Discussion by jamos77** [mKeRix/room-assistant#480] [Q&A]
Hi,

I've just installed room assistant on one Raspberry Pi with an AMG8833 Grid Eye Sensor and works really well.  The only problem is the Field of View on the Grid Eye isn't wide enough for my room to capture me sitting on the corner sofa.  Is there a way of using multiple Grid Eye's on the same Raspberry Pi or can I only use one Grid Eye per Raspberry Pi.  If it is possible how would I configure an additional Grid Eye  based on my config below:

```
all:
  hosts:
    living-room-pi.local:
      ansible_user: user
      ansible_password: password
      room_assistant_config: 
        global:
          integrations:
            - homeAssistant
            - bluetoothClassic
            - gridEye
        gridEye:
          deltaThreshold: 2
          heatmap:
            minTemperature: 16
            maxTemperature: 30
            rotation: 90
  vars:
    room_assistant_version: latest
    room_assistant_global_config:
      global:
        integrations:
          - homeAssistant
          - bluetoothClassic
      homeAssistant:
        mqttUrl: mqtt://xxx.xxx.xxx.xxx:1883
        mqttOptions:
          username: user
          password: password
      bluetoothClassic:
        addresses:
          - 'my-bluetooth-mac-address'
```
