### DISCUSSION TITLE
RPiZeroW, Lockups, WiFi 2Ghz flooding, and meaning of life

### DISCUSSION THREAD

**Discussion by DDomnick** [mKeRix/room-assistant#485] [Q&A]
Hi guys, came to this project after difficulties with setup using the 'monitor' project.  I have 2 RPiZeroW at the moment with two more on order (ooops).  RA setup on both went smoothly enough, doing only HomeAssistant and BlueToothClassic integrations to start with.  One thing I noticed almost immediately was easily repeatable connectivity issues (simple ping failures) on both pi devices only while the service is running.  Coming from the monitor project, I know that monitor's use of the 'name request' to discover BT devices uses large swaths of the 2.4ghz spectrum, causing disruption of other wifi devices.  Quote from docs in monitor project:

"Issuing a name request to the same private mac address every few seconds is a reliable - albeit rudimentary - way of detecting whether that device is "present" (it responds to the name request) or "absent" (no response to the name request is received). However, issuing name requests too frequently (e.g., every few seconds) uses quite a bit of 2.4GHz spectrum, which can cause interference with Wi-Fi or other wireless communications."

I was wondering if room-assistant theory-of-operation takes this into consideration, and what hardware the devs are using to test with?  I looked around on these forums to see a few folks having issues with lockups, and surmise that either I have overlooked something or room-assistant is, in fact, constantly flooding WiFi with BT 'name' requests that both interfere with the given RpiZero's own network connectivity as well as other devices communicating?  monitor project setups endeavor to only call for sweeping 'name requests' on demand to reduce interference.  Please comment on this and thanks for your continued work in presence detection solutions.  Look forward to making this work reliably.

**Comment by DDomnick** [comment]
Duhhh, right in the BT Classic section https://www.room-assistant.io/integrations/bluetooth-classic.html#requirements

Ok I have read up on this and I see the comment that the only way around this for Pi's is to increase the interval.  Yet I see some folks adding a separate USB BT device to the PiZero.  Anyone with experience comment on measurable improvements to either the WiFi responsiveness and/or polling responsiveness by adding a second, separate BT?

**Reply by mKeRix** [reply]
room-assistant doesn't use `name` requests, but the basic premise and disadvantages are the same. As you mentioned you can increase the interval or do an on-demand setup. For the latter I would recommend to write an automation that will turn the Bluetooth Inquiries switches on when some triggers happen (e.g. arrived home, motion sensor triggered...) and then turn it off after a while of no activity. Then setup your room-assistant config to contain:

```yaml
bluetoothClassic:
  preserveState: true
  inquireFromStart: false
```

As for the second adapter: I've only done short tests with those and they do seem to improve the connectivity of the Pis, but they will still cause the same interference issues for the whole network.

PS: If you go the on-demand route and write it as a Home Assistant automation it would be cool to publish that as a [blueprint](https://www.home-assistant.io/docs/automation/using_blueprints/)! :)

**Comment by DDomnick** [comment]
Thanks, I may move to on-demand as you suggest.  Not having much luck with fast, reliable updates.  Have all 4 PiZeroW's in play now with no additional hardware.  Am posting my configs for later review.  Big THANK YOU for advancing presence and detection with Home Assistant.  I understand you do this for the passion and the love of tech rather than the huge amounts of cash we all send you. (/s)
I have no better solutions to pursue at this time so happy to help with logs or testing if it helps you advance the project.

```
global:
  instanceName: ra-garage
  integrations:
    - bluetoothClassic
    - homeAssistant

bluetoothClassic:
# use hciconfig at command line to see available bluetooth adapters
  hciDeviceId: 0
  scanTimeLimit: 7
  interval: 15
  addresses:
    - '94:65:2D:6D:DB:FF'    # D
    - '94:65:2D:6C:A3:33'    # C
    - 'A8:2B:B9:B9:3A:B7'    # D
    - '94:65:2D:82:42:F3'    # N

homeAssistant:
  mqttUrl: mqtt://10.10.0.45:1883
  mqttOptions:
    username: mqtt
    password: 919

cluster:
  networkInterface: wlan0
  port: 6425
  timeout: 120
  weight: 10
  quorum: 3
# Make sure to add only peers of OTHER RA devices in this list (Exclude THIS RA device)
  autoDiscovery: false
  peerAddresses:
    - 10.10.2.161:6425
    - 10.10.2.162:6425
    - 10.10.2.163:6425
```

```
global:
  instanceName: ra-office
  integrations:
    - bluetoothClassic
    - homeAssistant

bluetoothClassic:
# use hciconfig at command line to see available bluetooth adapters
  hciDeviceId: 0
  scanTimeLimit: 7
  interval: 15
  addresses:
    - '94:65:2D:6D:DB:FF'    # D
    - '94:65:2D:6C:A3:33'    # C
    - 'A8:2B:B9:B9:3A:B7'    # D
    - '94:65:2D:82:42:F3'    # N

homeAssistant:
  mqttUrl: mqtt://10.10.0.45:1883
  mqttOptions:
    username: mqtt
    password: 919

cluster:
  networkInterface: wlan0
  port: 6425
  timeout: 120
  weight: 20
  quorum: 3
# Make sure to add only peers of OTHER RA devices in this list (Exclude THIS RA device)
  autoDiscovery: false
  peerAddresses:
    - 10.10.2.160:6425
    - 10.10.2.162:6425
    - 10.10.2.163:6425
```
```
global:
  instanceName: ra-attic
  integrations:
    - bluetoothClassic
    - homeAssistant

bluetoothClassic:
# use hciconfig at command line to see available bluetooth adapters
  hciDeviceId: 0
  scanTimeLimit: 7
  interval: 15
  addresses:
    - '94:65:2D:6D:DB:FF'    # D
    - '94:65:2D:6C:A3:33'    # C
    - 'A8:2B:B9:B9:3A:B7'    # D
    - '94:65:2D:82:42:F3'    # N

homeAssistant:
  mqttUrl: mqtt://10.10.0.45:1883
  mqttOptions:
    username: mqtt
    password: 919

cluster:
  networkInterface: wlan0
  port: 6425
  timeout: 120
  weight: 10
  quorum: 3
# Make sure to add only peers of OTHER RA devices in this list (Exclude THIS RA device)
  autoDiscovery: false
  peerAddresses:
    - 10.10.2.160:6425
    - 10.10.2.161:6425
    - 10.10.2.163:6425
```
```
global:
  instanceName: ra-kitchen
  integrations:
    - bluetoothClassic
    - homeAssistant

bluetoothClassic:
# use hciconfig at command line to see available bluetooth adapters
  hciDeviceId: 0
  scanTimeLimit: 7
  interval: 15
  addresses:
    - '94:65:2D:6D:DB:FF'    # D
    - '94:65:2D:6C:A3:33'    # C
    - 'A8:2B:B9:B9:3A:B7'    # D
    - '94:65:2D:82:42:F3'    # N
   
homeAssistant:
  mqttUrl: mqtt://10.10.0.45:1883
  mqttOptions:
    username: mqtt
    password: 919

cluster:
  networkInterface: wlan0
  port: 6425
  timeout: 120
  weight: 10
  quorum: 3
# Make sure to add only peers of OTHER RA devices in this list (Exclude THIS RA device)
  autoDiscovery: false
  peerAddresses:
    - 10.10.2.160:6425
    - 10.10.2.161:6425
    - 10.10.2.162:6425
```
