### DISCUSSION TITLE
States changing too quickly

### DISCUSSION THREAD

**Discussion by jcastro** [mKeRix/room-assistant#490] [Q&A]
Hello,
I've installed the new version 2.13 and also the iOS companion app. Everything seems to run smoothly (attaching my room-assistant configuration below). I'm getting the HA sensor and everything, however the state changes from home to not home really quickly and I'm not sure how to "smooth it out". For example when using monitor to detect home presence I'm able to to let the system work on the "confidence" by slowly lowering until it's sure that there's no one at home.

However here I might go from one room to another going through the hallway and it will detect me for a bit that I'm in another room, then change back. How I can smooth it out to wait a few seconds for the state to change? 

Thanks a lot!

```global:
  instanceName: oficina
  integrations:
    - homeAssistant
    - bluetoothClassic
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://10.0.1.30:1883'
  mqttOptions:
    username: mosquitto
    password: blablabla
bluetoothLowEnergy:
  hciDeviceId: 0
  timeout: 60
  allowlist:
    - REDACTED-REDACTEDC
  maxDistance: 2```

**Comment by mKeRix** [comment]
Regarding the `home`/`not_home` switches I would recommend to look at increasing `timeout` and/or `maxDistance`. Which one really helps depends on why the `not_home` states are triggered (you can see this via the [API](https://www.room-assistant.io/guide/api.html) if you want to dig deeper). Especially with Bluetooth Classic in the mix a timeout of 120s may make sense, as the adapter needs to switch modes a bit more. It might also make sense to increase your Bluetooth Classic `interval` to e.g. 20 or 30 when you are using both in tandem on a single adapter.

For smoothening the states you can use [entity behaviors](https://www.room-assistant.io/guide/entities.html#settings). Debouncing will help you for short, intermittent wrong states. It will wait a couple seconds for other state changes before committing to a state. Rolling averages help for states that are mostly right, but often interjected by shorter wrong states.

**Reply by jcastro** [reply]
Will give it a try, thanks so much for your reply and your work :)

**Reply by jcastro** [reply]
```
global:
  instanceName: imac
  integrations:
    - homeAssistant
    - bluetoothClassic
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://10.0.1.30:1883'
  mqttOptions:
    username: mosquitto
    password: REDACTED
bluetoothLowEnergy:
  hciDeviceId: 0
  timeout: 60
  allowlist:
    - REDACTEDXXX
  maxDistance: 12
entities:
  behaviors:
    REDACTEDXX_room_presence:
      debounce:
        wait: 2
        maxWait: 3
```
I'm not sure what I'm doing wrong but I've tried with debounce and rolling average and I?m still getting the entity in home assistant change as soon as the state changes. Attaching my configuration in case there's something wrong. I've tried with the entity name that HA gets (REDACTEDXX_room_presence) and also using same name as in the allowlist value "REDACTEDXX". Both with same result. Thanks!
