### DISCUSSION TITLE
Unable To Get Room Assistant Working

### DISCUSSION THREAD

**Discussion by TexanScot** [mKeRix/room-assistant#498] [General]
I'm hoping someone can give me a little bit of assistance in getting Room-Assistant working with my Home Assistant instance.

I have HA running on a Pi-4 (core-2021.1.5 & supervisor-2021.01.7). I installed room-assistant and have the following specified in my configuration.

```
global:
  instanceName: familyRoom
  integrations:
    - homeAssistant
    - bluetoothClassic
  homeAssistant:
    mqttUrl: 'mqtt://192.168.xx.xx:1883'
  bluetoothclassic:
    minRssi: -20
    hciDeviceId: 0
    addresses:
      - '90:8c:43:47:c3:55'
      - 'e4:e4:ab:b1:8b:02'
```

The mqtt address is the IP address of a mosquito broker that I am running on a separate pi-zero w. If I log onto this machine via SSH I can successfully publish and subscribe to topics on the mosquito server. I also have the mqtt integration installed on my HA instance pointing towards the same mosquito broker.

However from the room-assistant log file it appears that room-assistant is attempting to connect to mqtt on the localhost IP (127.0.0.1:1883). Here's the log output.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:11:26] ERROR: Got unexpected response from the API: Service not enabled
[16:11:26] INFO: Starting room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
2/5/2021, 4:11:29 PM - info - IntegrationsModule: Loading integrations: home-assistant, bluetooth-classic
2/5/2021, 4:11:30 PM - info - NestFactory: Starting Nest application...
2/5/2021, 4:11:30 PM - info - InstanceLoader: AppModule dependencies initialized
2/5/2021, 4:11:30 PM - info - InstanceLoader: ConfigModule dependencies initialized
2/5/2021, 4:11:30 PM - info - InstanceLoader: NestEmitterModule dependencies initialized
2/5/2021, 4:11:30 PM - info - InstanceLoader: IntegrationsModule dependencies initialized
2/5/2021, 4:11:30 PM - info - InstanceLoader: HttpModule dependencies initialized
2/5/2021, 4:11:30 PM - info - InstanceLoader: DiscoveryModule dependencies initialized
2/5/2021, 4:11:30 PM - info - InstanceLoader: PrometheusModule dependencies initialized
2/5/2021, 4:11:30 PM - info - InstanceLoader: ClusterModule dependencies initialized
2/5/2021, 4:11:30 PM - info - InstanceLoader: TerminusModule dependencies initialized
2/5/2021, 4:11:30 PM - info - InstanceLoader: BluetoothModule dependencies initialized
2/5/2021, 4:11:30 PM - info - InstanceLoader: ScheduleModule dependencies initialized
2/5/2021, 4:11:30 PM - info - InstanceLoader: EntitiesModule dependencies initialized
2/5/2021, 4:11:30 PM - info - InstanceLoader: BluetoothClassicModule dependencies initialized
2/5/2021, 4:11:30 PM - info - InstanceLoader: HomeAssistantModule dependencies initialized
2/5/2021, 4:11:30 PM - info - InstanceLoader: StatusModule dependencies initialized
2/5/2021, 4:11:30 PM - info - RoutesResolver: EntitiesController {/entities}:
2/5/2021, 4:11:30 PM - info - RouterExplorer: Mapped {/entities, GET} route
2/5/2021, 4:11:30 PM - info - RoutesResolver: StatusController {/status}:
2/5/2021, 4:11:30 PM - info - RouterExplorer: Mapped {/status, GET} route
2/5/2021, 4:11:30 PM - info - RoutesResolver: PrometheusController {/metrics}:
2/5/2021, 4:11:30 PM - info - RouterExplorer: Mapped {/metrics, GET} route
ls: /dev/disk/by-id/: No such file or directory
2/5/2021, 4:11:31 PM - error - HomeAssistantService: connect ECONNREFUSED 127.0.0.1:1883
2/5/2021, 4:11:31 PM - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/local.json
2/5/2021, 4:11:31 PM - error - ClusterService: Failed to start mdns discovery (dns service error: unknown)
2/5/2021, 4:11:31 PM - info - NestApplication: Nest application successfully started
2/5/2021, 4:11:32 PM - info - ClusterService: familyroom has been elected as leader
2/5/2021, 4:11:32 PM - info - EntitiesService: Refreshing entity states
```

Can anyone tell me where I'm going wrong?

**Comment by mKeRix** [comment]
Your config indentation is just a bit off, try it like this:

```yaml
global:
  instanceName: familyRoom
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.xx.xx:1883'
bluetoothclassic:
  minRssi: -20
  hciDeviceId: 0
  addresses:
    - '90:8c:43:47:c3:55'
    - 'e4:e4:ab:b1:8b:02'
```
