### DISCUSSION TITLE
Startup Problems

### DISCUSSION THREAD

**Discussion by Jens-Wymeersch** [mKeRix/room-assistant#505] [General]
I've followed the installation instruction to the letter (https://www.room-assistant.io/guide/quickstart-pi.html#configuring-room-assistant). I've installed the product on an RPI 3B.

I'm getting the following error message :

`2/6/2021, 20:57:20 - error - BluetoothService: Inquiring RSSI via BT Classic failed: Command failed: hcitool -i hci0 cc "mac address" && hcitool -i hci0 rssi "mac address"
Can't create connection: Operation not permitted
Get connection info failed: No such file or directory`

My config file is 
```
global:
  instanceName: Master_bedroom
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://XX.YY.ZZ.UU:1883'
  mqttOptions:
    username: user
    password: PSW
bluetoothClassic:
  minRssi: -20
  hciDeviceId: 0
  addresses:
    - mac addresses

```

Please note that when launching room-assistant : all looks good besides the following 

`ls: cannot access '/dev/disk/by-id/': No such file or directory`

Can you please let me know what I'm doing wrong here ?
