### DISCUSSION TITLE
Hostname wrong on Hassio

### DISCUSSION THREAD

**Discussion by acidShrooms2** [mKeRix/room-assistant#522] [Q&A] [answered]
Hi there,
After the latest hassio update the room-assistant service stopped working properly. I was able to track it down to the hostname being set 'wrong'. All the instances running on Hassio show "6e66619d-room-assistant-beta" as their hostname, instead of the room name I've set them to. It seems, that the hostname is derrived from the docker container instead of from the config file. Any advice on how to fix this?

**Comment by PeterCicaMolnar** [comment]
Hi, I just hangin' up here :)

I'm in the same boots. Just reinstalled all of my Pi Zeros and restarted Hassio add-on, same behaviour.
Before that, I deleted all sensors and MQTT topics. Unfortunatelly not all sensors have been recreated after my "big" re-do.
Any ideas would be great. Logs are clear, my HA Pi4 selected as leader as I expect in my living room.

Livingroom with HA OS and Hassio add-on (Pi4b):
```yaml
global:
  instanceName: Nappali
  integrations:
    - homeAssistant
    - bluetoothClassic
bluetoothClassic:
  addresses:
    - 'C8:3C:85:47:3B:02'
    - '50:7A:C5:0B:81:4B'
    - 'B8:F1:2A:44:8C:27'
    - '20:E2:A8:2C:3C:A8'
  interval: 20
  scanTimeLimit: 10
cluster:
  weight: 7
  timeout: 180
  autoDiscovery: false
  peerAddresses:
    - '192.168.0.70:6425'
    - '192.168.0.71:6425'
    - '192.168.0.200:6425'
```

Entrance (PiZero):
```yaml
#
#  Bejarat
#
global:
  instanceName: Bejarat
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://homeassistant.local:1883'
  mqttOptions:
    username: xxxxx
    password: xxxxx
bluetoothClassic:
  addresses:
    - C8:3C:85:47:3B:02
    - 50:7A:C5:0B:81:4B
    - B8:F1:2A:44:8C:27
    - 20:E2:A8:2C:3C:A8
  interval: 20
  scanTimeLimit: 10
cluster:
  weight: 1
  timeout: 180
  autoDiscovery: false
  peerAddresses:
    - 192.168.0.7:6425
    - 192.168.0.71:6425
    - 192.168.0.200:6425
```

Bedroom (PiZero):
```yaml
#
#  Haloszoba
#
global:
  instanceName: Haloszoba
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://homeassistant.local:1883'
  mqttOptions:
    username: xxxx
    password: xxxx
bluetoothClassic:
  addresses:
    - C8:3C:85:47:3B:02
    - 50:7A:C5:0B:81:4B
    - B8:F1:2A:44:8C:27
    - 20:E2:A8:2C:3C:A8
  interval: 20
  scanTimeLimit: 10
cluster:
  weight: 1
  timeout: 180
  autoDiscovery: false
  peerAddresses:
    - 192.168.0.7:6425
    - 192.168.0.70:6425
    - 192.168.0.200:6425
```

GamerRoom (Pi3B+):
```yaml
#
#  GamerRoom
#
global:
  instanceName: GamerRoom
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://homeassistant.local:1883'
  mqttOptions:
    username: xxxxx
    password: xxxxx
bluetoothClassic:
  addresses:
    - C8:3C:85:47:3B:02
    - 50:7A:C5:0B:81:4B
    - B8:F1:2A:44:8C:27
    - 20:E2:A8:2C:3C:A8
  interval: 20
  scanTimeLimit: 10
cluster:
  weight: 1
  timeout: 180
  autoDiscovery: false
  peerAddresses:
    - 192.168.0.7:6425
    - 192.168.0.70:6425
    - 192.168.0.71:6425
```

http://homeassistant.local:6415/api/#/entities/EntitiesController_getAll:
```json
[
  {
    "attributes": {
      "nodes": [
        "haloszoba",
        "gamerroom",
        "bejarat",
        "6e66619d-room-assistant"
      ]
    },
    "id": "status-cluster-size",
    "name": "6e66619d-room-assistant Cluster Size",
    "distributed": false,
    "stateLocked": true,
    "state": 4
  },
  {
    "attributes": {
      "quorumReached": true
    },
    "id": "status-cluster-leader",
    "name": "6e66619d-room-assistant Cluster Leader",
    "distributed": false,
    "stateLocked": true,
    "state": "6e66619d-room-assistant"
  }
]
```
