### DISCUSSION TITLE
Am I misunderstanding how maxDistance works? Using room-assistant to track my trash can.

### DISCUSSION THREAD

**Discussion by ih8gates** [mKeRix/room-assistant#550] [Q&A] [answered]
I'm attempting to use room-assistant to sense whether my trash can has been taken to the curb or not. When the can is at the house, room-assistant is reporting a distance attribute (in Home Assistant) of the presence sensor of around 2. When the can is at the street, it's usually around 3.

I tried setting the maxDistance attribute of the bluetoothLowEnergy integration to 2.5, thinking I'd see a change from home to not_home when the beacon moves to the curb. But when the can's at the curb, the beacon is still showing a status of "home" with a distance of 3ish.

Is that not how maxDistance works? I'm building a work-around using a template sensor that tracks the distance attribute...

Aside: I set the measuredPower values in tagOverrides per the information that Feasybeacon (Android app) reports as the RSI at 1 meter. When the can's at the street, it's a lot more than 3 meters from the Raspberry Pi 3 that I'm running room-assistant on. And the change in distance between "at the house" and "at the curb" is several meters.

**Comment by mKeRix** [comment]
Your assumption is correct, `maxDistance` should indeed cause the entity to enter `not_home` state if there is only that one instance tracking. Could you post your config (stripped of passwords and IDs) so I could get some more insight into what might be causing the issue for you?

> When the can's at the street, it's a lot more than 3 meters from the Raspberry Pi 3 that I'm running room-assistant on. And the change in distance between "at the house" and "at the curb" is several meters.

That's a limitation of distance measuring using Bluetooth unfortunately... it isn't perfect and will become less accurate with distance and more stuff in-between. One note that I could make is that optimally, the `measuredPower` is measured using the Pi to cover any differences in the antennas. You can see the measured RSSI in the entities endpoint of the [API](https://www.room-assistant.io/guide/api.html).

**Comment by ih8gates** [comment, marked as answer]
Here's my config. (I changed the ble IDs)

```yaml
global:
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://10.0.0.74:1883'
  mqttOptions:
    username: xxx
    password: xxx
  sendAttributes: true
bluetoothLowEnergy:
  maxdistance: 2
  allowlist:
    # trash
    - 426c7565436861726d42-3838-4949
    # key
    - fda50693a4e24fb1afcfc-10065-26049
  tagOverrides:
    426c7565436861726d42-3838-4949:
      measuredPower: -59
    fda50693a4e24fb1afcfc-10065-26049:
      measuredPower: -75
```

And, yes - I'm stopping/restarting the service to make sure that my config updates are seen.

When it's not raining, I'll fetch my sensor off the trash can and measure the RSSI via the Pi. Thanks for the tip about looking it up in the API.
