### DISCUSSION TITLE
Worked well for a bit, now getting weird data in Home Assistant

### DISCUSSION THREAD

**Discussion by ih8gates** [mKeRix/room-assistant#561] [Q&A] [answered]
When I first started using room-assistant, I'd see nice solid blocks of home/not home in the history graphs of my two trackers in Home Assistant. Now, I'm seeing graphs with a lot of stripes where the presence is switching frequently from home to not home. My test subject right now is a tracker that's about two feet from the Raspberry Pi 3 that hasn't moved. 

Sometimes, I'll see the presence tracker with a state of "not home", but with a distance of 3 meters. I have maxDistance set at 10. Even with maxDistance undefined, I'll see home/not home all night. 

I've tried rebooting room-assistant. I've restarted Home Assistant. I've tried adding debouncing behaviors.  I've tried measuredPower overrides based on measured rssi obtained from the API.

Current config:
```yaml
global:
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://10.0.0.74:1883'
  mqttOptions:
    username: xxx
    password: xxx
  sendAttributes: true
bluetoothLowEnergy:
#  maxDistance: 10
  allowlist:
    - xxx-3838-4949
    - xxx-10065-26049

  tagOverrides:
    xxx-3838-4949:
      measuredPower: -63
    xxx-10065-26049:
      measuredPower: -65.5
entities:
  behaviors:
    ble-xxx-3838-4949-tracker:
      debounce:
        wait: 10
    ble-xxx-3838-4949:
      debounce:
        wait: 10
    ble-xxx-10065-26049-tracker:
      debounce:
        wait: 30
    ble-xxx-10065-26049:
      debounce:
        wait: 30
```
