### DISCUSSION TITLE
Configuring clusters with Ansible

### DISCUSSION THREAD

**Discussion by mpfl** [mKeRix/room-assistant#569] [Q&A] [answered]
I used Ansible to roll Room Assistant out to a couple of Pi Zeroes. Each one works and is connecting to MQTT, and picking up the two Apple Watches in the house without issue. Unfortunately I'm stumped on whether or not clusters are working properly.

Unfortunately I'm not familiar enough with Ansible to know whether I'm writing the cluster configuration correctly so that it gets deployed to all of the Pis. Is this correct?

```
all:
  hosts:
    'kitchen.local':
    'bedroom.local':
  vars:
    room_assistant_version: latest
    room_assistant_global_config:
      global:
        cluster:
          networkInterface: wlan0
          port: 6425
          peerAddresses:
            - 'kitchen.local:6425'
            - 'bedroom.local:6425'
        integrations:
          - homeAssistant
          - bluetoothClassic
      homeAssistant:
        mqttUrl: mqtt://xxx:1883
        mqttOptions:
          username: homeassistant
          password: xxx
      bluetoothClassic:
        addresses:
          - 'de:ad:be:ef:00'
          - 'de:ad:be:ef:00'
```

**Comment by rmaxseiner** [comment]
Hi,

I'm by no means an expert as I'm struggling to get my set-up working but my cluster of 2 Raspberry Pi Zeros and the home assistant node is working.  I have posted my configuration in my issue getting devices to be tracked.  

The configuration of the home assistant installation needs to be different and it requires the peerAddresses but the two raspberry pi zero's didn't require this.  When I look at your configuration I think the addition of the peerAddresses: in the global section seems odd as the peers would be different for each node. I would try deleting that and see what happens.  I would also stop the each of the services and then start from the command line to see what the logs report.  The logs will likely be helpful in debugging the problem. 

Once again just a beginner myself but I have the cluster working.

**Comment by mKeRix** [comment, marked as answer]
Your `cluster` section needs to be on the top-level, not under `global`. It should also ideally contain the actual IP addresses, rather than the MDNS hostnames. Try to make it look similar to this:

```yaml
all:
  hosts:
    'kitchen.local':
    'bedroom.local':
  vars:
    room_assistant_version: latest
    room_assistant_global_config:
      global:
        integrations:
          - homeAssistant
          - bluetoothClassic
      cluster:
        networkInterface: wlan0
        port: 6425
        peerAddresses:
          - '192.168.1.xx:6425'
          - '192.168.1.xx:6425'
      homeAssistant:
        mqttUrl: mqtt://xxx:1883
        mqttOptions:
          username: homeassistant
          password: xxx
      bluetoothClassic:
        addresses:
          - 'de:ad:be:ef:00'
          - 'de:ad:be:ef:00'
```

Other than that the config looks ok to me.
