### DISCUSSION TITLE
Help Needed Detecting Devices

### DISCUSSION THREAD

**Discussion by rmaxseiner** [mKeRix/room-assistant#576] [Q&A] [answered]
I have been working to set up a three node cluster to perform presence detection and I have solved a number of problems but still stuck with the actual presence detection not working for some devices. I hope to expand to more devices but I want to get this working in a few rooms first.  I think this may be related to the devices I'm using but let's start with the configuration.  I have a node running on Home Assistant (Hassio) with the following configuration. I realize I don't need the MQTT settings and will likely delete but it is connecting and working fine right now.

```
instanceName: room1
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://localhost:1883'
  mqttOptions:
    username: superSecretUser
    password: superSecretPassword
bluetoothClassic:
  interval: 4
  scanTimeLimit: 3
  hciDeviceId:
    - 0
  addresses:
    - 'AA:AA:AA:AA:AA:AA'
    - 'BB:BB:BB:BB:BB:BB'
    - 'CC:CC:CC:CC:CC:CC'
cluster:
  peerAddresses:
    - 192.168.XX.XXX:6425
    - 192.168.XX.XXX:6425
  weight: 100

```

I have two other nodes that are managed by ansible with the following configuration. They are running on Raspberry pi Zero Ws.

```all:
  hosts:
    'ra-room2.local':
    'ra-room3.local':
  vars:
    room_assistant_version: latest
    room_assistant_global_config:
      global:
        integrations:
          - homeAssistant
          - bluetoothClassic
      homeAssistant:
        mqttUrl: mqtt://homeassistant.local:1883
        mqttOptions:
          username: superSecretUser
          password: superSecretPassowrd
      bluetoothClassic:
        interval: 6
        scanTimeLimit: 5
        preserveState: false
        hciDeviceId:
          - 0
        addresses:
        - 'AA:AA:AA:AA:AA:AA'
        - 'BB:BB:BB:BB:BB:BB'
        - 'CC:CC:CC:CC:CC:CC'
 ```

The cluster does come up with all three nodes reporting that 3 nodes are in the cluster and that room3 is the leader.  Now I believe everything is working properly but I'm having problems detecting some devices. 

1) Garmin Fenix 5x watch.  The Garmin Watch is Bluetooth Smart or BLE and that would explain why I'm not able to find it with the bluetoothClassic configuration.  In order to debug this I found a tool called hcitool that I believe should allow me to determine if the items are located.  When I run a hcitool lescan on one of the Raspberry pi Zero W many devices appear but the bluetooth address of the Garmin watch does not appear in the list.  Before I go changing all the configuration I wanted to verify that I can detect it.  Am I using the hcitool incorrectly? 

2) Andriod Phone: This doesn't get detected at all.  Maybe I'm just missing the signs but I'm not seeing any MQTT messages with the MAC address.  I'm not sure what I'm missing since this seems like it should work 

3) iWatch: This seems to be working properly as I'm able to get location for the iWatch.

More general questions.
1) Can I run both BLE and Bluetooth classic on the same device?  It seems like there is a warning that this may cause performance issues but I'm not sure how that would manifest itself.  The recommendation is to run these on separate HCI devices.  Does that mean attaching a Bluetooth device via USB on the Raspberry Pi Zero and on the Home Assistant instance?  

2) Why does room3 or room2 appear as leader when I have the weight on room1?

3) This is not a room-assistant question but seeing as people may be using this software I thought I would ask.  Any ideas on why MQTT explorer would essentially crash my MQTT instance?  Seems the addon goes from about 2-5% CPU usage to 25%+ when I start it.  This seems to overwhelm the service and the clients disconnect and reconnect.  I get a disconnected from server. Then after a while this settles down and stabilizes. 

4) Really an Ansible question but once again because people may have encountered and solved this problem.  Strange problem with Ansible.  I have set up the keys to access the two Pi Zeros.  When I run the ansible playbook I get a UNREACHABLE message on one or more of the connections.  Then I run again and the connection works just fine with no changes in configuration.  I had a problem where I needed to tell ansible the location of the keys in the ansible config file.  This changed the behavior from not working to working on and off.  

So any answers to the questions would be helpful or hints on my configurations. Thanks in advance for any assistance. 

Ron
