### DISCUSSION TITLE
Home Assistant Android App BLE Transmitter very flakey

### DISCUSSION THREAD

**Discussion by bachoo786** [mKeRix/room-assistant#592] [Q&A]
So I have the HA android app with the BLE sensors enabled. I have configured my room-assistant as shown below. However the I do not see the BLE from my phone on HA, sometimes it would appear on the MQTT integration and sometimes it wouldn't.

I have checked from my other android phone using beacon scope and I can see my android's BLE as an ibeacon.
```
global:
  instanceName: Office
  integrations:
    - bluetoothLowEnergy
    - homeAssistant
homeAssistant:
  mqttUrl: 'mqtt://XXXX:1883'
  mqttOptions:
    username: XXXX
    password: XXXX
bluetoothLowEnergy:
  timeout: 60
  whitelist:
    - feea1c2a-1241-437d-9c6e-3fdde1a317f7-100-1
  tagOverrides:
    feea1c2a-1241-437d-9c6e-3fdde1a317f7-100-1:
      name: testnew
```

Anyone experiencing the same?
