### DISCUSSION TITLE
Error in configuration file on upgraded version (2.15.1)

### DISCUSSION THREAD

**Discussion by warez1975** [mKeRix/room-assistant#608] [Q&A] [answered]
Hello

Last evening I've upgrade my RA instances to new 2.15.1 and I encunter some problem with my "old" configuration:

```
global:
  instanceName: Bedroom
  integrations:
    - homeAssistant
    - bluetoothClassic
    - shell
cluster:
  autoDiscovery: false
  quorum: 2
  weight: 50
  port: 6425
  peerAddresses:
    - XXXXXXXX:6425
    - XXXXXXXX:6425
    - XXXXXXXX:6425
shell:
  sensors:
    - name: Bedroom Wifi Strength
      command: 'iwconfig wlan0 | grep -i quality'
      regex: 'Signal level=(-?[0-9]+) dBm'
      cron: '* * * * *'
      icon: mdi:wifi
      unitOfMeasurement: dBm
      deviceClass: signal_strength
homeAssistant:
  mqttUrl: 'mqtt://XXXXXXX:1883'
  mqttOptions:
    username: XXXXXX
    password: XXXXXX
  discoveryPrefix: homeassistant
bluetoothClassic:
  interval: 6
  scanTimeLimit: 2.5
  timeoutCycles: 2.5
  inquireFromStart: true
  minRssi:
    'XXXXXXXXXXXXX': -25
    'XXXXXXXXXXXXX': -25
    'XXXXXXXXXXXXX': -25
  defualt: -20
  addresses:
    - 'XXXXXXXXXXXXX'
    - 'XXXXXXXXXXXXX'
    - 'XXXXXXXXXXXXX'
```
I recive this error from RA:

```
error - ConfigService: "global.cluster" is not allowed [Value: {"autoDiscovery":false,"port":6425,"peerAddresses":["192.168.1.100:6425","192.168.1.101:6425","192.168.1.102:6425"]}].
error - ConfigService: "bluetoothClassic.defualt" is not allowed [Value: -20].
```
Every instances run on separate RPI0 whit dedicated IP and HA run on RPI4 with dedicated IP but with this new version, for me, is impossible to configure cluster.

Mey someone could help me? Thank you.
