### DISCUSSION TITLE
Need Help, Ansible doesnt apply <room_assistant_global_config>

### DISCUSSION THREAD

**Discussion by acidShrooms2** [mKeRix/room-assistant#610] [Q&A] [answered]
HI there,

Ive finally decided to make the configuration process easyer and started using ansible. But now I got stuck with applying the configuration. All the specific configurations I use on each node get applyed as they should but it seems my global configuration gets ignored completely even if ansible states it was applyed. To make sure it hasnt got to do with my exiszting configuration, I completely deleted the local.yml file on one of the nodes and left the specific configurations empty so I ended up with the following hosts.yml file:

```
all:
  hosts:
    '192.168.0.xxx':
      ansible_user: user
      ansible_password: password
  vars:
    room_assistant_version: latest
    room_assistant_global_config:
      global:
        integrations:
          - homeAssistant
          - bluetoothClassic
          - bluetoothLowEnergy
      homeAssistant:
        mqttUrl: 'mqtt://192.168.0.xxx:1883'
        mqttOptions:
          username: user
          password: password
      bluetoothClassic:
        preserveState: false
        addresses:
          - 'xxxx'
          - 'xxxxx'
          - 'xxxx'
          - 'xxxx'
      bluetoothLowEnergy:
        allowlist:
          - 'xxxxx'
      cluster:
        quorum: 5
        port: 6425
        autoDiscovery: false
```

I know this configuration is not complete. The missing parts would be in the specific host. But the point is, the local.yml file on the host isnt even created. instead there is a file with my name .yml (could be that the file has my name, because its in my room and i just gave the instance my name) where the config is stored in. What am I missing?
