### DISCUSSION TITLE
entityOverrides

### DISCUSSION THREAD

**Discussion by svh1985** [mKeRix/room-assistant#619] [Q&A]
Hey there,

Can anybody explain how to use the entityOverrides?
I've tried multiple setups but the entities still show up as a Mac address in Home Assistant.

```
bluetoothClassic:
  addresses:
    - 'AA:AA:AA:AA:AA:AA'
  entityOverrides:
      'AA:AA:AA:AA:AA:AA':
      id: Apple-Watch
```
Or
```
bluetoothClassic:
  addresses:
    - 'AA:AA:AA:AA:AA:AA'
  entityOverrides:
      'AA:AA:AA:AA:AA:AA':
      id: Apple Watch
```
Or
```
bluetoothClassic:
  addresses:
    - 'AA:AA:AA:AA:AA:AA'
  entityOverrides:
      'AA:AA:AA:AA:AA:AA':
      id: 'Apple Watch'
```
Still shows up as:
![image](https://user-images.githubusercontent.com/5213210/112505194-d695a000-8d8c-11eb-8ee2-cf21ecaaf209.png)

ps I changed MAC to AA:AA.... for obvious reasons 😄
