### DISCUSSION TITLE
Not updating state of known device

### DISCUSSION THREAD

**Discussion by julianpomper** [mKeRix/room-assistant#629] [Q&A]
I use room-assistant with BLE(iOS App) and HA. I added 2 device IDs (from the iOS App):
```
global:
  instanceName: home
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://-:1883'
  mqttOptions:
    username: -
    password: -
bluetoothLowEnergy:
  timeout: 60
  allowlist:
    - '1E5BC071-F07B-49A0-8166-8684CA9CBDD9'
    - 'CEDC0A5C-8C63-46F0-A42E-27856329CDD0'
```

Both show correctly in HA, but over night the second one stopped updating in HA, so the last update was some time ago. In the morning this device left but it is still displaying as "home" in HA because the last update(some hours ago) was that this device is at home. Also checked the API `/entities` and it just shows the first one with state "home" (which is correct).
So my question is if it is expected behaviour that room-assistant does not report "known devices"/devices on the allowlist as "not home" if it does not detect them?
