### DISCUSSION TITLE
[Docker] is installing bluez on the host a requirement?

### DISCUSSION THREAD

**Discussion by beloso** [mKeRix/room-assistant#632] [Q&A] [answered]
I had Bluez installed on my host.
And I have room-assistant running via docker.
Everything worked.

I thought I could uninstall Bluez from the host.
Room-assistant started failing.

Is Bluez a requirement for the docker host?

Here is the compose part:
```
  roomassistant:
    image: mkerix/room-assistant
    container_name: roomassistant
    restart: always
    depends_on:
      - homeassistant
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - $DOCKERDIR/roomassistant/config:/room-assistant/config
      - /var/run/dbus:/var/run/dbus
    labels:
      ## Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
```
