### DISCUSSION TITLE
PI zero w BLE no entity!

### DISCUSSION THREAD

**Discussion by JAJBrouwers** [mKeRix/room-assistant#640] [Q&A]
Hi there all 👋

After a lot of trail en error and a fresh clean install of room assistant, I can't get a entity that I specified white the whitelist!

My HA gets the cluster entity, status is online.
In room assistant I see my device ID found, but I can't get the entity for that device!

After some googling I tried several times the "rights" command etc no luck so far.
```
sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)
sudo setcap cap_net_raw+eip $(eval readlink -f `which hcitool`)
sudo setcap cap_net_admin+eip $(eval readlink -f `which hciconfig`)
```

I find some more problems on the www but everybody is taking about the "rights" command and a reboot and it's fixed! Not for me, any ideas...?

```
cluster:
  weight: 2
  autoDiscovery: false
  port: 6425
  peerAddresses:
      - 192.168.178.46:6425
global:
  instanceName: Zithoek
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://192.168.178.**:1883'
  mqttOptions:
    username: 'mqtt'
    password: '****'
bluetoothLowEnergy:
  allowlist:
    - cf56f49f-427a-462c-9b21-290564099f3d-100-1
  maxDistance: 7
  tagOverrides:
    cf56f49f-427a-462c-9b21-290564099f3d-100-1:
      name: Jeroen BLE
```
* Do I need all the (-) in the ID? I copied/paste from the companion app.

**Comment by JAJBrouwers** [comment]
***UPDATE***

I now have a working ble entity, this is the config:
```
cluster:
  weight: 2
  autoDiscovery: true
  port: 6425
global:
  instanceName: Zithoek
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://192.168.178.**:1883'
  mqttOptions:
    username: 'mqtt'
    password: '****'
bluetoothLowEnergy:
  timeout: 60
  allowlist:
    - fdf6b14d4e884fd0a305d8c1d8e92b8e-100-1
  tagOverrides:
    fdf6b14d4e884fd0a305d8c1d8e92b8e-100-1:
      name: Angela BLE
```
This is working and updates verry fast! almost every 1 ~2 seconds, great! Im now installing a second Pi zero w.
But... for some reason it only works on the phone from my wife, ( Huawei P30 pro) When i add my phone ( OPPO find x2 pro) it see's the phone, but after the timeout it will switch to not_home! As far that i can see it will not transmit the id on the background, i did check my settings/right's for the app! there all good.

Anyone else that as this problem?
