### DISCUSSION TITLE
Integration - "independent" from homeassistant hardware

### DISCUSSION THREAD

**Discussion by sanderlv** [mKeRix/room-assistant#646] [Q&A]
Here is a very fresh joiner of room-assistant. Well, joiner is a big word, I am starting to read an try. I have trouble in basic understanding, please help me out here.

I run homeassistant as a virtual appliance. It is as far as I know the "HomeAssistant OS" installation and I have room-assistant installed as the addon.

Via MQTT I can see some devices which are presented to homeassitant. But now comes the part I do not understand and I would like some guidance here.

It is about the "integration" of sensors in room-assistant. Let's take an example. This sensor:
https://www.room-assistant.io/integrations/omron-d6t.html. it is added in the local.yml (although not connected :-)).

```
# You don't need to add the MQTT details for Home Assistant with the add-on installation, it will be auto-discovered!
global:
  instanceName: Studio1
  integrations:
    - homeAssistant
    - gridEye
entities:
  behaviors:
    d6t_occupancy_count:
      debounce:
        wait: 0.75
        maxWait: 2
gridEye:
  deltaThreshold: 2
  heatmap:
    minTemperature: 16
    maxTemperature: 30
    rotation: 180
```

Showing:
![image](https://user-images.githubusercontent.com/16528916/114527700-91a4b100-9c48-11eb-8567-1fe1f05628e0.png)

Where do I connect this sensor to room-assistant? Do I need to add it as an entity in home assistant? Or can it be on a esphome device? Or does home-assistant rely on the fact that such a sensor need to be connected to a GPIO pin of e.g. a Pi? Please help me on:

How to present sensors to room-assistant in this type of setup.

Thank you in advance.
