### DISCUSSION TITLE
2 nodes for 1 room?

### DISCUSSION THREAD

**Discussion by gbdavidx** [mKeRix/room-assistant#670] [General]
How could i join two node (or three) to one room? for example, i have a livingroom1 rasbperry pi w, a livingroom2 raspberry pi w, both in the same room.  should i create a group? or a min/max sensor (like in monitor)?

**Comment by mKeRix** [comment]
I don't really know the monitor features for grouping, so I can't draw a proper comparison, but for room-assistant I would suggest the following:

- setup your instances with unique names, maybe prefixing it with the room name (e.g. `bedroom-desk` and `bedroom-bed`)
- in Home Assistant, setup a template sensor that will rewrite presence to reflect the proper group
- tune the instances as you normally would

An example for how the template sensor could look like in the HA YAML config if you prefix everything with the room name and split on `-`:

```yaml
- platform: template
  sensors:
    room_presence_person:
      friendly_name: Person Room
      value_template: >
        {{ states('sensor.some_id_room_presence').split('-')[0] }}
```

There's also other ways to achieve such a thing, Home Assistants templates are pretty powerful.
