### DISCUSSION TITLE
Out of range false but state is not home

### DISCUSSION THREAD

**Discussion by firesidethe** [mKeRix/room-assistant#677] [General]
Hey, I'm having a bit of an issue with the distances being properly reported, however the state is set to "not home"

Here's my configuration:

```
global:
  instanceName: livingroom
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
cluster:
  networkInterface: eth0
  port: 6425
  peerAddresses:
    - '192.168.88.97:6425'
    - '192.168.88.98:6425'
    - '192.168.88.99:6425'
bluetoothLowEnergy:
  whitelist:
    - fc0d4fc4a59a
  timeout: 8
  tagOverrides:
    fc0d4fc4a59a:
      name: myNameHere
```

   ```
 "distances": {
      "livingroom": {
        "lastUpdatedAt": "2021-04-29T20:34:35.446Z",
        "distance": 5.4,
        "outOfRange": false
      },
      "kitchen-assistant": {
        "lastUpdatedAt": "2021-04-29T20:34:37.114Z",
        "distance": 8.8,
        "outOfRange": true
      },
      "bedroom-assistant": {
        "lastUpdatedAt": "2021-04-29T20:34:47.590Z",
        "distance": 8.9,
        "outOfRange": true
      }
    },
    "timeout": 8,

    "measuredValues": {
      "livingroom": {
        "rssi": -74.19184077967455,
        "measuredPower": -59
      },
      "kitchen-assistant": {
        "rssi": -79.12074186577395,
        "measuredPower": -59
      },
      "bedroom-assistant": {
        "rssi": -79.35107533101684,
        "measuredPower": -59
      }
    },
    "state": "not_home"
```

What am I doing wrong? Is this something I should report as a bug?
