### DISCUSSION TITLE
How to change timezone inside room-assistant docker container?

### DISCUSSION THREAD

**Discussion by hugalafutro** [mKeRix/room-assistant#680] [Q&A] [answered]
Hi, 

I have a cluster of 3 instances tracking a ble beacon and everything works great, but the containers (and consequently the sensor data sent over mqtt to homeassistant) report time in UTC. which at the moment is hour off GMT 

Is there any way to set the timezone inside the docker container to `Europe/London` ?

for reference my docker-compose.yml:
```
version: '3'
services:
  room-assistant:
    container_name: room-assistant_fr24
    image: mkerix/room-assistant
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - /var/run/dbus:/var/run/dbus
      - ./config:/room-assistant/config
    restart: unless-stopped
```
my config/local.yml
```
global:
  instanceName: home_bedroom_table
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.101:1883'
  mqttOptions:
    username: mosquitto
    password: ***
bluetoothLowEnergy:
  allowlist:
    - 2bf118b8570f46319c5656737ce9e500-0-0
  tagOverrides:
    2bf118b8570f46319c5656737ce9e500-0-0:
      name: oneplus6t_ra_ble
```

Thanks for any ideas!

**Comment by mKeRix** [comment, marked as answer]
I think I added the necessary package to allow changing timezones in Docker just now in 6702b98. I'll make it available for 2.16.1 today. Then you should be able to set the `TZ` environment variable like so:

```yaml
version: '3'
services:
  room-assistant:
    environment:
      TZ: 'Europe/London'
```
