### DISCUSSION TITLE
Interval Issues

### DISCUSSION THREAD

**Discussion by Colorado4Wheeler** [mKeRix/room-assistant#683] [Q&A]
I figured I would throw this out to the community first before opening a ticket.  I've been trying to find the balance between totally smoking my battery life on my watch and having accurate room detection and am having issues.  With no interval set I can get room updates fairly frequently but my watch will go through the battery twice as fast (literally, I've done in-depth analysis of this on spreadsheets using different settings), so I started messing with intervals to find the balance, but the interval is not really the interval as far as I can see.  For instance, right now I have all 4 of my Room-Assistant Pi's set to ```interval: 15``` but nothing is updating anywhere near every 15 seconds - as a test I put my phone right next to a pi and it took 4 minutes and 52 seconds to register as that device being in a different room - and it's not just that Pi, that phone should be easily in reach of all 4 of the Room Assistant Pi's, so one of them should have registered it in 15 seconds right?

All of my configs are pretty much identical:

```YAML
global:
  instanceName: family_room 
  integrations:
    - homeAssistant
    - bluetoothClassic
bluetoothClassic:
  hciDeviceId: 0
  interval: 15 
  addresses:
    - '18:55:e3:64:59:f0'
    - '94:b0:1f:74:28:f7'
    - '10:29:59:65:0a:81'
    - 'd4:a3:3d:f0:2a:12'
homeAssistant:
  mqttUrl: 'mqtt://**.**.**.**:1883'
  mqttOptions:
    username: ********
    password: ********
```
