### DISCUSSION TITLE
newbie: please help with Home Assistant :|

### DISCUSSION THREAD

**Discussion by naamah75** [mKeRix/room-assistant#696] [Q&A]
I'm a newbie with room assistant, I don't understand how to integrate with Home Assistant.
My integration on Home Assistante is installed and running, no errors in the log, but only this warning
```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
```

My room assistant config is the following:
```
global:
  instanceName: my_instance
  integrations:
    - homeAssistant
homeAssistant:
  mqttUrl: mqtt://192.168.1.65:1883
  mqttOptions:
    username: igor
    password: naamah
  discoveryPrefix: ha
```

And I've a ESP32 with ESP32-mqtt-room firmware that succesfully publish in the topic `room_presence/soggiorno` messages like `{"id":"7bb4735b70c3","uuid":"7bb4735b70c3","rssi":-59,"distance":0.14} `and in presence_nodes/soggiorno messages like `{"room":"soggiorno","ip":"192.168.1.189","hostname":"esp32_room_presence","scan_dur":5,"wait_dur":5,"max_dist":2,"disc_ct":10,"rept_ct":3}`
In my Home Assistant config I've a binary sensor with this config
```
- platform: mqtt
  name: ESP32 ROOM PRESENCE
  state_topic: "presence_nodes/soggiorno"
  json_attributes_topic: "presence_nodes/esp32_room_presence/tele"
  payload_on: "CONNECTED"
  payload_off: "DISCONNECTED"
  device_class: connectivity
```
that correctly reporte the ESP32 status
And the following sensor that might not work cause it's everytime "not_home"
```
- platform: mqtt_room
  device_id: "7bda4ad966f1"
  name: 'unknown Room Presence'
  state_topic: 'room_presence/soggiorno'
  timeout: 60
  away_timeout: 120
```

How room assistant will work? how to integrate correctly in Home Assistant... what to expect from room assistance? Where I'm wrong?

**Comment by mKeRix** [comment]
So, room-assistant registers its own room presence entities automatically via MQTT auto discovery. The state of these is calculated by the room-assistant instances, since I can use some more logic on the RA end to improve detection compared to mqtt_room. If you only have RA nodes that means all you have to do is to just spin it up with the MQTT information, the rest will happen automatically (no HA configuration needed aside from connecting it to MQTT as well).

If you want to combine room-assistant with other software via mqtt_room you can configure the `homeAssistant` integration to send data in the required format for this, it's called `sendMqttRoom` ([docs](https://www.room-assistant.io/integrations/home-assistant.html#settings)).

**Comment by naamah75** [comment]
Found the trick! On Home Assistant the `instanceName `on `local.yaml` must be the same defined in `room` settings of the `Settings.h` of _ESP32-mqtt-room_.
In way that `instanceName `match with the topic `room_presence/soggiorno`.
Now the problem is... I've multiple ESP32 devices, each one in one different room, each one with different `room` name... how I can set multiple `instanceName `on the same Home Assistant integration?
In other word I have many topics something like `room_presence/sal`a, `room_presence/cucina` and  so on... I suppose that I must have more `instanceName` like `sala` and `cucina` on the same `local.yaml` file of the same Home Assistant integration.
How I can do that?

p.s: my `local.yaml`
```
global:
  instanceName: soggiorno
  integrations:
    - homeAssistant
homeAssistant:
  mqttUrl: mqtt://192.168.1.xxx:1883
  mqttOptions:
    username: *****
    password: *****
  discoveryPrefix: ha
```

**Reply by naamah75** [reply]
Found by myself... right now... :)

```
global:
  instanceName: 
    - soggiorno
    - sala
  integrations:
    - homeAssistant
homeAssistant:
  mqttUrl: mqtt://192.168.1.xxx:1883
  mqttOptions:
    username: *****
    password: *****
  discoveryPrefix: ha
```
