### DISCUSSION TITLE
Rival Clusters Forming, Can't Get Them To Get Along

### DISCUSSION THREAD

**Discussion by MagicMountainMan** [mKeRix/room-assistant#714] [Q&A] [answered]
My setup was 7 RPi ZeroW's around my place, I recently added an 8th one and all hell broke loose and room-assistant won't work properly anymore. Two clusters seem to always form on my network (a dedicated IOT VLAN, if it matters) and my phone (using HASS Android Companion app) will only ever see the one cluster, but not the other.

Below is how I did have everything set up and it didn't work. Just now I turned autoDiscovery back to true and deleted networkInterface entirely to let room-assistant auto decide (I saw that in someone else's issue they had) and naturally I delete the IP address of the peer that the config file is on. I even updated all of the RPi's (npm and sudo apt update/full-upgrade) but nothing is helping the rival clusters from forming. Maybe it's been a long day and I'm just missing something dumb?

Edit: And I'm going to be honest about my skill level using Raspberry Pi's, it's basically non-existent. I have so many other hobbies and work related things that take up space in my brain that Raspberry Pi knowledge has sunk to the bottom.

```
global:
  instanceName: ***
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
cluster:
  autoDiscovery: false
  networkInterface: wlan0
  port: 6425
  weight: ***
  quorum: 5
  peerAddresses:
    - 192.168.10.10:6425
    - 192.168.10.11:6425
    - 192.168.10.12:6425
    - 192.168.10.13:6425
    - 192.168.10.14:6425
    - 192.168.10.15:6425
    - 192.168.10.16:6425
    - 192.168.14.17:6425
homeAssistant:
  mqttUrl: mqtt://192.168.104.5:1883
  mqttOptions:
    username: ***
    password: ***
bluetoothLowEnergy:
  whitelist:
    - xxx4D3
    - xxx-100-1
    - xxx-100-1
  maxDistance: 9
  timeout: 20
  tagOverrides:
    xxx4D3:
      name: AndrewBLE
    xxx-100-1:
      name: BrandonBLE
    xxx-100-1:
      name: ChristinaBLE
```
