### DISCUSSION TITLE
Very delayed Device Positioning

### DISCUSSION THREAD

**Discussion by jlvandusen** [mKeRix/room-assistant#746] [Q&A]
I have a 4 Raspberry Pi Zero Wifi configuration running Room-Assistant 
tied to Home Assistant install running MQTT

All the units are checking in...  and I have a quorum
I have in my local.yml on each system
cluster:
  port: 6425
  peerAddresses:
    - 192.168.1.71:6425
    - 192.168.1.72:6425
    - 192.168.1.73:6425
    - 192.168.1.74:6425
    - 
I added just my iPhone's BT MAC to bluetoothClassic
bluetoothClassic:
  addresses:
    - '5C:87:30:E9:72:18' # James iPhone for testing

It finds my phone...

I have a mudroom, sittingroom, kitchen and diningroom
when I place the phone in the kitchen... it eventually (after 60secs or more) switches to kitchen
I then move it to mudroom
it may take 2mins for it to switch to mudroom... it also flips to unavailable (instead of home) several times.

What could be wrong?

**Comment by warez1975** [comment]
Same problem here... Room Assistant 2.18.4 on 4 instances running on RPI3B+

**Comment by jlvandusen** [comment]
@mKeRix looking for assistance with this, at this point I don't know where to go - I would love to have a working viable solution but the delays make it not functional.   It may be due to various items:
I have a orbi_mesh that has 3 satellites
I have lots of wifi items running at 2.4ghz throughout the house

**Reply by warez1975** [reply]
try to play with this values:

```
bluetoothClassic:
  interval: 20
  scanTimeLimit: 1.5
  timeoutCycles: 1
  inquireFromStart: true
```
while we wait for some other suggestions

**Comment by benjycov** [comment]
Hi,

BTC is a bit slow, you can adjust the intervals and scans but its just a big laggy. 

BLE (using the iPhone companion app) is completely different and very responsive, once you have your calibration sorted (which the app helps with) you can literally get it so it swaps the instant you change rooms.

The only downside of BLE are the issues you can find elsewhere with devices dropping off, you may need to consider a 'belt and braces' approach and use both.

Ben

**Reply by warez1975** [reply]
> Hi,
> 
> BTC is a bit slow, you can adjust the intervals and scans but its just a big laggy.
> 
> BLE (using the iPhone companion app) is completely different and very responsive, once you have your calibration sorted (which the app helps with) you can literally get it so it swaps the instant you change rooms.
> 
> The only downside of BLE are the issues you can find elsewhere with devices dropping off, you may need to consider a 'belt and braces' approach and use both.
> 
> Ben

Please may you share your BLE config?

Thank you

**Reply by benjycov** [reply]
For sure, its pretty straight forward:

First of all in the global section you need:

```
global:
  instanceName: hallway
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
```

and then you need the BLE config, the allowlist is built up from the ID given on the Room Assistant companion app.

```
  bluetoothLowEnergy:
    timeout: 120
    allowlist:
      - '9D83E726-7584-4200-8519-0B48612?????'
      - 'EC727FF3-1823-445B-9AB2-3EC4920?????'
      - '38266D31-10BE-4C31-8AF2-7C56EFA7?????'
      - '93A338F2-7350-47F2-BB17-FEC31EB7?????'
    tagOverrides:
      9D83E726-7584-4200-8519-0B48612?????:
        name: Ben
      EC727FF3-1823-445B-9AB2-3EC4920?????:
        name: Wife
      38266D31-10BE-4C31-8AF2-7C56EFA7?????:
        name: Child1
      93A338F2-7350-47F2-BB17-FEC31EB7?????:
        name: Child2
```
