### DISCUSSION TITLE
Manually Integration in HomeAssistant

### DISCUSSION THREAD

**Discussion by mitch55500** [mKeRix/room-assistant#769] [Q&A]
This is a noob question...
Room-Assistant is installed as an add-on of homeassistant.
Here my configuration :
```
global:
   instanceName: Maison
   integrations:
    - mqtt
#    - homeAssistant
    - bluetoothLowEnergy
#   - bluetoothClassic

#homeAssistant:
#  mqttUrl: 'mqtt://192.168.1....'
#  mqttOptions:
#    username: username
#    password: password
#  discoveryPrefix: homeassistant

  
mqtt:
  mqttUrl: 'mqtt://192.168.1......
  mqttOptions:
    username: username
    password: pssword
  qos: 1
  retain: true
    
#bluetoothClassic:
#  minRssi: -20
#  hciDeviceId: 0
#  addresses:
#    - 'BC:A5:8B:2A:8D:AB' #Mobile Sébastien

bluetoothLowEnergy:
  hciDeviceId: 0
  timeout: 60
  allowlist:
    - f0c601711b0e45879c05793aa97765c7-100-1
  tagOverrides:
    f0c601711b0e45879c05793aa97765c7-100-1:
      name: note_9_ble
```

I'd like to integrate my device in HomeAssistant MANUALLY. How to do ?
Here is the topic mqtt : 

`{"entity":{"attributes":{"distance":14.9,"lastUpdatedAt":"2021-06-20T10:40:40.175Z"},"id":"ble-f0c601711b0e45879c05793aa97765c7-100-1","name":"note_9_ble Room Presence","distributed":true,"stateLocked":true,"distances":{"Maison":{"lastUpdatedAt":"2021-06-20T10:40:40.175Z","distance":14.9,"outOfRange":false}},"timeout":60,"measuredValues":{"Maison":{"rssi":-84.85156322711492,"measuredPower":-59}},"state":"Maison"},"diff":[{"path":"/measuredValues/Maison","oldValue":{"rssi":-84.93624153054385,"measuredPower":-59},"newValue":{"rssi":-84.85156322711492,"measuredPower":-59}},{"path":"/distances/Maison","oldValue":{"lastUpdatedAt":"2021-06-20T10:40:39.151Z","distance":15,"outOfRange":false},"newValue":{"lastUpdatedAt":"2021-06-20T10:40:40.175Z","distance":14.9,"outOfRange":false}},{"path":"/attributes/distance","oldValue":15,"newValue":14.9},{"path":"/attributes/lastUpdatedAt","oldValue":"2021-06-20T10:40:39.151Z","newValue":"2021-06-20T10:40:40.175Z"}],"hasAuthority":true}`

Here what I do in sensor.yaml : 

```
- platform: mqtt_room
  device_id: "ble-f0c601711b0e45879c05793aa97765c7-100-1"
  name: 'note mqtt_room'
  state_topic: "room-assistant/maison/bluetooth-low-energy-presence-sensor/ble-f0c601711b0e45879c05793aa97765c7-100-1"
  timeout: 10
  away_timeout: 15
```

The entity is created but I have no distance information and the state stay to "not_home"
