### DISCUSSION TITLE
Please explain Cluster configuration please :)

### DISCUSSION THREAD

**Discussion by BelgarionNL** [mKeRix/room-assistant#785] [Q&A]
How do you set up the configuration when using more because the both give each other leader...
It would make sense then only the leader has all the info and the rest of the devices only have the relevant parts to connect to the leader? 

Maybe I missed it in the docs but please help.

(I changed ip's and mac numbers.)

```
cluster:
  autoDiscovery: false  
  port: 6425
  peerAddresses:
    - 10.0.0.69:6425

global:
  instanceName: rpi3-1
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
    # - bluetoothClassic
    
homeAssistant:
  mqttUrl: 'mqtt://10.0.0.10:1883'
  # mqttOptions:
# bluetoothClassic:
  # addresses:
    # - B0:35:B5:D0:37:14
    
bluetoothLowEnergy:
  timeout: 60
  allowlist:
  - 443B83FC-0892-4A08-AD45-36A8F85CC92E
  - e5f7ab6f83dd
  maxDistance: 5.5
  tagOverrides:
    443B83FC-0892-4A08-AD45-36A8F85CC92E:
      name: iPhone
      # # measuredPower: -61
      # # batteryMask: 0x0000FF00
    e5f7ab6f83dd:  
      name: versa 2   

```

```
cluster:
  autoDiscovery: false  
  port: 6425
  peerAddresses:
    - 10.0.0.68:6425

global:
  instanceName: rpi3-2
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
    # - bluetoothClassic
    
homeAssistant:
  mqttUrl: 'mqtt://10.0.0.10:1883'
  # mqttOptions:
# bluetoothClassic:
  # addresses:
    # - B0:35:B5:D0:37:14
    
bluetoothLowEnergy:
  timeout: 60
  allowlist:
  - 443B83FC-0892-4A08-AD45-36A8F85CC92E
  - e5f7ab6f83dd
  maxDistance: 3
  tagOverrides:
    443B83FC-0892-4A08-AD45-36A8F85CC92E:
      name: iPhone
      # # measuredPower: -61
      # # batteryMask: 0x0000FF00
    e5f7ab6f83dd:  
      name: versa 2

```
