### DISCUSSION TITLE
minRssi correct settings - BT Classic on 2.18.4

### DISCUSSION THREAD

**Discussion by warez1975** [mKeRix/room-assistant#789] [Q&A]
Hi, may someone could help me to setting right my minRssi parameter? The min (1 meter) distance between my room assistance instance and my phone is -65, the max distance (approx 4 meters) is -72 and this is what I have in my config:

```
bluetoothClassic:
  interval: 5
  scanTimeLimit: 1
  timeoutCycles: 2
  inquireFromStart: true
  minRssi:
    default: -65
    'd8:55:75:ac:b5:ce': -70
    '14:d1:9e:5f:6e:c7': -70
```

I know that this is a noob question but i'm going mad with this settings.

Thank you :) 

BTW:
I'm running Room Assistant 2.18.4 on Pi3B+
