### DISCUSSION TITLE
Samsung fit 2 not detected when paired with phone

### DISCUSSION THREAD

**Discussion by stancho44** [mKeRix/room-assistant#820] [Q&A]
Hi, I recently got a galaxy fit 2 and I've been having tracking issues with the device. The galaxy fit 2 would only be connected if I turn my phone's Bluetooth off and the fit 2 would broadcast Bluetooth signals. I'm not sure if this is a software limitation or if there's a config I can change to bypass turning off Bluetooth on my phone and have the tracker on but here's my yml file that I've put on all my 3 raspberry pi zero w
```
global:
  cluster:
    autoDiscovery: true
  instanceName: Living Room
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://homeassistant.local:1883'
  mqttOptions:
    username: [Secret]
    password: [Secret]
  sendMqttRoom: true
bluetoothClassic:
  interval: 10
  addresses:
    - dc:f0:90:43:51:b5
bluetoothLowEnergy:
  allowlist:
    - 1039172933af
    - 5a73f9ef461747d086bc733306a6f4fe-0-0
```
Any help would be appreciated. As of posting, I'm figuring out how to turn off my phone's Bluetooth from home assistant to soft fix this problem.
