### DISCUSSION TITLE
Bluetooth service not working on raspberry pi 4?

### DISCUSSION THREAD

**Discussion by clinoid** [mKeRix/room-assistant#846] [Q&A]
I have installed room assistant on a raspberry pi 4. I have followed all of the commands per the online instructions with the exception of the OS, which is not the lite version. The only other service that I have running is a service hosting a usb stick over ip; everything else is essentially stock. 

I have been able to successfully install RA on a RP zero W, and that seems to work fine. The issue I have is with the Raspberry pi 4. The instance of room assistance does successfully communicate with the mqtt server, and with the other instance of RA, but is unable to see any of the devices that the other instance is able to. When I run room assistant, I continually get the following errors: 

Any thoughts? Thanks in advance. 

```
8/1/2021, 10:46:21 PM - error - BluetoothService: Inquiring RSSI via BT Classic failed: Command failed: hcitool -i hci0 cc "CC:21:19:AF:7A:D4" && hcitool -i hci0 rssi "CC:21:19:AF:7A:D4"
Invalid device: No such device

8/1/2021, 10:46:31 PM - error - BluetoothService: Inquiring RSSI via BT Classic failed: Command failed: hcitool -i hci0 cc "24:5A:B5:6A:49:1B" && hcitool -i hci0 rssi "24:5A:B5:6A:49:1B"
Invalid device: No such device

8/1/2021, 10:46:41 PM - error - BluetoothService: Inquiring RSSI via BT Classic failed: Command failed: hcitool -i hci0 cc "90:DD:5D:71:E5:F2" && hcitool -i hci0 rssi "90:DD:5D:71:E5:F2"
Invalid device: No such device
```

My config is below:

```
global:
  instanceName: RPi4
  integrations:
    - homeAssistant
    - bluetoothClassic
  cluster:
    port: 6425
    weight: 100
    peerAddresses:
      - 192.168.20.119
      - 192.168.20.129
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.79:1883'
  mqttOptions:
    username: ####
    password: ####
bluetoothClassic:
  addresses:
    - CC:21:19:AF:7A:D4 ###
    - 24:5A:B5:6A:49:1B ###
    - 90:DD:5D:71:E5:F2 ###
```
