### DISCUSSION TITLE
Quorum # API Responses

### DISCUSSION THREAD

**Discussion by ckellyusa** [mKeRix/room-assistant#859] [Q&A] [answered]
For setting the quorum parameter, is any number equal to or less than the total number of room-assistant nodes acceptable?  So if I have 8 pi's running room-assistant and I only want 1 leader, can I set the quorum to 8?

And when I execute the entities command in the RA:6415/api page, should we get a response from every RA node?  I usually only get responses from about 4 of the 8.

Examples below:
```shell
[
  {
    "attributes": {
      "nodes": [
        "laundryroom",
        "livingroom",
        "mastersuite",
        "garage",
        "kitchen",
        "mediaroom",
        "sparebedroom",
        "office"
      ]
    },
    "id": "status-cluster-size",
    "name": "office Cluster Size",
    "distributed": false,
    "stateLocked": true,
    "state": 8
  },
  {
    "attributes": {
      "quorumReached": true
    },
    "id": "status-cluster-leader",
    "name": "office Cluster Leader",
    "distributed": false,
    "stateLocked": true,
    "state": "office"
  },
  {
    "attributes": {},
    "id": "ble-426c7565436861726d426561636f6e73-XX-XX-tracker",
    "name": "Voodoo Tracker",
    "distributed": true,
    "stateLocked": true,
    "state": "not_home"
  },
  {
    "attributes": {
      "lastUpdatedAt": "2021-08-07T14:29:20.283Z"
    },
    "id": "ble-426c7565436861726d426561636f6e73-XX-XX",
    "name": "Voodoo Room Presence",
    "distributed": true,
    "stateLocked": true,
    "distances": {
      "livingRoom": {
        "lastUpdatedAt": "2021-08-07T14:27:25.380Z",
        "distance": 0,
        "outOfRange": false
      },
      "office": {
        "lastUpdatedAt": "2021-08-07T14:28:10.346Z",
        "distance": 0.6,
        "outOfRange": false
      },
      "LaundryRoom": {
        "lastUpdatedAt": "2021-08-07T15:20:38.810Z",
        "distance": 2.9,
        "outOfRange": true
      },
      "kitchen": {
        "lastUpdatedAt": "2021-08-07T15:19:23.820Z",
        "distance": 3.3,
        "outOfRange": true
      }
    },
    "timeout": 60,
    "measuredValues": {
      "livingRoom": {
        "rssi": -49.738121057017565,
        "measuredPower": -71
      },
      "office": {
        "rssi": -68,
        "measuredPower": -71
      },
      "LaundryRoom": {
        "rssi": -82.3375184753721,
        "measuredPower": -71
      },
      "kitchen": {
        "rssi": -83.50064263271483,
        "measuredPower": -71
      }
    },
    "state": "not_home"
  },
  {
    "attributes": {},
    "id": "ble-fda50693a4e24fb1afcfc6eb07647825-XX-XX-tracker",
    "name": "Tester Tracker",
    "distributed": true,
    "stateLocked": true,
    "state": "home"
  },
  {
    "attributes": {
      "distance": 0,
      "lastUpdatedAt": "2021-08-07T15:21:31.160Z"
    },
    "id": "ble-fda50693a4e24fb1afcfc6eb07647825-XX-XX",
    "name": "Tester Room Presence",
    "distributed": true,
    "stateLocked": true,
    "distances": {
      "livingRoom": {
        "lastUpdatedAt": "2021-08-07T15:21:30.131Z",
        "distance": 0.1,
        "outOfRange": false
      },
      "kitchen": {
        "lastUpdatedAt": "2021-08-07T15:21:31.160Z",
        "distance": 0,
        "outOfRange": false
      },
      "LaundryRoom": {
        "lastUpdatedAt": "2021-08-07T15:21:30.257Z",
        "distance": 1.8,
        "outOfRange": true
      },
      "MediaRoom": {
        "lastUpdatedAt": "2021-08-07T15:19:53.814Z",
        "distance": 2.4,
        "outOfRange": true
      }
    },
    "timeout": 60,
    "measuredValues": {
      "livingRoom": {
        "rssi": -62.03027848513203,
        "measuredPower": -78
      },
      "kitchen": {
        "rssi": -56.19583865625977,
        "measuredPower": -78
      },
      "LaundryRoom": {
        "rssi": -84.72991167748762,
        "measuredPower": -78
      },
      "MediaRoom": {
        "rssi": -87.89540703818356,
        "measuredPower": -78
      }
    },
    "state": "kitchen"
  },
  {
    "attributes": {},
    "id": "ble-426c7565436861726d426561636f6e73-XX-XX-tracker",
    "name": "Monkey Tracker",
    "distributed": true,
    "stateLocked": true,
    "state": "home"
  },
  {
    "attributes": {
      "distance": 0.2,
      "lastUpdatedAt": "2021-08-07T15:21:19.916Z"
    },
    "id": "ble-426c7565436861726d426561636f6e73-XX-XX",
    "name": "Monkey Room Presence",
    "distributed": true,
    "stateLocked": true,
    "distances": {
      "office": {
        "lastUpdatedAt": "2021-08-07T15:17:29.393Z",
        "distance": 1.1,
        "outOfRange": false
      },
      "LaundryRoom": {
        "lastUpdatedAt": "2021-08-07T15:21:37.811Z",
        "distance": 2.4,
        "outOfRange": true
      },
      "livingRoom": {
        "lastUpdatedAt": "2021-08-07T15:21:19.916Z",
        "distance": 0.2,
        "outOfRange": false
      }
    },
    "timeout": 60,
    "measuredValues": {
      "office": {
        "rssi": -72.26542411512752,
        "measuredPower": -71
      },
      "LaundryRoom": {
        "rssi": -80.10470025637811,
        "measuredPower": -71
      },
      "livingRoom": {
        "rssi": -58.941668124193086,
        "measuredPower": -71
      }
    },
    "state": "livingRoom"
  },
  {
    "attributes": {},
    "id": "ble-426c7565436861726d426561636f6e73-XX-XX-tracker",
    "name": "Boog Tracker",
    "distributed": true,
    "stateLocked": true,
    "state": "home"
  },
  {
    "attributes": {
      "distance": 3,
      "lastUpdatedAt": "2021-08-07T15:20:47.945Z"
    },
    "id": "ble-426c7565436861726d426561636f6e73-XX-XX",
    "name": "Boog Room Presence",
    "distributed": true,
    "stateLocked": true,
    "distances": {
      "MediaRoom": {
        "lastUpdatedAt": "2021-08-07T15:21:27.727Z",
        "distance": 2.5,
        "outOfRange": true
      },
      "kitchen": {
        "lastUpdatedAt": "2021-08-07T15:20:47.945Z",
        "distance": 3,
        "outOfRange": false
      }
    },
    "timeout": 60,
    "measuredValues": {
      "MediaRoom": {
        "rssi": -80.64879435505348,
        "measuredPower": -71
      },
      "kitchen": {
        "rssi": -82.62627762750981,
        "measuredPower": -71
      }
    },
    "state": "kitchen"
  }
]
```

My configuration file:
```yml
global:
  integrations:
    - bluetoothLowEnergy
    - mqtt
bluetoothLowEnergy:
  allowlist:
    - 426c7565436861726d426561636f6e73-XX-XX
    - fda50693a4e24fb1afcfc6eb07647825-XX-XX
    - 426c7565436861726d426561636f6e73-XX-XX
    - 426c7565436861726d426561636f6e73-XX-XX
  maxDistance: 2
#  rssiFactor: 
  tagOverrides:
    426C7565436861726D426561636F6E73-XX-XX9:
     name: Boog
    fda50693a4e24fb1afcfc6eb07647825-XX-XX:
     name: Tester
    426C7565436861726D426561636F6E73-XX-XX:
     name: Monkey
    426C7565436861726D426561636F6E73-XX-XX:
     name: Voodoo
mqtt:
  mqttUrl: 'mqtt://192.168.1.80:1883'
cluster:
  autoDiscovery: false
  weight: 50
  quorum: 7
  peerAddresses:
    - 192.168.1.25:6425 #Laundry Room
    - 192.168.1.87:6425 #Spare Bedroom
    - 192.168.1.121:6425 #Media Room
    - 192.168.1.150:6425 #Kitchen
#    - 192.168.1.167:6425 #Office
    - 192.168.1.185:6425 #Master Suite
    - 192.168.1.218:6425 #Garage
    - 192.168.1.232:6425 #Living Room
```
