### DISCUSSION TITLE
Home Assistant - Command failed: hcitool -i hci0 cmd 0x01 0x0008

### DISCUSSION THREAD

**Discussion by alex-mikhaylov** [mKeRix/room-assistant#863] [Q&A]
Hello everyone,

I've set up the Room Assistant add-on on my Home Assistant instance according to the documentation and added 2 devices to be tracked using BT Classic. When the add-on starts, I see the following errors in the logs:
```
8/9/2021, 6:41:39 PM - error - BluetoothClassicService: Failed to retrieve RSSI for xx:xx:xx:xx:xx:xx: Command failed: hcitool -i hci0 cmd 0x01 0x0008
8/9/2021, 6:42:09 PM - error - BluetoothClassicService: Failed to retrieve RSSI for xx:xx:xx:xx:xx:xx: Command failed: hcitool -i hci0 cmd 0x01 0x0008
```

My configuration file is:
```
global:
  instanceName: entrance
  integrations:
    - homeAssistant
    - bluetoothClassic
bluetoothClassic:
   minRssi: -20
   hciDeviceId: 0
   interval: 30
   addresses:
     - 'xx:xx:xx:xx:xx:xx'
     - 'xx:xx:xx:xx:xx:xx'
```

Any help would be appreciated.
