### DISCUSSION TITLE
[Home Assistant] ClusterService: Failed to start mdns discovery (dns service error: unknown)

### DISCUSSION THREAD

**Discussion by garv3** [mKeRix/room-assistant#873] [General]
Hey all,

I am currently trying to build a Room Assistant cluster for room presence detection.
Currently I have a Home Assistant OS installation running the Room Assistant addon. This is what I used for simple presence detection until now.
Now I added a Raspberry Pi Zero W running room assistant and want to build the cluster.

Hiere is the cluster block of the config of HA's Room Assistant instance.
```
cluster:
  autoDiscovery: true
  port: 6425
  weight: 1000
```
For the installation on the Pi Zero W I set the weight to 100 so the HA installation should become the leader. The rest is identical.

The problem now is that the logs on the HA installation show:
```
error - ClusterService: Failed to start mdns discovery (dns service error: unknown)
```
So the cluster cannot be created.

What might be the problem?
Thanks in advance!

**Comment by CobraDunn** [comment]
The mdns discovery doesn't work correctly with the HA add-on. You can ignore the error, but you do need to add the addresses of each instance to the cluster like below. The cluster details should be the same for each instance, with the exception of weight:
```
cluster:
  port: 6425
  autoDiscovery: true
  weight: 100
  timeout: 60
  peerAddresses:
    - 192.168.7.211:6425
    - 192.168.7.118:6425
```

**Reply by garv3** [reply]
So autoDiscovery does not work with HA?

**Comment by garv3** [comment]
I added the peer addresses:
```
cluster:
  autoDiscovery: true
  port: 6425
  weight: 1000
  timeout: 60
  peerAddresses:
    - 192.168.0.43:6425
    - 192.168.0.31:6425
```
Both seem to be working but now the instance with the lower weight is selected as the leader. Why is that?
