### DISCUSSION TITLE
How to make RA report the distance?

### DISCUSSION THREAD

**Discussion by garv3** [mKeRix/room-assistant#875] [Q&A]
I am using RA with Home Assistant and the entities created via MQTT only have the state (home/not_home/away/room) but no information about the distance?
How can I make the distance show as a entity parameter?

EDIT: Okay, I found the info. Was hidden in the HA UI.

**Comment by warez1975** [comment]
> EDIT: Okay, I found the info. Was hidden in the HA UI.

where did you find the distance parameter?

Thank you

**Reply by garv3** [reply]
Sorry, I just don't remember and can't find it anymore 🤔

**Comment by 51av0sh** [comment]
It's an attribute of the presence sensor that's created 

`states.sensor.xxx_room_presence.attributes.distance`

You can create a sensor for it like this:

```
- platform: template
  sensors:
    #Extract Distance from room-assistant
    xxx_room_proximity:
      friendly_name: "xxx Room Proximity"
      value_template: '{{ states.sensor.xxx_room_presence.attributes.distance }}'
      unit_of_measurement: 'ft'
      unique_id: xxx_room_proximity
```

This will create a new sensor that shows the distance:

`sensor.xxx_room_proximity`
