### DISCUSSION TITLE
MqttService: undefined

### DISCUSSION THREAD

**Discussion by SayAndre** [mKeRix/room-assistant#913] [Q&A]
Hey,

I'm currently stuck getting the devices into my MQTT Broker ( ioBroker ).
Everything with room-assistant on my pi zero w works fine but the MQTT Service.

I just get the error MqttService: undefined.
Tried several different ports and stuff. 

my local.yml:

```
global:
  integrations:
    - mqtt
    - bluetoothLowEnergy
mqtt:
  mqttUrl: mqtt://myipadress:1883
bluetoothLowEnergy:
  timeout: 60
  allowlist:
    - my iPhone
```

I'm using https:// for my iobroker and the iobroker ip is the mqtt IP but that shouldn't matter right ? 
I also tried installing a seperate MQTT Broker adapter with another port but get the same error. Am I missing something ? 

EDIT:
I'm not using login credentials for MQTT yet.
