### DISCUSSION TITLE
Android + iOS BLE configuration

### DISCUSSION THREAD

**Discussion by harphere** [mKeRix/room-assistant#950] [Q&A]
Hello,

I set up an Android (Pixel 5) and iOS (iPhone 12 Pro) in the config below but can't seem to get the correct `maxDistance`. When both phones are in the living room, my only RA instance, the maxDistance varies greatly. Is there a way to set a `maxDistance` for each `tagOverrides`? The Pixel would register as 'livingroom' but the iPhone refuses to because it's `maxDistance` is greater and thus registers as 'not_home'. Or is there another attribute I should be using to help get both phones to register 'livingroom'?

```
global:
  instanceName: livingroom
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://192.168.50.xx:1883'
bluetoothLowEnergy:
  timeOut: 60
  allowlist:
    - .*-100-.*
    - <iphone ble id>
  allowlistRegex: true
  maxDistance: 3
  tagOverrides:
    <pixel ble id>-100-1:
      name: Pixel 5
      measuredPower: -74
    <iphone ble id>:
      name: iPhone 12
      measuredPower: -59

```

Thanks for any help
