### ISSUE TITLE
HA Supervisor log shows a lot of warnings "<...> does not exist in the schema ..."

### ISSUE THREAD

**Issue by N3rdix** [mKeRix/room-assistant#1000]
**Describe the bug**
Some time ago room-assistant started to flood the supervisor logs with warning messages i seemingly can't fix as there is no longer a configuration of the add-on where those parameters could be removed.
Is there a way to get rid of those warning somehow?

**Relevant logs**
```
21-12-22 07:48:42 WARNING (MainThread) [supervisor.addons.options] Option 'bluetoothLowEnergy' does not exist in the schema for room-assistant (6e66619d_room_assistant)
21-12-22 07:48:42 WARNING (MainThread) [supervisor.addons.options] Option 'bluetoothClassic' does not exist in the schema for room-assistant (6e66619d_room_assistant)
21-12-22 07:48:42 WARNING (MainThread) [supervisor.addons.options] Option 'omronD6t' does not exist in the schema for room-assistant (6e66619d_room_assistant)
21-12-22 07:48:42 WARNING (MainThread) [supervisor.addons.options] Option 'gridEye' does not exist in the schema for room-assistant (6e66619d_room_assistant)
21-12-22 07:48:42 WARNING (MainThread) [supervisor.addons.options] Option 'homeAssistant' does not exist in the schema for room-assistant (6e66619d_room_assistant)
21-12-22 07:49:42 WARNING (MainThread) [supervisor.addons.options] Option 'global' does not exist in the schema for room-assistant (6e66619d_room_assistant)
21-12-22 07:49:42 WARNING (MainThread) [supervisor.addons.options] Option 'cluster' does not exist in the schema for room-assistant (6e66619d_room_assistant)
```

**Relevant configuration**
```
global:
  instanceName: Küche
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
bluetoothLowEnergy:
  hciDeviceId: 0
  updateFrequency: 8
  timeout: 30
  #minDiscoveryLogRssi: -75
  denylist: []
```

**Expected behavior**
No warnings or at least a description how to resolve the error

**Environment**
 - room-assistant version: 2.19
 - installation type: Home Assistant supervised core-2021.11.5
 - hardware: Raspberry Pi 4
 - OS: Linux
