### ISSUE TITLE
API distance doesn't match with entity state

### ISSUE THREAD

**Issue by davidrustingha** [mKeRix/room-assistant#1023]
**Describe the bug**
In Home Assistant the entities sometimes switch to not_home even when stationary. The maxDistance values are set correctly.
When I check the /entities endpoint I can see the rooms that are out of range, and the right one is always in range, but the entities still don't show the correct state.

**To reproduce**
Install RA on Pi zero

**Relevant logs**
No weird errors or messages are shown in the log, but happy to post them if needed

**Relevant configuration**
This is the config for the livingroom, the rest is exactly set up the same, except for the maxDistance values

```
cluster:
  autoDiscovery: false
  peerAddresses:
    - IP:6425 #Slaapkamer
    - IP:6425 #Woonkamer
    - IP:6425 #Werkkamer
    - IP:6425 #Kledingkamer
    - IP:6425 #Badkamer
  quorum: 4
  weight: 5

global:
  instanceName: Woonkamer
  integrations:
    - homeAssistant
    - bluetoothLowEnergy

homeAssistant:
  mqttUrl: 'mqtt://IP:1883'
  mqttOptions:
    username: username
    password: passwd

bluetoothLowEnergy:
  instanceBeaconEnabled: false
  processIBeacon: true
  onlyIBeacon: true
  timeout: 60
  updateFrequency: 0
  hciDeviceId: 0
  maxDistance: 10
  allowlist:
    - xxxxxxxxx-100-1
    - xxxxxxxxx-100-1
  tagOverrides:
    xxxxxxxxx-100-1:
      name: Android van David (Room Assistant)
      id: android-van-david
      measuredPower: -65
    xxxxxxxxx-100-1:
      name: Android van Lusan (Room Assistant)
      id: android-van-lusan
      measuredPower: -65
```

**Expected behavior**
If the distances are set correctly, I would expect the entities to have the correct value/room name.

**Environment**
 - room-assistant version: [2.19.1]
 - installation type: [NodeJS]
 - hardware: [Raspberry Pi Zero W]
 - OS: [Linux]

**Additional context**
