### ISSUE TITLE
[Docker] Crash due to hciconfig errors and TypeError

### ISSUE THREAD

**Issue by Obbay2** [mKeRix/room-assistant#1038]
**Describe the bug**
Room assistant container crashes after some time (about a day) with `TypeError: Cannot read properties of undefined (reading 'length')`

**To reproduce**
Run the container for an extended period of time, eventually it will crash. I have this setup in a cluster, but I don't think this is contributing to the bug?

**Relevant logs**
**Full Logs:**
https://gist.github.com/Obbay2/6456160e2f502acfbf7ba990a79b232c

**Truncated logs:**
```
1/20/2022, 4:46:33 PM - info - BluetoothLowEnergyService: Discovered nearby BLE peripheral Chromecast1659 with ID 6a77f9b0dccd and RSSI -89
1/20/2022, 4:47:04 PM - info - BluetoothLowEnergyService: Discovered nearby BLE peripheral fb32b513a07b with ID fb32b513a07b and RSSI -98
1/20/2022, 4:47:50 PM - info - BluetoothLowEnergyService: Discovered nearby BLE peripheral 4a96d8587fa4 with ID 4a96d8587fa4 and RSSI -85
1/20/2022, 4:47:59 PM - info - BluetoothLowEnergyService: Attempting app discovery for tag 630beaba62f8
1/20/2022, 4:48:42 PM - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting
1/20/2022, 4:48:42 PM - error - undefined: Command failed: hciconfig hci0 reset
/bin/sh: hciconfig: Operation not permitted

1/20/2022, 4:48:42 PM - error - BluetoothService: Failed to connect to 63:0b:ea:ba:62:f8: timed out
1/20/2022, 4:48:42 PM - warn - BluetoothLowEnergyService: Failed to discover companion app ID due to error: timed out
1/20/2022, 4:48:42 PM - info - BluetoothLowEnergyService: Discovered nearby BLE peripheral 630beaba62f8 with ID 630beaba62f8 and RSSI -85
node:buffer:544
      if (list[i].length) {
                  ^

TypeError: Cannot read properties of undefined (reading 'length')
    at Function.concat (node:buffer:544:19)
    at Object.c1 (/usr/local/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/hci-socket/crypto.js:8:21)
    at Smp.handlePairingResponse (/usr/local/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/hci-socket/smp.js:84:12)
    at Smp.onAclStreamData (/usr/local/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/hci-socket/smp.js:55:10)
    at AclStream.emit (node:events:402:35)
    at AclStream.push (/usr/local/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/hci-socket/acl-stream.js:33:10)
    at NobleBindings.onAclDataPkt (/usr/local/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/hci-socket/bindings.js:319:15)
    at Hci.emit (node:events:390:28)
    at Hci.onSocketData (/usr/local/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/hci-socket/hci.js:641:14)
    at BluetoothHciSocket.emit (node:events:390:28)
```

**Relevant configuration**
**docker-compose.yml**
```
version: '3.8'
services:
  room-assistant:
    container_name: roomassistant
    image: mkerix/room-assistant
    network_mode: host
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /home/pi/HomeAssistantConfiguration/roomassistant/:/room-assistant/
```
**local.yaml**
```
global:
  instanceName: 'Office'
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.220:1883'
bluetoothLowEnergy:
  timeout: 60
  allowlist:
    - '30FFF053-FDFF-4BFF-B928-CBA11DC3EA45'
    - 'EB1717DD-C2F8-40A0-8B3A-D7644E2C3C0D'
  tagOverrides:
    30FFF053-FDFF-4BFF-B928-CBA11DC3EA45:
      name: iPhone1
    EB1717DD-C2F8-40A0-8B3A-D7644E2C3C0D:
      name: iPhone 2
```

**Expected behavior**
Not to crash

**Environment**
 - room-assistant version: 2.19.1
 - installation type: Docker
 - hardware: Raspberry Pi Zero W, Raspberry Pi 3B
 - OS: Raspbian (both Bullseye and Buster)
