### ISSUE TITLE
Unable to detect devices on Rasperrypi Zero 2 W

### ISSUE THREAD

**Issue by infinitejest** [mKeRix/room-assistant#1049]
I set up RA as per the instructions. RA is able to detect the raspberryPI2W. But it is not able to detect the specific devices we want to detect. 

**To reproduce**
Run room assistant on Rasspberrypi Zero 2 W. HA mqtt broker is only able to see that the RA is running but is not able to detect specific devices. 

**Relevant logs**
```
30/01/2022, 21:57:07 - debug - HomeAssistantService: Sending new attributes {"nodes":["garage-ra"]} for room-assistant-garage-ra-status-cluster-size
30/01/2022, 21:57:07 - debug - HomeAssistantService: Sending new attributes {"quorumReached":true} for room-assistant-garage-ra-status-cluster-leader
30/01/2022, 21:57:07 - debug - HomeAssistantService: Sending new state true for room-assistant-garage-ra-bluetooth-classic-inquiries-switch
30/01/2022, 21:57:17 - debug - BluetoothService: Locking adapter 0
30/01/2022, 21:57:17 - debug - BluetoothService: Querying for RSSI of  XX:XX:XX:XX:XX:XX using hcitool
30/01/2022, 21:57:17 - error - undefined: Inquiring RSSI via BT Classic failed: Command failed: hcitool -i hci0 cc "XX:XX:XX:XX:XX:XX" && hcitool -i hci0 rssi "XX:XX:XX:XX:XX:XX"
Invalid device: Network is down

30/01/2022, 21:57:17 - debug - BluetoothService: Unlocking adapter 0
30/01/2022, 21:57:27 - debug - BluetoothService: Locking adapter 0
30/01/2022, 21:57:27 - debug - BluetoothService: Querying for RSSI of XX:XX:XX:XX:XX:XX using hcitool
30/01/2022, 21:57:27 - error - undefined: Inquiring RSSI via BT Classic failed: Command failed: hcitool -i hci0 cc "XX:XX:XX:XX:XX:XX" && hcitool -i hci0 rssi "XX:XX:XX:XX:XX:XX"
Invalid device: Network is down
'''
30/01/2022, 21:57:27 - debug - BluetoothService: Unlocking adapter 0
30/01/2022, 21:57:30 - debug - HomeAssistantService: Marking instance as online
30/01/2022, 21:57:30 - debug - HomeAssistantService: Marking room-assistant-garage-ra-status-cluster-size as online
30/01/2022, 21:57:30 - debug - HomeAssistantService: Marking room-assistant-garage-ra-status-cluster-leader as online
30/01/2022, 21:57:30 - debug - HomeAssistantService: Marking room-assistant-garage-ra-bluetooth-classic-inquiries-switch as online
30/01/2022, 21:57:37 - debug - BluetoothService: Locking adapter 0
30/01/2022, 21:57:37 - debug - BluetoothService: Querying for RSSI of XX:XX:XX:XX:XX:XX using hcitool
30/01/2022, 21:57:37 - error - undefined: Inquiring RSSI via BT Classic failed: Command failed: hcitool -i hci0 cc "XX:XX:XX:XX:XX:XX" && hcitool -i hci0 rssi "XX:XX:XX:XX:XX:XX"
Invalid device: Network is down

30/01/2022, 21:57:37 - debug - BluetoothService: Unlocking adapter 0

```

**Relevant configuration**

```
global:
  instanceName: "garage_RA"
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://local_IP_address:1883'
  mqttOptions:
    username: user
    password: password
bluetoothClassic:
  minRssi: -20
  hciDeviceId: 0
  addresses:
    - XX:XX:XX:XX:XX:XX': #android Phone
    - 'ZZ:ZZ:ZZ:ZZ:ZZ:ZZ' #iphone phone
  entityOverrides:
    'XX:XX:XX:XX:XX:XX':
      id: android_phone
      name: Android Phone

```

**Expected behavior**
I want to detect device 1 and 2 as separate entities in RA so I cant know which device is in that room. 

**Environment**
 - room-assistant version: 2021.12.10
 -  - installation type:  Raspberry PI 4 B
 - hardware: Raspberry PI 4 B for home assistant; Raspberry PI zero 2W for Room assistant
 - OS: MAC OS

I tried to reboot and now not detecting any of the devices. It detected one when set up initially.
