### ISSUE TITLE
Unhandled promise rejection while starting

### ISSUE THREAD

**Issue by nikolaykasyanov** [mKeRix/room-assistant#107]
### Config

I'm running Room Assistant in Docker via the following docker-compose.yml:

```
...
  rass:
    image: mkerix/room-assistant:2.0.0
    network_mode: host
    volumes:
      - /var/run/dbus:/var/run/dbus
      - ./volumes/rass/config:/room-assistant/config
```

Room Assistant config:

```yml
global:
  instanceName: living-room
  integrations:
    - bluetoothClassic
    - homeAssistant
bluetoothClassic:
  minRssi: -20
  addresses:
    - 'redacted'
homeAssistant:
  mqttUrl: mqtt://127.0.0.1
  mqttOptions:
    username: redacted
    password: redacted
```

### Starcktrace

```
rass_1         | (node:1) UnhandledPromiseRejectionWarning: Error: dns service error: unknown
rass_1         |     at new Advertisement (/usr/local/lib/node_modules/room-assistant/node_modules/mdns/lib/advertisement.js:56:10)
rass_1         |     at Object.create [as createAdvertisement] (/usr/local/lib/node_modules/room-assistant/node_modules/mdns/lib/advertisement.js:64:10)
rass_1         |     at ClusterService.startBonjourDiscovery (/usr/local/lib/node_modules/room-assistant/dist/cluster/cluster.service.js:112:35)
rass_1         |     at ClusterService.onApplicationBootstrap (/usr/local/lib/node_modules/room-assistant/dist/cluster/cluster.service.js:67:22)
rass_1         |     at MapIterator.iteratee (/usr/local/lib/node_modules/room-assistant/node_modules/@nestjs/core/hooks/on-app-bootstrap.hook.js:21:43)
rass_1         |     at MapIterator.next (/usr/local/lib/node_modules/room-assistant/node_modules/iterare/lib/map.js:13:39)
rass_1         |     at IteratorWithOperators.next (/usr/local/lib/node_modules/room-assistant/node_modules/iterare/lib/iterate.js:21:28)
rass_1         |     at Function.from (<anonymous>)
rass_1         |     at IteratorWithOperators.toArray (/usr/local/lib/node_modules/room-assistant/node_modules/iterare/lib/iterate.js:180:22)
rass_1         |     at callOperator (/usr/local/lib/node_modules/room-assistant/node_modules/@nestjs/core/hooks/on-app-bootstrap.hook.js:22:10)
```
