### ISSUE TITLE
Apple iPhone not found

### ISSUE THREAD

**Issue by poudenes** [mKeRix/room-assistant#109]
Hi All,

I have everything work. See many BLE devices discovered. But my iPhone is missing.
When I scan for devices on my work phone (samsung) then I see my iPhone in the list.

Can someone tell me what to do?

40:9c:28:XX:XX:XX Must be my iPhone and tried to add this in white list

```
global:
  instanceName: room-assistant
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://192.168.xxx.xxx:1883'
  mqttOptions:
    username: USERNAME
    password: PASSWORD
bluetoothLowEnergy:
  whitelist:
    - '40:9c:28:XX:XX:XX'
    - '68:fe:f7:XX:XX:XX'
  maxDistance: 15
  tagOverrides:
    '40:9c:28:XX:XX:XX':
      name: Peter BLE
```

```
[21:33:33] ERROR: Got unexpected response from the API: Service not enabled
[21:33:33] INFO: Starting room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
[Nest] 7   - 02/22/2020, 9:33:35 PM   [NestFactory] Starting Nest application...
[Nest] 7   - 02/22/2020, 9:33:35 PM   [InstanceLoader] AppModule dependencies initialized +620ms
[Nest] 7   - 02/22/2020, 9:33:35 PM   [InstanceLoader] ConfigModule dependencies initialized +2ms
[Nest] 7   - 02/22/2020, 9:33:35 PM   [InstanceLoader] NestEmitterModule dependencies initialized +2ms
[Nest] 7   - 02/22/2020, 9:33:35 PM   [InstanceLoader] IntegrationsModule dependencies initialized +1ms
[Nest] 7   - 02/22/2020, 9:33:36 PM   [InstanceLoader] DiscoveryModule dependencies initialized +22ms
[Nest] 7   - 02/22/2020, 9:33:36 PM   [InstanceLoader] HomeAssistantModule dependencies initialized +2ms
[Nest] 7   - 02/22/2020, 9:33:36 PM   [InstanceLoader] ClusterModule dependencies initialized +2ms
[Nest] 7   - 02/22/2020, 9:33:36 PM   [InstanceLoader] ScheduleModule dependencies initialized +2ms
[Nest] 7   - 02/22/2020, 9:33:36 PM   [InstanceLoader] BluetoothLowEnergyModule dependencies initialized +3ms
[Nest] 7   - 02/22/2020, 9:33:36 PM   [InstanceLoader] EntitiesModule dependencies initialized +1ms
[Nest] 7   - 02/22/2020, 9:33:36 PM   [RoutesResolver] EntitiesController {/entities}: +23ms
[Nest] 7   - 02/22/2020, 9:33:36 PM   [RouterExplorer] Mapped {/, GET} route +11ms
[Nest] 7   - 02/22/2020, 9:33:36 PM   [HomeAssistantService] Successfully connected to MQTT broker at mqtt://192.168.100.26:1883
[Nest] 7   - 02/22/2020, 9:33:36 PM   [ClusterService] Starting mDNS advertisements and discovery
[Nest] 7   - 02/22/2020, 9:33:36 PM   [NestApplication] Nest application successfully started +3ms
[Nest] 7   - 02/22/2020, 9:33:36 PM   [BluetoothLowEnergyService] Discovered new BLE peripheral 35268a63f395 with ID 35268a63f395 and RSSI -68
[Nest] 7   - 02/22/2020, 9:33:36 PM   [BluetoothLowEnergyService] Discovered new BLE peripheral 5527cef4bdac with ID 5527cef4bdac and RSSI -64
[Nest] 7   - 02/22/2020, 9:33:36 PM   [BluetoothLowEnergyService] Discovered new BLE peripheral Nanoleaf Remote 9089 with ID f898b506739a and RSSI -54
[Nest] 7   - 02/22/2020, 9:33:36 PM   [BluetoothLowEnergyService] Discovered new BLE peripheral c869cd2b8afd with ID c869cd2b8afd and RSSI -68
[Nest] 7   - 02/22/2020, 9:33:37 PM   [BluetoothLowEnergyService] Discovered new BLE peripheral 5c8cd4639f97 with ID 5c8cd4639f97 and RSSI -73
[Nest] 7   - 02/22/2020, 9:33:37 PM   [BluetoothLowEnergyService] Discovered new BLE peripheral N0AX2 with ID df507b84bf13 and RSSI -71
[Nest] 7   - 02/22/2020, 9:33:38 PM   [ClusterService] room-assistant has been elected as leader
[Nest] 7   - 02/22/2020, 9:33:38 PM   [EntitiesService] Refreshing entity states
[Nest] 7   - 02/22/2020, 9:33:38 PM   [BluetoothLowEnergyService] Discovered new BLE peripheral N0AQM with ID fcf0f88fe9ea and RSSI -66
[Nest] 7   - 02/22/2020, 9:34:23 PM   [BluetoothLowEnergyService] Discovered new BLE peripheral N0BDH with ID d12d9ea7ff1b and RSSI -75
[Nest] 7   - 02/22/2020, 9:34:57 PM   [BluetoothLowEnergyService] Discovered new BLE peripheral 1c1ac0928454 with ID 1c1ac0928454 and RSSI -78
```

**Comment by mKeRix** [comment]
iPhones do not really broadcast on BLE - and if they do, they randomize their MAC addresses. For tracking iPhones you will need to make use of the [Bluetooth Classic integration](https://www.room-assistant.io/integrations/bluetooth-classic). So your config would be:

```yaml
global:
  instanceName: room-assistant
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.xxx.xxx:1883'
  mqttOptions:
    username: USERNAME
    password: PASSWORD
bluetoothClassic:
  addresses:
    - '40:9c:28:XX:XX:XX'
    - '68:fe:f7:XX:XX:XX'
```
