### ISSUE TITLE
Room-assistant 2.0 add-on doesn't start on Hassio (Raspberry 3B+)

### ISSUE THREAD

**Issue by vash3d** [mKeRix/room-assistant#111]
I've tried uninstalling and reinstalling several times.
The add-on just doesn't start.
No error in the logs, neither add-on logs nor Homeassistant logs.
Maybe there is something wrong with my config?
```
global:
  instanceName: Livingroom
  integrations:
    - homeAssistant
    - bluetoothClassic
cluster:
  port: 6425
  peerAddresses:
    - 192.168.1.155
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.152:1883'
  mqttOptions:
    username: user
    password: password
bluetoothClassic:
  addresses:
    - '18:81:0c:46:35:a0'
    - 'a8:5c:2e:83:99:1b'
```
I even thought of a bluetooth issue, but I believe in Hassio bluetooth is activated automatically.
