### ISSUE TITLE
BLE showing not home state/away

### ISSUE THREAD

**Issue by infinitejest** [mKeRix/room-assistant#1114]
I have a google Pixel 5 that I am tyring to get connected to Home assistant and Room assistant. I am using the Home assistant android app to transmit the BLE signal. Bluetooth classic work well. However, it has some delay so I wanted to try BLE. The problem I am encoutering is that when Room assistant detects the Pixel 5 BLE signal it is sending to Home assistant not_home status for room presence sensor. Not sure how to change that to make the phone sens home signal instead. 

Any ideas welcome.

**Comment by st3v3nFr** [comment]
Hi there, it's sending this 'not home' because : 

- RAPI AND MQTT + HA are working fine !
- BUT he can't find your phone, please unsure you did this in config file (local.yml) :

```
 bluetoothLowEnergy:
  timeout: 60
  allowlist:
  - UUID OF YOUR PHONE
  whitelist:
  - UUID OF YOUR PHONE
```

PS1: NOTE that UUID need to be unquote
PS2: Note that the HOME ASSISTANT app will give you the UUID with the form XXXXXXXXXXXXXX-YYY-Z, the UUID is the XXX part
