### ISSUE TITLE
2.10 bluetooth classic devices being shown as undefined

### ISSUE THREAD

**Issue by gmalbert** [mKeRix/room-assistant#117]
**Describe the bug**
After upgrading to 2.10 today, the mqtt messages show up as: 

`room-assistant/sensor/bluetooth-classic-undefined/attributes`

In the previous release (including 2.01), the message showed the bluetooth mac ID of the device.
**To reproduce**
Steps required to reproduce the issue.
Post-upgrade and restart of the service.
**Relevant configuration**
Paste the relevant parts of your configuration below.

```
global:
  instanceName: Garage
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: mqtt://192.168.1.38:1883
 # mqttOptions:
 #   username: ''
 #   password:
bluetoothClassic:
  addresses:
    - WATCH
    - PHONE
```

```yaml
```

**Expected behavior**
I expect to see the bluetooth mac address as it had been in previous versions.
**Environment**
 - room-assistant version: [e.g. 2.0.0]
 - installation type: [e.g. NodeJS, Docker, Hass.io]
 - hardware: [e.g. Raspberry Pi Zero W, NUC]
 - OS: [e.g. Linux, Windows, macOS]
Raspberry PI Zero W using NodeJS
**Additional context**
