### ISSUE TITLE
No MQTT Connection Attempt After Adding Cluster

### ISSUE THREAD

**Issue by Blink515** [mKeRix/room-assistant#126]
**Describe the bug**
After adding cluster configuration information to the config file room-assistant no longer tries to connect to MQTT

**To reproduce**
Add cluster to config file with relevant peer addresses

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```[Nest] 694   - 03/03/2020, 7:51:11 PM   [IntegrationsModule] Loading integrations: none
[Nest] 694   - 03/03/2020, 7:51:13 PM   [NestFactory] Starting Nest application... +2384ms
[Nest] 694   - 03/03/2020, 7:51:14 PM   [InstanceLoader] AppModule dependencies initialized +562ms
[Nest] 694   - 03/03/2020, 7:51:14 PM   [InstanceLoader] ConfigModule dependencies initialized +16ms
[Nest] 694   - 03/03/2020, 7:51:14 PM   [InstanceLoader] NestEmitterModule dependencies initialized +15ms
[Nest] 694   - 03/03/2020, 7:51:14 PM   [InstanceLoader] IntegrationsModule dependencies initialized +15ms
[Nest] 694   - 03/03/2020, 7:51:14 PM   [InstanceLoader] DiscoveryModule dependencies initialized +98ms
[Nest] 694   - 03/03/2020, 7:51:14 PM   [InstanceLoader] ClusterModule dependencies initialized +17ms
[Nest] 694   - 03/03/2020, 7:51:14 PM   [InstanceLoader] ScheduleModule dependencies initialized +19ms
[Nest] 694   - 03/03/2020, 7:51:14 PM   [InstanceLoader] EntitiesModule dependencies initialized +20ms
[Nest] 694   - 03/03/2020, 7:51:14 PM   [RoutesResolver] EntitiesController {/entities}: +133ms
[Nest] 694   - 03/03/2020, 7:51:14 PM   [RouterExplorer] Mapped {/, GET} route +77ms
[Nest] 694   - 03/03/2020, 7:51:15 PM   [ConfigService] Loading configuration from /opt/nodejs/lib/node_modules/room-assistant/dist/config/definitions/default.js
[Nest] 694   - 03/03/2020, 7:51:15 PM   [ConfigService] No configuration found in /home/pi/config
[Nest] 694   - 03/03/2020, 7:51:15 PM   [ClusterService] Starting mDNS advertisements and discovery
[Nest] 694   - 03/03/2020, 7:51:15 PM   [NestApplication] Nest application successfully started +30ms
[Nest] 694   - 03/03/2020, 7:51:15 PM   [ClusterService] Added 192.168.1.212:6425 to the cluster with id ra-office
[Nest] 694   - 03/03/2020, 7:51:23 PM   [ClusterService] getaddrinfo -3008 +8088ms
[Nest] 694   - 03/03/2020, 7:51:23 PM   [ClusterService] getaddrinfo -3008 +25ms

```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```
global:
  instanceName: bedroom
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
cluster:
  networkInterface: wlan0
  quorum: 2
  peerAddresses:
    - 192.168.1.212:6425
    - 192.168.1.221:6425
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.67:1883'
  mqttOptions:
    username: ######
    password: ######
bluetoothLowEnergy:
  whitelist:
    - c53e5f59c30b
    - f0-35-3a-ef-06-84
  maxDistance: 4
  channel: 'room_presence'
  tagOverrides:
    c53e5f59c30b:
      name: 'Charger Keys'
```

**Expected behavior**
Room assistant should pick up the other peers and connect to MQTT.

**Environment**
 - room-assistant version:2.1.0
 - installation type: NodeJS
 - hardware: Pi Zero W
 - OS: Linux
