### ISSUE TITLE
Compatibility with other HomeAutomation Systems

### ISSUE THREAD

**Issue by nukleuz80** [mKeRix/room-assistant#1267]
Hi there,

i tried using room-assistant on RPI4.
Installation and configuration are ok.

Now, it´s running as deamon very well.
I use the ios app and put the key in the config...

The MQTT messages were sent to ioBroker (MQTT-Server),
but the only MQTT payloads i get is:

![grafik](https://user-images.githubusercontent.com/43496030/190988985-7b0ccea0-52fc-4110-847a-868342b5279b.png)

```
{
  "entity": {
    "attributes": {
      "quorumReached": true
    },
    "id": "status-cluster-leader",
    "name": "raspberrypi Cluster Leader",
    "distributed": false,
    "stateLocked": true,
    "state": "raspberrypi"
  },
  "diff": [
    {
      "path": "/state",
      "oldValue": "none",
      "newValue": "raspberrypi"
    }
  ],
  "hasAuthority": true
}
```

So i think there are missing values like: RSSI, Distance etc...

Could you please tell me, that room-assistant is running with every MQTT Broker?

Here is my config:
```
global:
  instanceName: Wohnzimmer
  integrations:
    - mqtt
    - bluetoothLowEnergy
mqtt:
  mqttUrl: mqtt://192.168.0.56:1888
  retain: false

bluetoothLowEnergy:
  timeout: 60
  allowlist:
  - '292A08C9-A0B2-456C-A12B-66042BC418AA'
```

Can anyone see my issue?

Thank you!
