### ISSUE TITLE
Why do I have a bluetooth device called "undefined" ?

### ISSUE THREAD

**Issue by B-Hartley** [mKeRix/room-assistant#136]
**Describe the bug**
A few times when runnings, I seem to end up with a bluetooth device called "undefined"
Sometimes I see it in the MQTT data.
Sometimes I see it in the logs.

```
[Nest] 30489   - 03/09/2020, 8:53:52 PM   [BluetoothClassicService] Querying for RSSI of undefined using hcitool
[Nest] 30489   - 03/09/2020, 8:53:57 PM   [BluetoothClassicService] Command failed: hcitool -i hci0 cc "undefined" && hcitool -i hci0 rssi "undefined"
Can't create connection: Input/output error
Get connection info failed: No such file or directory
```

config........

```
global:
  instanceName: lounge
  integrations:
    - bluetoothClassic
    - homeAssistant
cluster:
  autoDiscovery: false
  quorum: 4
  weight: 4
  networkInterface: wlan0
  port: 6425
  peerAddresses:
    - 192.168.xx.xxx:6425
    - 192.168.xx.xxx:6425
    - 192.168.xx.xxx:6425
    - 192.168.xx.xxx:6425
    - 192.168.xx.xxx:6425    
    - 192.168.xx.xxx:6425
bluetoothClassic:
  minRssi: -20
  addresses:
    - 'CC:D2:81:xx:xx:xx'
    - '8C:86:1E:xx:xx:xx'
    - '2C:33:61:xx:xx:xx'
    - '2C:33:61:xx:xx:xx'
    - '18:55:E3:xx:xx:xx'
homeAssistant:
  mqttUrl: mqtt://192.168.xx.xxx:1883
  mqttOptions:
    username: xxxxxx
    password: xxxxxx
```

**Environment**
 - room-assistant version: 2.1.1
 - installation type: NodeJS
 - hardware: Raspberry Pi Zero W
