### ISSUE TITLE
What do i add to config for two devices

### ISSUE THREAD

**Issue by hwikene** [mKeRix/room-assistant#138]
**Describe the bug**
I have Room Assistant installed on on RPI3 and a Addon on Home Assistant.
What config do i add to the devices? Mine are like this and what am i missing?:

**Relevant configuration**
Paste the relevant parts of your configuration below.

```
This is what i have on my addon in Home Assistant
global:
  instanceName: stue
  integrations:
    - homeAssistant
    - bluetoothClassic
bluetoothClassic:
  addresses:
    - '40:9C:XX:XX:XX:XX'
homeAssistant:
  mqttUrl: 'mqtt://192.168.XX.XX:1883'
  mqttOptions:
    username: user
    password: pass

And this is what i have on my RPI3
global:
  integrations:
    - bluetoothClassic
bluetoothClassic:
  minRssi: -20
  addresses:
    - 40:9C:XX:XX:XX:XX
```

**Expected behavior**

**Environment**
 - room-assistant version: 2.1.1
 - installation type: Hass.io
 - hardware: Raspberry Pi 3, NUC
 - OS: Linux

**Additional context**
I only get one of the sensors that track bluetooth. I cant figure out to get both.
