### ISSUE TITLE
Restarting home assistant with room-assistant running causes a failed restart

### ISSUE THREAD

**Issue by THATDONFC** [mKeRix/room-assistant#143]
**Describe the bug**
When room-assistant is running on home assistant, and the home assistant server is restarted, the restart hangs and I am forced to reboot the rpi4 that is hosting home assistant. 

**To reproduce**
Start room-assistant add-on. Restart home assistant from configuration -> server controls -> restart

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

I don't have any logs that would assist here. I don't see any errors because home assistant never starts back up.

**Relevant configuration**
Paste the relevant parts of your configuration below.

```yaml
global:
  instanceName: homeassistant
  integrations:
    - homeAssistant
    - bluetoothClassic
  homeAssistant:
    mqttUrl: 'mqtt://core-mosquitto:1883'
    mqttOptions:
      username: user
      password: pass
      rejectUnauthorized: false
  bluetoothClassic:
    addresses:
      - '6C:85:1E:AA:85:93'
      - '03:F4:A3:37:F1:26'
```
**Expected behavior**
Being able to restart home assistant without stopping room-assistant first.

**Environment**
 - room-assistant version: 2.1.1
 - installation type: hassio
 - hardware: raspberry pi 4 4gb
 - OS: rasbian buster lite

**Additional context**
I thought this was a fluke initially. But now I have been able to reproduce it without a miss. If I stop room-assistant before restarting home assistant, there is no issue. If room-assistant is running and I restart home-assistant, the restart hangs and never completes. I must then reboot or manually restart the home-assistant docker container. This is a big issue for me because every time this happens, I have re-integrate smart things because the refresh token becomes out of sync due to the forced restart.
