### ISSUE TITLE
Room Assistant hanging

### ISSUE THREAD

**Issue by KTibow** [mKeRix/room-assistant#1436]
**Describe the bug**
Room Assistant randomly tries to connect to devices and hangs. I don't even have bluetooth classic turned on.

**To reproduce**
Set up the config listed below

**Relevant logs**

```text
04/06/2023, 10:05:57 - info - BluetoothLowEnergyService: Attempting app discovery for tag censored-100-1
04/06/2023, 10:05:57 - debug - BluetoothLowEnergyService: Tag censored-100-1 seems to broadcast the app with manufacturer data 4c000215c04d90f201c443b7be06086b4914872b00640001c5
04/06/2023, 10:05:57 - debug - BluetoothService: Locking adapter 0
04/06/2023, 10:05:57 - debug - BluetoothService: Stopping scanning for BLE peripherals on adapter 0
04/06/2023, 10:05:57 - debug - BluetoothService: Connecting to BLE device at address ce:ns:or:ed:ce:ns
^C^C04/06/2023, 10:06:38 - debug - HomeAssistantService: Marking instance as online
04/06/2023, 10:06:38 - debug - HomeAssistantService: Marking room-assistant-room-assistant-1-status-cluster-size as online
04/06/2023, 10:06:38 - debug - HomeAssistantService: Marking room-assistant-room-assistant-1-status-cluster-leader as online
04/06/2023, 10:06:38 - info - BluetoothService: Detected unusually long lock on Bluetooth adapter 0, force unlocking
```

**Relevant configuration**

```yaml
global:
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: mqtt://homeassistant.local:1883
  mqttOptions:
    username: mqtt
    password: censored
bluetoothLowEnergy:
  allowlist:
    - censored-100-1
  instanceBeaconEnabled: false
  tagOverrides:
    censored-100-1:
      name: OnePlus 7
```

**Expected behavior**

For it to not hang

**Environment**
 - room-assistant version: 2.20.0
 - installation type: NodeJS
 - hardware: Raspberry Pi 3B
 - OS: Linux

**Additional context**
