### ISSUE TITLE
Following the docs for install on Pi results in crashed Pi's after a few hours

### ISSUE THREAD

**Issue by MTrab** [mKeRix/room-assistant#146]
**Describe the bug**
I have installed a few Raspberry Pi's (3B+ and Zero W) and they are randomly crashing after a few hours, rendering them inaccessible via SSH and not reporting states.

**To reproduce**
Install following the docs

**Relevant configuration**
```
global:
  instanceName: bryggers
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://ip:1883'
  mqttOptions:
    username: user
    password: pass
bluetoothClassic:
  addresses:
    - mac_1
    - mac_2
    - mac_3
```

**Environment**
 - room-assistant version: ? Latest I guess as I installed yesterday and today
 - installation type: NodeJS
 - hardware: RPi 3B+ and RPi Zero W
 - OS: Raspbian Buster Lite
