### ISSUE TITLE
How to use the inquiries switch?

### ISSUE THREAD

**Issue by pointlevel** [mKeRix/room-assistant#151]
Hi!

I cant find anything in the docs about how to disable/enable the inquiries switch when using BluetoothClassic mode. I can see the switch presented by mqtt, but dont know how to manage it?

- entrance-bluetooth-classic-inquiries-switch
    - status = online
    - state = true
    - attributes = {}

**Comment by mKeRix** [comment]
When using the Home Assistant integration you will just see a switch entity being created in Home Assistant. Appears automatically if you have auto discovery enabled for MQTT in Home Assistant. Then you can just use the switch with the `switch.turn_on`/`switch.turn_off` services or from the Lovelace UI if you add it.

**Comment by pointlevel** [comment]
Great, thanks. But if im not want to turn on auto discovery for mqtt? How can i make my own mqtt-switch?
`
switch:
   - platform: mqtt
      command_topic: "?"
`

**Comment by mKeRix** [comment]
If you subscribe to `home assistant/switch/+/+/config` you will find the config being posted to that topic as JSON. You can use that as the MQTT switch config, just leave out the `device` and `unique_id` sections. In your case it would probably be something like:

```yaml
switch:
   - platform: mqtt
      payload_available: online
      payload_not_available: offline
      name: entrance Bluetooth Inquiries
      state_topic: room-assistant/switch/entrance-bluetooth-classic-inquiries-switch/state
      json_attributes_topic: room-assistant/switch/entrance-bluetooth-classic-inquiries-switch/attributes
      availability_topic: room-assistant/switch/entrance-bluetooth-classic-inquiries-switch/status
      payload_on: on
      payload_off: off
      state_on: true
      state_off: false
      command_topic: room-assistant/switch/entrance-bluetooth-classic-inquiries-switch/command
      icon: mdi:bluetooth-audio
```
