### ISSUE TITLE
Resetting hci0 in Docker container is causing zombie processes

### ISSUE THREAD

**Issue by iicky** [mKeRix/room-assistant#157]
**Describe the bug**
I am getting a lot of zombie processes popping up as a result of my room-assistant Docker container. It appears as though whenever the BluetoothClassicService query takes too long and `hci0` is reset, it becomes a zombie process. This results in tons of zombie processes over time until I restart the room-assistant container, at which point they all are destroyed.

This issue is specifically impacting my deployment on my Intel NUC and is not occurring on my Raspberry Pi deploys.

**To reproduce**
Deploy using the docker-compose file and config below.

**Relevant logs**

Room Assistant logs.
```
docker logs -f room-assistant

[Nest] 1   - 03/22/2020, 11:44:54 AM   [BluetoothClassicService] Query of xx:xx:xx:xx:xx:xx took too long, resetting hci0
[Nest] 1   - 03/22/2020, 11:46:24 AM   [BluetoothClassicService] Query of xx:xx:xx:xx:xx:xx took too long, resetting hci0
[Nest] 1   - 03/22/2020, 11:46:35 AM   [BluetoothClassicService] Query of xx:xx:xx:xx:xx:xx took too long, resetting hci0
[Nest] 1   - 03/22/2020, 11:46:36 AM   [BluetoothClassicService] Query of xx:xx:xx:xx:xx:xx took too long, resetting hci0
[Nest] 1   - 03/22/2020, 11:55:06 AM   [BluetoothClassicService] Query of xx:xx:xx:xx:xx:xx took too long, resetting hci0
```

Zombie processes.
```
user@core:~$ ps auxwww | grep ' Z '
4 Z root      5859 28012  0  80   0 -     0 -      13:44 ?        00:00:00 [hcitool] <defunct>
4 Z root      7486 28012  0  80   0 -     0 -      13:46 ?        00:00:00 [hcitool] <defunct>
4 Z root      7672 28012  0  80   0 -     0 -      13:46 ?        00:00:00 [hcitool] <defunct>
4 Z root      7713 28012  0  80   0 -     0 -      13:46 ?        00:00:00 [hcitool] <defunct>
```

**Relevant configuration**

Docker Compose `docker-compose.yaml`
```
version: "3.1"
services:

  # Room Assistant-----------------------------------
  room-assistant:
    container_name: room-assistant
    image: mkerix/room-assistant
    network_mode: host
    ports:
      - 6425:6425
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/dbus:/var/run/dbus
      - ./room-assistant/config:/room-assistant/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
```

Room Assistant config `local.yml`
```
global:
  instanceName: office
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://XXX.XXX.XXX.XXX:1883'
  mqttOptions:
    username: <username>
    password: <password>
cluster:
  networkInterface: eno1
  port: 6425
  peerAddresses:
    - <raspberry_pi_zero_1>:6425 
    - <raspberry_pi_zero_1>:6425
bluetoothClassic:
  addresses:
    - '<mac_address_1>'
    - '<mac_address_2>' 
```

**Expected behavior**
I expect the zombie processes to not appear.

**Environment**
 - room-assistant version: 2.1.1
 - installation type: Docker
 - hardware: Intel NUC8i5BEK1
 - OS: Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-91-generic x86_64)

**Additional context**

Zombie processes are not appearing on both Raspberry Pis that have room-assistant installed.

**Comment by mKeRix** [comment]
Thanks for the bug report - I'll try to reproduce it with my Ubuntu NUC at home. In theory the processes should be hard killed by NodeJS, that was also what I was observing when I tried it. I didn't try it with this specific setup though, so maybe we need some small adaptions in the Dockerfile.

**Comment by iicky** [comment]
Awesome, thanks! Let me know if you need any additional info.

**Comment by mwasowski** [comment]
I have the same issue.
**Docker logs**
```[Nest] 1   - 04/03/2020, 5:00:47 PM   [BluetoothClassicService] Query of XX:XX:XX:XX:XX:XX took too long, resetting hci0
[Nest] 1   - 04/03/2020, 5:00:53 PM   [BluetoothClassicService] Query of XX:XX:XX:XX:XX:XX took too long, resetting hci0
[Nest] 1   - 04/03/2020, 5:01:23 PM   [BluetoothClassicService] Query of XX:XX:XX:XX:XX:XX took too long, resetting hci0
[Nest] 1   - 04/03/2020, 5:01:29 PM   [BluetoothClassicService] Query of XX:XX:XX:XX:XX:XX took too long, resetting hci0
[Nest] 1   - 04/03/2020, 5:01:35 PM   [BluetoothClassicService] Query of XX:XX:XX:XX:XX:XX took too long, resetting hci0
```
**Zombie processes**
```
root      3779  0.0  0.0      0     0 ?        Z    19:00   0:00 [hcitool] <defunct>
root      3782  0.0  0.0      0     0 ?        Z    19:00   0:00 [hcitool] <defunct>
root      3799  0.0  0.0      0     0 ?        Z    19:01   0:00 [hcitool] <defunct>
root      3802  0.0  0.0      0     0 ?        Z    19:01   0:00 [hcitool] <defunct>
root      3805  0.0  0.0      0     0 ?        Z    19:01   0:00 [hcitool] <defunct>
```
**Environment**
```
room-assistant version: 2.2.0
installation type: Docker
hardware: ProxmoxVE
OS: Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
```
**Config**
Docker
```
version: '3'
services:
  room-assistant:
    container_name: room-assistant
    image: mkerix/room-assistant
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /etc/room-assistant/config:/room-assistant/config
```
Room asistant
```
global:
  instanceName: Home
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://XXX.XXX.XXX.XXX:1883'
  mqttOptions:
    username: <user>
    password: <pass>
bluetoothClassic:
  addresses:
    - 'XX:XX:XX:XX:XX:XX'
```
