### ISSUE TITLE
only getting not_home

### ISSUE THREAD

**Issue by rrosson** [mKeRix/room-assistant#158]
**Describe the bug**
Running three 'pi zero w' nodes in a cluster using your guide for setup and since initial detection of my Apple Watch it shows 'not_home'.

**To reproduce**
Steps required to reproduce the issue.

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```text
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```
global:
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.XX.XXX:1883'
  mqttOptions:
    username: myuser
    password: mysecret
bluetoothClassic:
#  minRssi: -20
  addresses:
    - 'C4:84:66:XX:XX:XX'	# My Apple Watch
#    - 'C4:84:66:YY:YY:YY'	# Wife's Apple Watch
cluster:
  networkInterface: wlan0
  port: 6425
  peerAddresses:
    - 192.168.XX.XXX:6425   # Location 1
    - 192.168.XX.XXX:6425   # Location 2
    - 192.168.XX.XXX:6425   # Location 3
```

**Expected behavior**
Expecting to see mqtt messages using 'mqtt lens' to show my Apple Watch leave and arrive but am only seeing status of each node in the cluster.

**Environment**
 - room-assistant version: latest release as of 3/24/202
 - installation type: NodeJs
 - hardware: Raspberry Pi Zero W
 - OS: Linux

**Additional context**
Each node deployed is roughly over a 50' apart from each other at a minimum with multiple walls between them.
