### ISSUE TITLE
Device detection that is not near the room-assistant device

### ISSUE THREAD

**Issue by petarvucetin** [mKeRix/room-assistant#162]
**Describe the bug**
Not sure this is a bug or it should work this way. I have my phone right next to RPI0W and Distance (I am guessing RSSI) is showing - values that are in range of -0.9 to -12. My other registered device is in another room approximately 10 feet away (through the wall) and it is showing values of .1 to 12.5. 

I have set RSSI value to -80 and the other device is still getting detected.

**To reproduce**
Have two devices within 10 feet of each other

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```text
```

**Relevant configuration**

```yaml

global:
  instanceName: office
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.1:1883'
  mqttOptions:
    username: mqtt
    password: ******
bluetoothClassic:
  minRssi: -80
  interval: 3
  timeoutCycles: 2
  addresses:
    - 'E4:....'
    - '54:....'
```

**Expected behavior**
The other device should not have been detected

**Environment**
 - room-assistant version: 2.2.0
 - installation type: NodeJS,
 - hardware: Raspberry Pi Zero W
 - OS: Linux,

**Additional context**

![image](https://user-images.githubusercontent.com/179653/77882085-1d51c800-7215-11ea-94ad-d201c03e5dc6.png)
