### ISSUE TITLE
BTLE devices stay at 'Unknown' in Home Assistant

### ISSUE THREAD

**Issue by SylvainGa** [mKeRix/room-assistant#175]
I'm trying to get a Tile working in Room Assistant. This is what I have in my config file

```
global:
  instanceName: Salon
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
  cluster:
    autoDiscovery: false
    networkInterface: wlan0
    port: 6425
    weight: 100
    quorum: 2
    peerAddresses:
      - 192.168.2.84:6425
      - 192.168.2.119:6425
homeAssistant:
  mqttUrl: 'mqtt://192.168.2.84:1883'
  mqttOptions:
    username: xxx
    password: xxx
bluetoothLowEnergy:
  whitelist:
    - c2a802783678
```

The other two devices in the cluster are not configured for BTLE, just classic BT.

This is the log in verbose mode:

```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
4/19/2020, 5:23:37 PM - info - IntegrationsModule: Loading integrations: home-assistant, bluetooth-low-energy
4/19/2020, 5:23:40 PM - info - NestFactory: Starting Nest application...
4/19/2020, 5:23:43 PM - info - InstanceLoader: AppModule dependencies initialized
4/19/2020, 5:23:43 PM - info - InstanceLoader: ConfigModule dependencies initialized
4/19/2020, 5:23:43 PM - info - InstanceLoader: NestEmitterModule dependencies initialized
4/19/2020, 5:23:43 PM - info - InstanceLoader: IntegrationsModule dependencies initialized
4/19/2020, 5:23:43 PM - info - InstanceLoader: DiscoveryModule dependencies initialized
4/19/2020, 5:23:43 PM - info - InstanceLoader: HomeAssistantModule dependencies initialized
4/19/2020, 5:23:43 PM - info - InstanceLoader: ClusterModule dependencies initialized
4/19/2020, 5:23:43 PM - info - InstanceLoader: ScheduleModule dependencies initialized
4/19/2020, 5:23:43 PM - info - InstanceLoader: BluetoothLowEnergyModule dependencies initialized
4/19/2020, 5:23:43 PM - info - InstanceLoader: EntitiesModule dependencies initialized
4/19/2020, 5:23:43 PM - info - RoutesResolver: EntitiesController {/entities}:
4/19/2020, 5:23:43 PM - info - RouterExplorer: Mapped {/, GET} route
4/19/2020, 5:23:44 PM - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://192.168.2.84:1883
4/19/2020, 5:23:44 PM - info - ConfigService: Loading configuration from /opt/nodejs/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/local.yml
4/19/2020, 5:23:44 PM - info - ClusterService: Starting mDNS advertisements and discovery
4/19/2020, 5:23:45 PM - info - NestApplication: Nest application successfully started
4/19/2020, 5:23:45 PM - info - BluetoothLowEnergyService: Discovered new BLE peripheral 5e89b7e37f7f with ID 5e89b7e37f7f and RSSI -84
4/19/2020, 5:23:46 PM - info - BluetoothLowEnergyService: Discovered new BLE peripheral PR BT 04E4 with ID 001fff57a010 and RSSI -89
4/19/2020, 5:23:46 PM - info - BluetoothLowEnergyService: Discovered new BLE peripheral Tile with ID c2a802783678 and RSSI -52
4/19/2020, 5:23:46 PM - debug - EntitiesService: Adding new entity ble-c2a802783678
4/19/2020, 5:23:46 PM - debug - HomeAssistantService: Registering entity room-assistant-ble-c2a802783678 under homeassistant/sensor/room-assistant/ble-c2a802783678/config
```

So the Tile device is seen and added to Home Assistant, but within Home Assistant, all I ever get is 

```
Tile Room Presence          Unknown
19 minutes ago
```

This is running off a Raspberry Pi Zero W with an up to date Rasbian-Lite. If I use Classic BT instead, my phones are seen are showing properly in Home Assistant.

Not sure what I'm doing wrong but I can't get it to publish its state.
