### ISSUE TITLE
Stopping the docker container in Hass.io doesn't put sensors as unavailable

### ISSUE THREAD

**Issue by RomRider** [mKeRix/room-assistant#181]
**Describe the bug**
Shutting down the docker container (Hass.io) doesn't put monitored Classic Bluetooth devices as `unavailable` (maybe others too).
Note: I only have 1 instance.

**To reproduce**
1. Install the addon
2. Configure some classic BT devices
3. verify that they appear in HA's dev-state
4. stop the container

**Relevant logs**
N/A

**Relevant configuration**
Paste the relevant parts of your configuration below.

```yaml
global:
  instanceName: Office
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtts://xxxxxxxx'
  mqttOptions:
    username: xxxxxxxx
    password: xxxxxxxx
bluetoothClassic:
  hciDeviceId: 0
  minRssi: -20
  interval: 6
  addresses:
    - 'xx:xx:xx:xx:xx:xx'
```

**Expected behavior**
Putting sensors as unavailable when the last instance is down or when there where no updates for some time (ideally configurable). 

This would help secure the solution a bit, especially if the app crashes.

**Environment**
 - room-assistant version: [e.g. 2.0.0] 2.4.0
 - installation type: [e.g. NodeJS, Docker, Hass.io]: Hass.io
 - hardware: [e.g. Raspberry Pi Zero W, NUC]: NUC
 - OS: [e.g. Linux, Windows, macOS]: Linux

**Additional context**
