### ISSUE TITLE
Problem with MQTT topic / payload

### ISSUE THREAD

**Issue by BigDi** [mKeRix/room-assistant#185]
**Describe the bug**
I used the assistant to integrate it into io.broker. I setup the MQTT connection. But I got two topics while sending updates. 1) homeassistant 2) room-assistent
Under topic homeassistant is a JSON structure send. Under room-assistent I get the state and status.
Next issue is when I get a new update then I will always received a "not_home".

**Relevant logs**
`
```

2020-04-30 09:35:13
Topic: room-assistant/sensor/ble-0dac8737d59b/status
Qos: 0
Retained
online
2020-04-30 09:35:13
Topic: room-assistant/sensor/ble-29cfc0d8ab0d/state
Qos: 0
Retained
not_home
2020-04-30 09:35:13
Topic: room-assistant/sensor/ble-29cfc0d8ab0d/status
Qos: 0
Retained
online
2020-04-30 09:35:13
Topic: room-assistant/sensor/ble-1b8ab8940985/state
Qos: 0
Retained
not_home
2020-04-30 09:35:13
Topic: room-assistant/sensor/ble-1b8ab8940985/status
Qos: 0
Retained
online
2020-04-30 09:35:13
Topic: room-assistant/sensor/ble-0df785719207/state
Qos: 0
Retained
not_home
2020-04-30 09:35:13
Topic: room-assistant/sensor/ble-0df785719207/status
Qos: 0
Retained
online
2020-04-30 09:35:13
Topic: room-assistant/sensor/ble-35b4361de881/state
Qos: 0
Retained
not_home
2020-04-30 09:35:13
Topic: room-assistant/sensor/ble-35b4361de881/status
Qos: 0
Retained
online
2020-04-30 09:35:13
Topic: room-assistant/sensor/ble-4c24980935c0/state
Qos: 0
Retained
not_home
2020-04-30 09:35:13
Topic: room-assistant/sensor/ble-4c24980935c0/status
Qos: 0
Retained
online
2020-04-30 09:35:13
Topic: room-assistant/sensor/ble-7e3ca0205b46/state
Qos: 0
Retained
not_home
2020-04-30 09:35:13
Topic: room-assistant/sensor/ble-7e3ca0205b46/status
Qos: 0
Retained
online
2020-04-30 09:35:13
Topic: room-assistant/sensor/ble-52a5734dfe7a/state
Qos: 0
Retained
not_home
2020-04-30 09:35:13
Topic: room-assistant/sensor/ble-52a5734dfe7a/status
Qos: 0
Retained
online
```

`

```text
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```
lobal:
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
  instanceName: rpizero
  room: BeaconBLE
homeAssistant:
  mqttUrl: 'http://192.168.1.8:1883'
bluetoothLowEnergy:
  blacklist:
  - 000000000000
  updateFrequency: 8
  maxDistance: 8

```

**Expected behavior**
Only one topic? 
If a device is online only publish "online".

**Environment**
 - room-assistant version: 2.4.0.
 - installation type: NodeJS
 - hardware: Raspberry Pi Zero W
 - OS: Linux
