### ISSUE TITLE
Sony Smartwatch is not detected

### ISSUE THREAD

**Issue by fribse** [mKeRix/room-assistant#189]
**Describe the bug**
I have a Sony Smartwatch 3 (SWR50) and it is not detected by the room-assistant (and yes BT is on).
The Sony phones I have tried with are detected.

**To reproduce**
Add the MAC address of the Sony smartwatch place it near the room-assistant node, nothing happens.

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```text
Nothing shows in the log
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```yaml
global:
  cluster:
    autoDiscovery: false
    networkInterface: wlan0
    port: 6425
    peerAddresses:
      - '10.11.14.5:6425'
      - '10.11.14.6:6425'
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://mqttserver:1883'
  mqttOptions:
    username: mqtt
    password: pw
bluetoothClassic:
  minRssi: -20
  hciDeviceId: 0
  addresses:
    - '30:a8:db:f1:a0:36'
```

**Expected behavior**
It should appear under MQTT as a device, just like the phone

**Environment**
 - room-assistant version: 
 - installation type: Hass.io on pve on NUC
 - hardware (for nodes): Raspberry Pi Zero W

**Additional context**
I've placed the same config on all devices (including HA, wasn't sure if that is correct), they are rebooted of course, but still shows nothing.
