### ISSUE TITLE
Room-Assistant should exit / report error on hcitool error

### ISSUE THREAD

**Issue by RomRider** [mKeRix/room-assistant#194]
**Describe the bug**
Using docker, in the logs I see this (the hci0 crashed, it requires a reboot, `hciconfig hci0 reset` is not enough)
```
room-assistant_1  | 5/10/2020, 12:26:21 AM - debug - BluetoothClassicService: Command failed: hcitool -i hci0 cc "XX:XX:XX:XX:XX" && hcitool -i hci0 rssi "XX:XX:XX:XX:XX"
room-assistant_1  | Invalid device: Network is down
```

This means nothing is sent anymore from this device. It also reports itself as healthy in the cluster and also reports itself as healthy for a docker standpoint (which means it will not auto-restart)

```
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                    PORTS               NAMES
8dad12b03c7f        mkerix/room-assistant:latest   "tini -- room-assist…"   9 minutes ago       Up 9 minutes (healthy)                        room-assistant_room-assistant_1
```

**To reproduce**
I don't really know how to forcefully generate this problem, seems like a low level issue on the HW (but it happened a lot also on my NUC with some other tools using hcitool).

**Relevant logs**

```text
room-assistant_1  | 5/10/2020, 12:26:21 AM - debug - BluetoothClassicService: Command failed: hcitool -i hci0 cc "XX:XX:XX:XX:XX" && hcitool -i hci0 rssi "XX:XX:XX:XX:XX"
room-assistant_1  | Invalid device: Network is down
```

**Relevant configuration**
Using ansible

```yaml
cluster:
  networkInterface: '{{ room_assistant_interface }}'
  port: 6425
  peerAddresses: {{ room_assistant_cluster_members }}
  autoDiscovery: false
  weight: {{ room_assistant_weight | default(10) }}
  quorum: 2
global:
  instanceName: '{{ room_assistant_name }}'
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: '{{ mqtt_server }}'
  mqttOptions:
    username: '{{ mqtt_room_assistant_username }}'
    password: '{{ mqtt_room_assistant_password }}'
bluetoothClassic:
  hciDeviceId: 0
  minRssi: -30
  interval: 6
  addresses: {{ room_assistant_bluetooth_devices }}
```

**Expected behavior**
I think it should either report itself as unhealthy in the cluster and in docker, or exit so that either docker or systemd can restart it.
Maybe adding a health sensor would be usefull also to generate notifications :)

**Environment**
 - room-assistant version: `2.6.0`
 - installation type: Docker
 - hardware: Raspi 3B x1 / Zero W x2
 - OS: [e.g. Linux, Windows, macOS]: Linux
