### ISSUE TITLE
Legacy - How to connect to MQTT which runs on different device 

### ISSUE THREAD

**Issue by Shaun-Harrison** [mKeRix/room-assistant#197]
Hello

I'm assuming I'm not using the 'legacy' docker container, seeing as I am not using a config file, just a docker-compose file which looks as follows 

```
---
version: '2'
services:
  room-assistant:
    image: mkerix/room-assistant:latest-arm32
    restart: always
    network_mode: host
    environment:
      SERVICES: 'console,mqtt,ble'
      ROOM: 'Home'
      AUTO_DISCOVERY: 'true'
      BLE_CHANNEL: 'room_presence'
      BLE_UPDATE_FREQUENCY: 5
```

However I've now got room assistant running on a rpi0 w , but in the logs its saying it's connecting to mqtt://localhost. 
I'm assuming there is a Environment variable I can use to set the MQTT url ?
