### ISSUE TITLE
Distance always 1

### ISSUE THREAD

**Issue by huuub** [mKeRix/room-assistant#217]
I have room-assistant running in docker on a alpha latte panda in Linux Mint 19.3.
It works but I get always a distance of "1".
I also have a raspberry pi zero w which works ok.
Config: (tagoverrides don't work, probably do something wrong)
```
global:
  instanceName: living
  integrations:
#    - bluetoothLowEnergy
    - homeAssistant
    - bluetoothClassic

homeAssistant:
  mqttUrl: 'mqtt://192.168.1.2:1883'
  mqttOptions:
    username: jeroen
    password: whatever

bluetoothClassic:
  addresses:
    - '50:77:05:B7:11:A5'
    - '14:9F:3C:41:A9:86'
  minRssi: -9
  interval: 20
  timeoutCycles: 2.5
  tagOverrides:
    '14:9F:3C:41:A9:86':
      name: GSM-Agata
    '50:77:05:B7:11:A5' :
      name: GSM-huuubs
```

docker-compose:
```
  roomassistant:
    container_name: roomassistant
    image: mkerix/room-assistant
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/dbus:/var/run/dbus
      - ${SHB_HOME_CONT}/room-assistant/config:/room-assistant/config
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```
