### ISSUE TITLE
bluetooth low energy updateFrequency seems not to be adhered to

### ISSUE THREAD

**Issue by tehbra1n** [mKeRix/room-assistant#222]
I may be misunderstanding what updateFrequency is supposed to do, but in an attempt to stop my iBeacons from flapping between rooms while stationary I set it globally to 60s.  Despite this, the distance on a given tag seems to update several times per minute, occasionally causing the room to change.

Here is one of my local.yml files.  All are identical save the instanceName:

```
global:
  instanceName: office
  integrations:
    - bluetoothLowEnergy
    - homeAssistant
homeAssistant:
  mqttUrl: 'mqtt://<removed>.com:1883'
  mqttOptions:
    username: homeassistant
    password: <removed>
bluetoothLowEnergy:
  whitelist:
    - fda50693a4e24fb1afcfc6eb07647825-5-69
    - fda50693a4e24fb1afcfc6eb07647825-5-88
    - 449ab3fd4bc3
  maxDistance: 15
  updateFrequency: 60
  tagOverrides:
    fda50693a4e24fb1afcfc6eb07647825-5-69:
      measuredPower: -58
    fda50693a4e24fb1afcfc6eb07647825-5-88:
      measuredPower: -58
entities:
  behaviors:
    debounce:
      wait: 30
      maxwait: 120
```

Really my main goal is to get to a point where a stationary tag is seen as stationary by room-assistant.  I understand the inherent limitations on the distance measurement, but I feel like I should be able to get this to the point where if I'm sitting next to one RPi, the system should never think I'm in a room with another RPi.
