### ISSUE TITLE
 ibeacon does not publish

### ISSUE THREAD

**Issue by daiv87** [mKeRix/room-assistant#224]
I will have done something wrong in the configuration.
the beacon status is monitored for the first few minutes , after the status on homeassistant it remains on not-home despite the beacon being 20 cm from the raspberry.
this is my configuration:
```
global:
  integrations:
    - homeAssistant
    - bluetoothLowEnergy

homeAssistant:
  mqttUrl: 'mqtt://localhost:1883'
  mqttOptions:
    username: davide
    password: password

bluetoothLowEnergy:
  whitelist:
    - b5b182c7eab14988aa99b5c1517008d9-20-1
  maxDistance: 15
  #updateFrequency: 60
  tagOverrides:
    b5b182c7eab14988aa99b5c1517008d9-20-1: 
      name: davide BLE
      measuredPower: -59
```

and from the mobile app I gave these configurations to the beacon:
```
measure power: -59
tx Power: 4dbm
advertsing Freq : 6
switch delay in Second: 1
```
fow power up the bluetooth device i run the command:
```
sudo hciconfig hci0 up
```
after i have turned on the Bluetooth module we need to change its operating mode to “Low Energy Advertising
```
sudo hciconfig hci0 leadv 3
```
i test that the beacon is working on the raspberry
```
sudo hcitool -i hci0 cmd 0x08 0x0008 1E 02 01 06 1A FF 4C 00 02 15 C7 C1 A1 BF BB 00 4C AD 87 04 9F 2D 29 17 DE D2 00 00 00 00 C8 00
```
I posted all the steps I did because I'm not an expert.
I hope you can help me
```
