### ISSUE TITLE
Losing distance and last_updated_at attributes

### ISSUE THREAD

**Issue by circa1741** [mKeRix/room-assistant#227]
**Describe the bug**
I successfully configured room assistant on the following:
- hass.io on proxmox vm (laptop)
- raspberry pi zero w

The bluetooth classic device shows the following attributes:
distance:
last_updated_at:
friendly_name:
icon:

I added another raspberry pi zero w but it lost the distance and last_updated_at attributes.
I used to be able to verify that it is working because the distance and last_updated_at changes. now, the state seems stuck to the last instanceName it recorded. The state does not change to not_home even if I turn off the bluetooth_inquiries switch.

**To reproduce**
1. Configure room assistant on hass.io and on raspberry pi zero w.
2. Make sure that everything is working as expected.
3. Now, add another raspberry pi zero w with room assistant.
4. Observe that the distance and last_updated_at attributes are gone. The state seems stuck to the last instanceName it recorded. The state does not change to not_home even if I turn off the bluetooth_inquiries switch. 

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
7/5/2020, 1:00:26 AM - info - IntegrationsModule: Loading integrations: none
7/5/2020, 1:00:28 AM - info - NestFactory: Starting Nest application...
7/5/2020, 1:00:29 AM - info - InstanceLoader: AppModule dependencies initialized
7/5/2020, 1:00:29 AM - info - InstanceLoader: ConfigModule dependencies initialized
7/5/2020, 1:00:29 AM - info - InstanceLoader: NestEmitterModule dependencies initialized
7/5/2020, 1:00:29 AM - info - InstanceLoader: IntegrationsModule dependencies initialized
7/5/2020, 1:00:29 AM - info - InstanceLoader: HttpModule dependencies initialized
7/5/2020, 1:00:29 AM - info - InstanceLoader: DiscoveryModule dependencies initialized
7/5/2020, 1:00:29 AM - info - InstanceLoader: ClusterModule dependencies initialized
7/5/2020, 1:00:29 AM - info - InstanceLoader: TerminusModule dependencies initialized
7/5/2020, 1:00:29 AM - info - InstanceLoader: ScheduleModule dependencies initialized
7/5/2020, 1:00:29 AM - info - InstanceLoader: EntitiesModule dependencies initialized
7/5/2020, 1:00:29 AM - info - InstanceLoader: StatusModule dependencies initialized
7/5/2020, 1:00:31 AM - info - RoutesResolver: EntitiesController {/entities}:
7/5/2020, 1:00:31 AM - info - RouterExplorer: Mapped {/entities, GET} route
7/5/2020, 1:00:31 AM - info - RoutesResolver: StatusController {/status}:
7/5/2020, 1:00:31 AM - info - RouterExplorer: Mapped {/status, GET} route
7/5/2020, 1:00:31 AM - info - ConfigService: Loading configuration from /opt/nodejs/lib/node_modules/room-assistant/dist/config/definitions/default.js
7/5/2020, 1:00:31 AM - warn - ConfigService: No configuration found in /home/pi/config
7/5/2020, 1:00:32 AM - debug - EntitiesService: Adding new entity status-cluster-size
7/5/2020, 1:00:32 AM - debug - EntitiesService: Adding new entity status-cluster-leader
7/5/2020, 1:00:32 AM - info - ClusterService: Starting mDNS advertisements and discovery
7/5/2020, 1:00:32 AM - info - NestApplication: Nest application successfully started
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::6415
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at ExpressAdapter.listen (/opt/nodejs/lib/node_modules/room-assistant/node_modules/@nestjs/platform-express/adapters/express-adapter.js:45:32)
    at NestApplication.listen (/opt/nodejs/lib/node_modules/room-assistant/node_modules/@nestjs/core/nest-application.js:144:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1307:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```
global:
  instanceName: <instanceName 1>
  integrations:
    - homeAssistant
    - bluetoothClassic
bluetoothClassic:
  interval: 20
  addresses:
    - '<bluetooth classic 1>'
    - '<bluetooth classic 1>'
homeAssistant:
  mqttUrl: '<mqttUrl>'
  mqttOptions:
    username: <mqtt username>
    password: <mqtt password>
cluster:
  networkInterface: wlan0
  port: 6425
  weight: 1
  peerAddresses:
    - '<hass.io on proxmox vm>'
    - '<rpi zero w 1>'
    - '<rpi zero w 2>'
```

**Expected behavior**
Should show distance and last_updated_at attributes

**Environment**
 - room-assistant version: 2.82
 - installation type: hass.io on proxmox vm
 - hardware: laptop and raspberry pi zero w
 - OS: hass os and raspbian lite

**Additional context**
The bluetooth classic devices are:
- Android phone
- iOS phone

**Comment by mKeRix** [comment]
Do you have the Home Assistant and Bluetooth Classic integrations enabled and configured like that on your second Raspberry too? In a cluster, room-assistant will elect a leader instance that is then responsible for managing sensors that are determined across multiple instances (e.g. the Bluetooth Classic sensors). Since this could technically be any instance it's best to keep the configurations for these shared things the same across all installations. Alternatively you can try to configure a [preferred leader](https://www.room-assistant.io/guide/cluster.html#usage-tips).

**Comment by circa1741** [comment]
Both Rpi 0 W are configured the same except for the instanceName. (see Relevant Configuration in the original post).

As for the hassio, it is configured with "weight: 99" to make it as the preferred leader.

**Comment by mKeRix** [comment]
In that case, could you stop the room-assistant service on your Pi Zero (`sudo systemctl stop room-assistant`) and then start room-assistant manually like you did above (with the `-v` log)? Just so that we have some more data to go by, as the logs in your original post only show the failed start-up because you had two instances of the software running on the Pi at the same time.

**Comment by circa1741** [comment]
I will get the `room-assistant -v` log. But in the meantime, I found a sequence that gets me up and running. But it is a lot of work and I plan to add more RPi0Ws.

**Preparation**
Step 1. Shutdown hassio with room-assistant.
Step 2. Shutdown rpi0w1 and unplug from power source.
Step 3. Shutdown rpi0w2 and unplug from power source.

**Step 4. Boot hassio with room-assistant.**
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:45:09] INFO: Setting up Home Assistant configuration
[16:45:09] INFO: Starting room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
7/13/2020, 4:45:15 PM - info - IntegrationsModule: Loading integrations: home-assistant
7/13/2020, 4:45:17 PM - info - NestFactory: Starting Nest application...
7/13/2020, 4:45:17 PM - info - InstanceLoader: AppModule dependencies initialized
7/13/2020, 4:45:17 PM - info - InstanceLoader: ConfigModule dependencies initialized
7/13/2020, 4:45:17 PM - info - InstanceLoader: NestEmitterModule dependencies initialized
7/13/2020, 4:45:17 PM - info - InstanceLoader: IntegrationsModule dependencies initialized
7/13/2020, 4:45:17 PM - info - InstanceLoader: HttpModule dependencies initialized
7/13/2020, 4:45:17 PM - info - InstanceLoader: DiscoveryModule dependencies initialized
7/13/2020, 4:45:17 PM - info - InstanceLoader: HomeAssistantModule dependencies initialized
7/13/2020, 4:45:17 PM - info - InstanceLoader: ClusterModule dependencies initialized
7/13/2020, 4:45:17 PM - info - InstanceLoader: TerminusModule dependencies initialized
7/13/2020, 4:45:17 PM - info - InstanceLoader: ScheduleModule dependencies initialized
7/13/2020, 4:45:17 PM - info - InstanceLoader: EntitiesModule dependencies initialized
7/13/2020, 4:45:17 PM - info - InstanceLoader: StatusModule dependencies initialized
7/13/2020, 4:45:17 PM - info - RoutesResolver: EntitiesController {/entities}:
7/13/2020, 4:45:17 PM - info - RouterExplorer: Mapped {/entities, GET} route
7/13/2020, 4:45:17 PM - info - RoutesResolver: StatusController {/status}:
7/13/2020, 4:45:17 PM - info - RouterExplorer: Mapped {/status, GET} route
7/13/2020, 4:45:17 PM - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://192.168.1.xxx:1883
7/13/2020, 4:45:17 PM - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/default.json, config/local.json
7/13/2020, 4:45:18 PM - info - ClusterService: Starting mDNS advertisements and discovery
7/13/2020, 4:45:18 PM - info - NestApplication: Nest application successfully started
7/13/2020, 4:45:19 PM - info - **ClusterService: hassio has been elected as leader**
7/13/2020, 4:45:19 PM - info - EntitiesService: Refreshing entity states

**Step 5. Plug rpi0w1 to power source.**

**Step 6. Check log of hassio with room-assistant.**
7/13/2020, 4:48:00 PM - info - **ClusterService: Added 192.168.1.xxx:6425 to the cluster with id rpi0w1**

**Step 7. Check Developer Tools**
Entity:
`sensor.phone1_room_presence`
State:
`rpi0w1`
Attributes:
```
friendly_name: PHONE1 Room Presence
icon: mdi:bluetooth
```

At this point, rpi0w1 is not yet detecting.

**Step 8. Reboot hassio with room-assistant.**
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:58:35] INFO: Setting up Home Assistant configuration
[16:58:35] INFO: Starting room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
7/13/2020, 4:59:11 PM - info - IntegrationsModule: Loading integrations: home-assistant
7/13/2020, 4:59:19 PM - info - NestFactory: Starting Nest application...
7/13/2020, 4:59:21 PM - info - InstanceLoader: AppModule dependencies initialized
7/13/2020, 4:59:21 PM - info - InstanceLoader: ConfigModule dependencies initialized
7/13/2020, 4:59:21 PM - info - InstanceLoader: NestEmitterModule dependencies initialized
7/13/2020, 4:59:21 PM - info - InstanceLoader: IntegrationsModule dependencies initialized
7/13/2020, 4:59:21 PM - info - InstanceLoader: HttpModule dependencies initialized
7/13/2020, 4:59:21 PM - info - InstanceLoader: DiscoveryModule dependencies initialized
7/13/2020, 4:59:21 PM - info - InstanceLoader: HomeAssistantModule dependencies initialized
7/13/2020, 4:59:21 PM - info - InstanceLoader: ClusterModule dependencies initialized
7/13/2020, 4:59:21 PM - info - InstanceLoader: TerminusModule dependencies initialized
7/13/2020, 4:59:21 PM - info - InstanceLoader: ScheduleModule dependencies initialized
7/13/2020, 4:59:21 PM - info - InstanceLoader: EntitiesModule dependencies initialized
7/13/2020, 4:59:21 PM - info - InstanceLoader: StatusModule dependencies initialized
7/13/2020, 4:59:22 PM - info - RoutesResolver: EntitiesController {/entities}:
7/13/2020, 4:59:22 PM - info - RouterExplorer: Mapped {/entities, GET} route
7/13/2020, 4:59:22 PM - info - RoutesResolver: StatusController {/status}:
7/13/2020, 4:59:22 PM - info - RouterExplorer: Mapped {/status, GET} route
7/13/2020, 4:59:22 PM - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://192.168.1.xxx:1883
7/13/2020, 4:59:22 PM - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/default.json, config/local.json
7/13/2020, 4:59:22 PM - info - ClusterService: Starting mDNS advertisements and discovery
7/13/2020, 4:59:22 PM - info - NestApplication: Nest application successfully started

**Step 9. Check Developer Tools**
Entity:
`sensor.phone1_room_presence`
State:
`rpi0w1`
Attributes:
```
distance: 0.2
last_updated_at: 2020-07-13T22:02:42.266Z
friendly_name: PHONE1 Room Presence
icon: mdi:bluetooth
```

Now, rpi0w1 is successfully detecting.

**Step 10. Plug rpi0w2 to power source.**

**Step 11. Check log of hassio with room-assistant.**
7/13/2020, 5:04:48 PM - info - **ClusterService: Added 192.168.1.xxx:6425 to the cluster with id rpi0w2**

**Step 12. Check Developer Tools**
Entity:
`sensor.phone1_room_presence`
State:
`rpi0w2`
Attributes:
distance: 0
last_updated_at: 2020-07-13T22:09:12.657Z
friendly_name: PHONE1 Room Presence
icon: mdi:bluetooth

And, rpi0w2 is also successfully detecting.

As you can see, I have to physically unplug the RPi0Ws from its power source.

I will try `sudo systemctl stop room-assistant` and see if that will cut down the work.

**Comment by circa1741** [comment]
The sequence described in my previous post got everything working (e.g. hassio (without bluetooth), rpi0w1 (with bluetooth) and rpi0w2 (with bluetooth)).

In rpi0w1, performed sudo systemctl stop room-assistant. Immediately, tracking stopped even with room-assistant in hassio and rpi0w2 still running. distance and last_updated_at froze and no longer updating.

room-assistant -v log follows:

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
7/14/2020, 11:11:15 AM - info - IntegrationsModule: Loading integrations: none
7/14/2020, 11:11:17 AM - info - NestFactory: Starting Nest application...
7/14/2020, 11:11:18 AM - info - InstanceLoader: AppModule dependencies initialized
7/14/2020, 11:11:18 AM - info - InstanceLoader: ConfigModule dependencies initialized
7/14/2020, 11:11:18 AM - info - InstanceLoader: NestEmitterModule dependencies initialized
7/14/2020, 11:11:18 AM - info - InstanceLoader: IntegrationsModule dependencies initialized
7/14/2020, 11:11:18 AM - info - InstanceLoader: HttpModule dependencies initialized
7/14/2020, 11:11:18 AM - info - InstanceLoader: DiscoveryModule dependencies initialized
7/14/2020, 11:11:18 AM - info - InstanceLoader: ClusterModule dependencies initialized
7/14/2020, 11:11:18 AM - info - InstanceLoader: TerminusModule dependencies initialized
7/14/2020, 11:11:18 AM - info - InstanceLoader: ScheduleModule dependencies initialized
7/14/2020, 11:11:18 AM - info - InstanceLoader: EntitiesModule dependencies initialized
7/14/2020, 11:11:18 AM - info - InstanceLoader: StatusModule dependencies initialized
7/14/2020, 11:11:20 AM - info - RoutesResolver: EntitiesController {/entities}:
7/14/2020, 11:11:20 AM - info - RouterExplorer: Mapped {/entities, GET} route
7/14/2020, 11:11:20 AM - info - RoutesResolver: StatusController {/status}:
7/14/2020, 11:11:20 AM - info - RouterExplorer: Mapped {/status, GET} route
7/14/2020, 11:11:20 AM - info - ConfigService: Loading configuration from /opt/nodejs/lib/node_modules/room-assistant/dist/config/definitions/default.js
7/14/2020, 11:11:20 AM - warn - ConfigService: No configuration found in /home/pi/config
7/14/2020, 11:11:20 AM - debug - EntitiesService: Adding new entity status-cluster-size
7/14/2020, 11:11:20 AM - debug - EntitiesService: Adding new entity status-cluster-leader
7/14/2020, 11:11:21 AM - info - ClusterService: Starting mDNS advertisements and discovery
7/14/2020, 11:11:21 AM - info - NestApplication: Nest application successfully started
7/14/2020, 11:11:21 AM - info - ClusterService: rpi0w1r has been elected as leader
7/14/2020, 11:11:21 AM - info - EntitiesService: Refreshing entity states
7/14/2020, 11:11:21 AM - info - ClusterService: Added 192.168.1.xxx:6425 to the cluster with id hassio
7/14/2020, 11:11:22 AM - info - ClusterService: Added 192.168.1.xxx:6425 to the cluster with id rpi0w2

distance and last_updated_at still frozen. The only way to get everything working again is to perform the sequence described in my previous post again.

**Comment by circa1741** [comment]
For what its worth, below are the configurations:

**hassio (without bluetooth)**

```
global:
  instanceName: hassio
  integrations:
    - homeAssistant
#    - bluetoothClassic #hassio has no bluetooth
cluster:
  networkInterface: enp0s18
  peerAddresses:
    - '192.168.1.xxx:6425' #hassio
    - '192.168.1.xxx:6425' #rpi0w1
    - '192.168.1.xxx:6425' #rpi0w2
  weight: 99 #cluster leader
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.xxx:1883'
  mqttOptions:
    password: mqtt_password
    username: mqtt_username
#bluetoothClassic: #hassio has no bluetooth
#  addresses:
#    - 'xx:xx:xx:xx:xx:xx' #android phone
#    - 'xx:xx:xx:xx:xx:xx' #ios phone
#  interval: 10
#  minRssi:
#    'xx:xx:xx:xx:xx:xx': -5 #android phone
#    'xx:xx:xx:xx:xx:xx': -5 #ios phone
#  timeoutCycles: 10
```

**rpi0w1 (with bluetooth)**

```
global:
  instanceName: rpi0w1
  integrations:
    - homeAssistant
    - bluetoothClassic
cluster:
  networkInterface: wlan0
#  peerAddresses: #works even if peerAddresses not listed
#    - '192.168.1.xxx:6425' #hassio
#    - '192.168.1.xxx:6425' #rpi0w1
#    - '192.168.1.xxx:6425' #rpi0w2
  weight: 1
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.xxx:1883'
  mqttOptions:
    password: mqtt_password
    username: mqtt_username
bluetoothClassic:
  addresses:
    - 'xx:xx:xx:xx:xx:xx' #android phone
    - 'xx:xx:xx:xx:xx:xx' #ios phone
  interval: 10
  minRssi:
    'xx:xx:xx:xx:xx:xx': -5 #android phone
    'xx:xx:xx:xx:xx:xx': -5 #ios phone
  timeoutCycles: 10
```

**rpi0w2 (with bluetooth)**

```
global:
  instanceName: rpi0w2
  integrations:
    - homeAssistant
    - bluetoothClassic
cluster:
  networkInterface: wlan0
#  peerAddresses: #works even if peerAddresses not listed
#    - '192.168.1.xxx:6425' #hassio
#    - '192.168.1.xxx:6425' #rpi0w1
#    - '192.168.1.xxx:6425' #rpi0w2
  weight: 1
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.xxx:1883'
  mqttOptions:
    password: mqtt_password
    username: mqtt_username
bluetoothClassic:
  addresses:
    - 'xx:xx:xx:xx:xx:xx' #android phone
    - 'xx:xx:xx:xx:xx:xx' #ios phone
  interval: 10
  minRssi:
    'xx:xx:xx:xx:xx:xx': -5 #android phone
    'xx:xx:xx:xx:xx:xx': -5 #ios phone
  timeoutCycles: 10
```
