### ISSUE TITLE
Rivalling clusters with the same nodes?

### ISSUE THREAD

**Issue by angadsingh** [mKeRix/room-assistant#262]
**Describe the bug**
Each node says it is its own cluster's leader. Entity status reporting to home assistant seems to be working correctly for a single BLE device i have setup to track. However the 'cluster leader' shows to be the node itself on each node, instead of the master node.

This may or may not be a bug, and could just be lack of clarity in the documentation.

**To reproduce**
simple 2-node setup with 2 raspberry PI's (one is running on HASS and the other natively on raspberry Pi OS and nodejs, but don't think that matters)

**Relevant logs**
Here's the output of the /entities REST api:

on the master node (called "mbr")
```json
[{
	"attributes": {
		"nodes": ["living-room", "mbr"]
	},
	"id": "status-cluster-size",
	"name": "mbr Cluster Size",
	"distributed": false,
	"state": 2
}, {
	"attributes": {
		"quorumReached": true
	},
	"id": "status-cluster-leader",
	"name": "mbr Cluster Leader",
	"distributed": false,
	"state": "mbr"
}, {
	"attributes": {},
	"id": "ble-ee01b5455f23-tracker",
	"name": "FitBark",
	"distributed": true,
	"state": true
}, {
	"attributes": {
		"distance": 2.3,
		"lastUpdatedAt": "2020-08-12T05:31:51.935Z"
	},
	"id": "ble-ee01b5455f23",
	"name": "FitBark Room Presence",
	"distributed": true,
	"distances": {
		"mbr": {
			"lastUpdatedAt": "2020-08-12T05:31:51.935Z",
			"distance": 2.3,
			"outOfRange": false
		},
		"living_room": {
			"lastUpdatedAt": "2020-08-12T05:31:50.952Z",
			"distance": 27.5,
			"outOfRange": true
		}
	},
	"timeout": 5,
	"measuredValues": {
		"mbr": {
			"rssi": -66.1067395387145,
			"measuredPower": -59
		},
		"living_room": {
			"rssi": -91.87616736293079,
			"measuredPower": -59
		}
	},
	"state": "mbr"
}]
```

and on the slave node ("living_room"):
```json
[{
	"attributes": {
		"nodes": ["mbr", "living-room"]
	},
	"id": "status-cluster-size",
	"name": "living_room Cluster Size",
	"distributed": false,
	"state": 2
}, {
	"attributes": {
		"quorumReached": true
	},
	"id": "status-cluster-leader",
	"name": "living_room Cluster Leader",
	"distributed": false,
	"state": "living-room"
}, {
	"attributes": {},
	"id": "ble-ee01b5455f23-tracker",
	"name": "FitBark",
	"distributed": true,
	"state": true
}, {
	"attributes": {
		"distance": 2.5,
		"lastUpdatedAt": "2020-08-12T05:50:36.288Z"
	},
	"id": "ble-ee01b5455f23",
	"name": "FitBark Room Presence",
	"distributed": true,
	"distances": {
		"mbr": {
			"lastUpdatedAt": "2020-08-12T05:50:36.288Z",
			"distance": 2.5,
			"outOfRange": false
		},
		"living_room": {
			"lastUpdatedAt": "2020-08-12T05:36:12.223Z",
			"distance": 25.1,
			"outOfRange": true
		}
	},
	"timeout": 5,
	"measuredValues": {
		"mbr": {
			"rssi": -67.04512685572811,
			"measuredPower": -59
		},
		"living_room": {
			"rssi": -90.80375735644033,
			"measuredPower": -59
		}
	},
	"state": "mbr"
}]
```

**Relevant configuration**

configuration on both nodes:

```yaml
global:
  instanceName: mbr
  integrations:
    - bluetoothLowEnergy
    - homeAssistant
cluster:
  weight: 1
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.24:1883'
  mqttOptions:
    username: mqtt
    password: <password>
bluetoothLowEnergy:
  whitelist:
    - ee01b5455f23
entities:
  behaviors:
    ble-ee01b5455f23-tracker:
      debounce:
        wait: 5
        maxWait: 30
```
the only difference in configuration: weight is set to `0` on `living_room` and `1` on `mbr` (as i want `mbr` to be the leader, which is connected via ethernet)

**Expected behavior**
The leader should be the same as reported by both nodes. Each of them can't be their own leader.

**Environment**
 - room-assistant version: 2.8.2
 - installation type: `mbr` on Hass.io, `living_room` on NodeJS
 - hardware: `mbr` on Raspberry Pi 4B, `living_room` on Raspberry Pi Zero W
 - OS: `living_room` on Raspberry OS
