### ISSUE TITLE
Logs show the most recently restarted node as elected leader, despite weights

### ISSUE THREAD

**Issue by angadsingh** [mKeRix/room-assistant#263]
**Describe the bug**
I have a 2 node setup - node1 and node2. I have set one of the nodes (`node1`) to have a weight of `20`, which I prefer to become the leader, and the other (`node2`) to `10`. Because of another issue (https://github.com/mKeRix/room-assistant/issues/262), i ended up specifying the `peerAddresses` inside `cluster` config, after which  leader gets elected correctly   After i start both the nodes, I can see that the leader gets correctly as `node` when i hit the /entities API on **both** the nodes. Perfect. But whenever i restart one of the nodes, the log on the other node shows that the other has become the leader - even the API says the correct election.

**To reproduce**
Setup up two nodes as per the config below
Start/restart both nodes - leader will be elected properly, as per the entities API
Restart one of the nodes - logs will show that leader as elected, even though API shows the correct leader, as per weight

**Relevant logs**
```
8/12/2020, 3:49:37 PM - info - ClusterService: node2has been elected as leader
```

**Relevant configuration**

node1
```yaml
global:
  instanceName: node1
  integrations:
    - bluetoothLowEnergy
    - homeAssistant
cluster:
  weight: 20
  autoDiscovery: false
  peerAddresses:
    - '192.168.1.19:6425'
    - '192.168.1.67:6425'
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.19:1883'
  mqttOptions:
    username: mqtt
    password: <password>
bluetoothLowEnergy:
  whitelist:
    - ee01b5455f23
entities:
  behaviors:
    ble-ee01b5455f23-tracker:
      debounce:
        wait: 5
        maxWait: 30
```

node2
```
global:
  instanceName: node2
  integrations:
    - bluetoothLowEnergy
    - homeAssistant
cluster:
  weight: 10
  autoDiscovery: false
  peerAddresses:
    - 192.168.1.19:6425
    - 192.168.1.67:6425
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.19:1883'
  mqttOptions:
    username: mqtt
    password: <password>
bluetoothLowEnergy:
  whitelist:
    - ee01b5455f23
  maxDistance: 3
entities:
  behaviors:
    ble-ee01b5455f23-tracker:
      debounce:
        wait: 5
        maxWait: 30
```

**Expected behavior**
Logs should show the same leader as the API

**Environment**
 - room-assistant version: 2.8.2
 - installation type: `node1` on Hass.io, `node2` on NodeJS
 - hardware: `node1` on Raspberry Pi 4B, `node2` on Raspberry Pi Zero W
 - OS: `node2` on Raspberry OS
