### ISSUE TITLE
Bluetooth BLE finding iBeacon, not publishing to MQTT

### ISSUE THREAD

**Issue by yieldhog** [mKeRix/room-assistant#276]
**Describe the bug**
Bluetooth BLE finding iBeacon, not publishing to MQTT. Thank you

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```
successfully connects to MQTT... nothing is ever published. MQTT auto-discovery on.

BluetoothLowEnergyService: Discovered new BLE peripheral XXX-3838-4949 with ID XXX-3838-4949 and RSSI -89
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```
global:
  instanceName: garage
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.X:1883'
  mqttOptions:
    username: XXX
    password: XXX
bluetoothLowEnergy:
  whitelist:
    - XXX-3838-4949
  tagOverrides:
    XXX-3838-4949:
      name: iBeacon
```

Also, it is unclear to me in the documentation how you setup a device_tracker for iBeacon UUID on BLE

```
device_tracker:
- platform: mqtt
  devices:
    **apple_watch: 'room-assistant/device_tracker/bluetooth-classic-aa-aa-aa-aa-aa-aa-tracker/state'**
  payload_home: 'true'
  payload_not_home: 'false'
  source_type: bluetooth
```
