### ISSUE TITLE
Xiaomi sensors

### ISSUE THREAD

**Issue by mycanaletto** [mKeRix/room-assistant#280]
Hi,

I have this error 
`9/13/2020, 11:03:37 PM - warn - XiaomiMiService: Clear Cuisine does not appear to be a Xiaomi device. Got advertisement {"localName":"ClearGrass Temp & RH","serviceData":[{"uuid":"fdcd","data":{"type":"Buffer","data":[8,7,109,77,16,52,45,88,1,4,34,1,28,2,2,1,11]}}],"serviceUuids":[],"solicitationServiceUuids":[],"serviceSolicitationUuids":[]}`

The information goes back to HA but without the battery information.

Merci !

```
global:
  instanceName: canaletto_ble
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
    - xiaomiMi
homeAssistant:
  mqttUrl: 'mqtt://192.168.210.44:1883'
  mqttOptions:
    username: mqtt
    password: xx
bluetoothClassic:
  minRssi: '-20'
  hciDeviceId: 1
  addresses:
    - 'xx:65:2D:D4:xx:xx'
bluetoothLowEnergy:
  hciDeviceId: 1
  onlyIbeacon: true
  whitelist:
    - f8de32b1ddffg
    - 94652DDdfgd6
    - 1dbedc84d5bdfgdga93d22a85cb1f933-9-9
  tagOverrides:
    f8de32gfdsfgd:
      name: Tile
xiaomiMi:
  hciDeviceId: 1
  sensors:
    - name: Clear Cuisine
      address: 582fgdg4d6d
    - name: Clear SdB
      address: 58dgdg03286
    - name: Clear Exterieur
      address: 4c65dfgdb75
    - name: Clear Square
      address: 3f59dgd0ca
    - name: Clear Clock
      address: 582d3dgddg2
      bindKey: cc0d9d2dgfd95d27eacf5250e2e8
entities:
  behaviors:
    ble-f8de32dgdfg-tracker:
      debounce:
        wait: 1.75
        maxWait: 2
```
