### ISSUE TITLE
blutooth not working in docker

### ISSUE THREAD

**Issue by ljmerza** [mKeRix/room-assistant#290]
**Describe the bug**
I cant get the bluetooth to work at all

**To reproduce**
```
room-assistant:
    image: mkerix/room-assistant
    container_name: roomassistant
    restart: unless-stopped
    network_mode: host
    command: --digResolver --verbose
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - /home/user/docker/volumes/roomassistant:/room-assistant/config
      - /var/run/dbus:/var/run/dbus
```

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```text
10/1/2020, 3:05:47 PM - error - HealthCheckService: Health Check has failed! {"bt_successive_errors":{"status":"down"}}
10/1/2020, 3:05:49 PM - debug - BluetoothClassicService: Querying for RSSI of xx:xx:xx:xx:xx:xx using hcitool
10/1/2020, 3:05:49 PM - error - BluetoothClassicService: Command failed: hcitool -i hci0 cc "xx:xx:xx:xx:xx:xx" && hcitool -i hci0 rssi "xx:xx:xx:xx:xx:xx"
Invalid device: Network is dow
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```yaml
global:
  instanceName: office
  integrations:
    - homeAssistant
    - bluetoothClassic

homeAssistant:
  mqttUrl: "mqtt://192.168.x.xx:1883"

bluetoothClassic:
  # hciDeviceId: 0
  # minRssi: -60
  scanTimeLimit: 60
  addresses:
    - xx:xx:xx:xx:xx:xx
```

**Expected behavior**

**Environment**
 - room-assistant version: 2.9.1
 - installation type: docker
 - hardware: pc
 - OS: ubuntu

**Additional context**
i can connect to the bluetooth just fine on the host system without room assitant but as soon as i turn on room assistant the bluetooth keeps turning off and on
