### ISSUE TITLE
Room Assistant not detecting any BLE Tags

### ISSUE THREAD

**Issue by yonz2** [mKeRix/room-assistant#307]
Hi,

I am new to Room Assistant, and am trying to get it running on a single Raspberry Pi Zero W.
So far I've installed it, and got it running, and connected to Home Assistant (running on a separate PI3 B)

```yaml
global:
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://hassio:1883'
  mqttOptions:
    username: b27_mqtt
    password: MyPassword
bluetoothLowEnergy:
  maxDistance: 7
  whitelist:
    - 589ec6203f0a
    - 589ec600d54b
```
I used the hcitool with the lescan option to find the Mac Addresses:
`pi@raspi1:~ $ hcitool lescan`

`LE Scan ...`
`58:9E:C6:00:D5:4B Gigaset keeper`
`58:9E:C6:20:3F:0A Gigaset G-tag`

So you can see that a) the hcitool is accessible by user "pi" and b) the two devices are seen from the Raspi Zero.

I do not get any device information neither on the log nor in Home Assistant

`10/19/2020, 21:11:45 - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://hassio:1883`
`10/19/2020, 21:11:45 - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/local.yml`
`...`
`10/19/2020, 21:11:45 - debug - HomeAssistantService: Registering entity room-assistant-raspi1-status-cluster-leader under homeassistant/sensor/room-assistant/raspi1-status-cluster-leader/config`
`10/19/2020, 21:11:45 - debug - HomeAssistantService: Sending new state 1 for room-assistant-raspi1-status-cluster-size`
`10/19/2020, 21:11:45 - debug - HomeAssistantService: Sending new state raspi1 for room-assistant-raspi1-status-cluster-leader`
`10/19/2020, 21:11:45 - info - ClusterService: Starting mDNS advertisements and discovery`
`10/19/2020, 21:11:45 - info - NestApplication: Nest application successfully started`
`10/19/2020, 21:11:45 - debug - HomeAssistantService: Sending new attributes {"nodes":["raspi1"]} for room-assistant-raspi1-status-cluster-size`
`10/19/2020, 21:11:45 - debug - HomeAssistantService: Sending new attributes {"quorumReached":true} for room-assistant-raspi1-status-cluster-leader`
`...`
`- - - The log just hangs here .... no further messages are output - - -`

Am I missing something???? Is there something I must do in Home Assistant?

**Expected behavior**
A set of MQTT Events in Home Assistant

**Environment**
 - room-assistant version: 2.10
 - installation type: NodeJS. V12.19.0
 - hardware:  Raspberry Pi Zero W Rev 1.1
 - OS: Raspbian (just did a "dist-upgrade")

Any hint would be much appreciated.

Yonz
