### ISSUE TITLE
Home Assistant Addon crashes, when another node shuts down

### ISSUE THREAD

**Issue by gadric** [mKeRix/room-assistant#308]
**Describe the bug**
In my set up with 3 room-assistant installation: 
1. as Home Assistant Addon
2. On Raspberry Pi Zero W (NodeJS installation according to the official guide)
3. On Raspberry Pi 4B (NodeJS installation according to the official guide)

My Home Assistant automatically shuts down my Raspberry Pi 4 if nobody is at home or if every at home is sleeping. But, as soon as the Raspberry Pi 4 is offline, the room assistant addon installation crashs. The NodeJS installation works fine. 

**To reproduce**
Steps required to reproduce the issue.

Start all 3 Raspi and let everything work. Then shut down the Raspberry Pi 4. A couple of seconds later the Room Assistant Addon in Home Assistant crashs

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.
```text
10/19/2020, 11:30:08 PM - info - ClusterService: Removed 192.168.xxx.xxx:6425 from the cluster with id office
10/19/2020, 11:30:08 PM - info - ClusterService: Removed 192.168.xxx.xxx:6425 from the cluster with id office
/usr/lib/node_modules/room-assistant/dist/cluster/cluster.service.js:124
            const leaders = Object.entries(this._nodes).filter((node) => node[1].state === 'leader');
                                                                                 ^
TypeError: Cannot read property 'state' of null
    at /usr/lib/node_modules/room-assistant/dist/cluster/cluster.service.js:124:82
    at Array.filter (<anonymous>)
    at ClusterService.processEvent (/usr/lib/node_modules/room-assistant/dist/cluster/cluster.service.js:124:57)
    at Socket.<anonymous> (/usr/lib/node_modules/room-assistant/node_modules/democracy/lib/democracy.js:73:14)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage [as onmessage] (dgram.js:910:8)
[cmd] /room-assistant/entrypoint.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```yaml
global:
  cluster:
    autoDiscovery: false
    port: 6425
    peerAddresses:
       - '192.168.yyy.yyy:6425'
       - '192.168.xxx.xxx:6425'
    instanceName: livingroom
    integrations:
     - homeAssistant
     - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtts://'
  mqttOptions:
    username: 
    password: 
    rejectUnauthorized: false
bluetoothClassic:
  interval: 15
  scanTimeLimit: 10
  timeoutCycles: 5
  minRssi: -30
  addresses:
    - '123232'
    - '21341234'
    - '23424'
```

**Expected behavior**
No Crash of the Addon

**Environment**
 - room-assistant version: all on 2.10.0
 - installation type: NodeJS, Hass.io]
 - hardware: Raspberry Pi Zero W, Raspberry Pi 3B, Raspberry Pi 4B
 - OS: Home Assistant, Raspbian

**Additional context**
