### ISSUE TITLE
Can't load Room-Assistant for the first time.

### ISSUE THREAD

**Issue by Derrick355** [mKeRix/room-assistant#312]
**Describe the bug**
Setting up Room assistant for the first time and it doesn't seem like the `BluetoothClassicService` is starting properly

**Relevant configuration**

```yaml                                    
global:
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://homeassistant.local:8113'
  mqttOptions:
    username: Room-Assistant
    password: ##room-assistant's user password
bluetoothClassic:
  addresses:
    - ##My phone's BT MAC address
```

**Console Output**

```text
10/20/2020, 10:45:59 PM - error - BluetoothClassicService: Command failed: hciconfig hci0 reset
Can't down device hci0: Operation not permitted (1)
```

**Expected behavior**
For Room-assistant to start.

**Environment**
 - room-assistant version: Latest
 - installation type: Hass.io
 - hardware: Raspberry Pi Zero W
 - OS: Raspbian

**Additional context**
The `BluetoothClassicServce` error will repeat after a set timeout.
I also already ran the command ```sudo setcap cap_net_raw+eip $(eval readlink -f `which hcitool`)``` to give it permission to use Bluetooth.
