### ISSUE TITLE
No way to detect when RA node is lost due to connectivity issues

### ISSUE THREAD

**Issue by KonstantinNosov** [mKeRix/room-assistant#313]
**Describe the bug**
I have setup with 2 nodes cluster of RA (both nodes are rpi)
rpi in garage tracks presence of the car with BLE 
so if I turn off  rpi or the switch that connects it to LAN (assume same will happen if RA crashes) another node will report that  car device previously observed with lost node is not_home. 
When garage rpi is back it reports that device is back and car is in garage

The problem is - HA automation opens garage door when car device is discovered. And thus disappear/appear of car device caused by RA node availability also triggers garage door opening. 

I'd like to filter out such situation. Obvious solution is tracking of availability of sensors related to garage rpi, but they are all  available in spite of rpi is down. Only case when availability is properly reported is clear RA service shutdown.

I believe the problem is in missing of MQTT last will message.

There may be only one last will MQTT client may configure when establishing connection.
I'd propose the following impleentation
1. when RA connects to MQTT it 
   - Sets up last will message to be  sent to  `room-assistant/switch/[node name]-availability` with `offline` payload
   - Sends `online` to `room-assistant/switch/[node name]-availability`
1. All autodiscovery HA entities are configured to use `room-assistant/switch/[node name]-availability` as  availability_topic
1. Additional autodiscovery sensor indicates RA node availability , it has no availability_topic (always available) but uses `room-assistant/switch/[node name]-availability`  as `state_topic`

**To reproduce**
1. Configure RA with homeAssistant integration
2. power off the node or kill RA process

_Expected_
Sensors in HA are unavailable

_Actual_
Sensors in HA are available

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```text
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```yaml

bluetoothClassic:
    addresses:
    - 00:1D:A5:00:42:B4
    - 64:D4:BD:5E:7C:A7
    hciDeviceId: 1
    interval: 10
    scanTimeLimit: 8
    timeoutCycles: 3
bluetoothLowEnergy:
    hciDeviceId: 00:15:83:FC:AD:D3
    tagOverrides:
        c80f10525792:
            name: Car
        e0102a6895cd:
            measuredPower: -53
            name: knst_miband
    timeout: 301
    whitelist:
    - e0102a6895cd
    - c80f10525792
cluster:
    networkInterface: eth0
    peerAddresses:
    - 192.168.4.118:6425
    - 192.168.4.224:6425
global:
    instanceName: garage
    integrations:
    - homeAssistant
    - bluetoothClassic
    - bluetoothLowEnergy
homeAssistant:
    mqttUrl: mqtt://192.168.4.16:1883

```

**Expected behavior**

**Environment**
 - room-assistant version: 2.10.0
 - installation type:  NodeJS
 - hardware: Raspberry Pi 3b
 - OS: Linux
