### ISSUE TITLE
2.11.0 crashes in HA with BLE and Classic enabled

### ISSUE THREAD

**Issue by embcla** [mKeRix/room-assistant#316]
**Describe the bug**
an exception is thrown and the container quits

**To reproduce**
I have room-assistant running in supervised HA on debian, running on qemu.
TPLink bluetooth adapted connected to the VM.

**Relevant logs**

```
/usr/lib/node_modules/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/hci.js:100
    this._deviceId = this._socket.bindRaw(deviceId);
                                  ^
Error: EALREADY, Operation already in progress
    at Hci.init (/usr/lib/node_modules/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/hci.js:100:35)
    at Hci.pollIsDevUp (/usr/lib/node_modules/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/hci.js:115:14)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  errno: 114,
  code: 'EALREADY',
  syscall: 'bind'
}
```

**Relevant configuration**
```
global:
  instanceName: server
  integrations:
    - homeAssistant
    - bluetoothClassic
    - bluetoothLowEnergy
bluetoothClassic:
  addresses:
    - mac1
    - mac2
    - mac3
debug_level: verbose
cluster:
  autoDiscovery: false
  peerAddresses:
    - 'ip:6425'
bluetoothLowEnergy:
  processIBeacon: false
  whitelist:
    - mac4
    - mac5
    - mac2
  tagOverrides:
    mac2:
      name: my phone
    mac3:
      name: my watch


```

**Expected behavior**
That it would keep running with both integrations working.
Disabling BLE makes it work with the same configuration.

**Environment**
 - room-assistant version: 2.11.0
 - installation type: Hass.io
 - hardware: x86 QNAP NAS, running a debian VM
 - OS: Debian 

**Additional context**
