### ISSUE TITLE
Unable to start in docker on Pi 3

### ISSUE THREAD

**Issue by vkhurana** [mKeRix/room-assistant#318]
**Describe the bug**
Following the docker instructions for installation, the container fails to start up. Logs attached.

**To reproduce**
Steps required to reproduce the issue:
1. Install Rasbian on a Pi3
2. Install Docker
3. Install Docker-compose
4. Follow https://www.room-assistant.io/guide/quickstart-docker.html
5. Add a docker-compose.yml file
6. Start and monitor docker logs

**Relevant logs**
```text
room-assistant_app | *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
room-assistant_app | *** WARNING *** Please fix your application to use the native API of Avahi!
room-assistant_app | *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
room-assistant_app | *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
room-assistant_app | *** WARNING *** Please fix your application to use the native API of Avahi!
room-assistant_app | *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
room-assistant_app | 10/26/2020, 9:18:36 PM - info - IntegrationsModule: Loading integrations: bluetooth-low-energy, home-assistant
room-assistant_app | 10/26/2020, 9:18:39 PM - info - NestFactory: Starting Nest application...
room-assistant_app | 10/26/2020, 9:18:39 PM - error - ExceptionHandler: EAFNOSUPPORT, Address family not supported by protocol
room-assistant_app exited with code 1
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

docker-compose.yml
```yaml
version: '2'
services:
 room-assistant:
  image: mkerix/room-assistant
  container_name: "room-assistant_app"
  networks:
    - local
  volumes:
    - /var/run/dbus:/var/run/dbus
    - ./room-assistant:/room-assistant/config

networks:
  local:
    driver: bridge
```

local.yml
```yaml
global:
  instanceName: room1
  integrations:
    - bluetoothLowEnergy
    # - bluetoothClassic
    - homeAssistant

homeAssistant:
  mqttUrl: mqtt://something.mqtt.local:1883
  mqttOptions:
    username: user
    password: pwd
```

**Expected behavior**
It should start up :)

**Environment**
 - room-assistant version: docker:latest
 - installation type: Docker
 - hardware: Raspberry Pi 3
 - OS: Raspbian
