### ISSUE TITLE
Docker does not start with rpi zero w

### ISSUE THREAD

**Issue by dedalusjinja** [mKeRix/room-assistant#325]
**Describe the bug**

Tried installation with NodeJs and everything works. Tested with Docker and after the command docker-compose up no logs start.
pi @ raspberrypi: ~ / room-assistant $ docker-compose up
Creating roomassistant ... done
Attaching to roomassistant
pi @ raspberrypi: ~ / room-assistant $

**To reproduce**
Steps required to reproduce the issue.

Install Rasbian on a Pi3
Install Docker
Install Docker-compose
Follow https://www.room-assistant.io/guide/quickstart-docker.html
Add a docker-compose.yml file
Start and monitor docker logs

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```text
pi@raspberrypi:~/room-assistant $ docker-compose top
ERROR: Container 2682ff99179ca0dedb501131a10c6c189d4ade3d50de64802ce3901f7d94a14d is restarting, wait until the container is running

pi@raspberrypi:~/room-assistant $ docker container ls
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                            PORTS               NAMES
2682ff99179c        mkerix/room-assistant   "tini -- room-assist…"   45 minutes ago      Restarting (139) 46 seconds ago                       roomassistant
pi@raspberrypi:~/room-assistant $ 
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```yaml

version: '3'
services:
  room-assistant:
    container_name: roomassistant
    image: mkerix/room-assistant
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    network_mode: host
    command: --digResolver --verbose
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /home/pi/room-assistant/config:/room-assistant/config

```

**Environment**
 - room-assistant version: latest
 - installation type: Docker
 - hardware: Raspberry Pi Zero W
 - OS: Raspbian
