### ISSUE TITLE
Multiple "Home" events

### ISSUE THREAD

**Issue by yonz2** [mKeRix/room-assistant#326]
I am not sure if this is a Room or Home Assistant issue. So I'll start with RA:

When monitoring events from Room Assistant using Node-Red in Home Assistant, the **"Home"** (in my log: "raspi1") event is triggered every few seconds. However, if I move the Tag out of Range, only one **"not_home"** (Away) event is triggered. 

The issue is, that if i tie an action to this event, it keeps firing all the time (would not be nice e.g. for a light switch, it would be flickering all the time)

**Debug output fro Node-Red**

```text
30.10.2020, 19:29:24node: dbg_Allowed
sensor.589ec6203fb4_room_presence : msg.payload : string[6]
"raspi1"
30.10.2020, 19:29:26node: dbg_Allowed
sensor.589ec6203fb4_room_presence : msg.payload : string[6]
"raspi1"
30.10.2020, 19:29:27node: dbg_Allowed
sensor.589ec6203fb4_room_presence : msg.payload : string[6]
"raspi1"
30.10.2020, 19:29:32node: dbg_Allowed
sensor.589ec6203fb4_room_presence : msg.payload : string[6]
"raspi1"
30.10.2020, 19:29:33node: dbg_Allowed
sensor.589ec6203fb4_room_presence : msg.payload : string[6]
"raspi1"
30.10.2020, 19:29:34node: dbg_Allowed
sensor.589ec6203fb4_room_presence : msg.payload : string[6]
"raspi1"
30.10.2020, 19:29:36node: dbg_NotAllowed
sensor.589ec6203fb4_room_presence : msg.payload : string[8]
"not_home"
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```yaml
global:
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://hassio:1883'
  mqttOptions:
    username: mqtt
    password: Password
bluetoothLowEnergy:
  hciDeviceId: 0
  processIBeacon: false
  timeout: 5
  updateFrequency: 0
  maxDistance: 2
  whitelist:
    589ec6203fb4
    589ec600d54b
entities:
  behaviors:
    ble-589ec6203fb4:
      debounce:
        wait: 3
        maxWait: 6
```

**Expected behavior**
Both **"home"** and **"not_home"** events should trigger only once.

**Environment**
**Room Assistant**
 - room-assistant version:  2.11.2
 - installation type: NodeJS, 
 - hardware: Raspberry Pi Zero W
 - OS: Raspbian (Just did a dist-upgrade)

**Home Assistant**
 - Home Assistant: 0.117.1, 
 - OS: HassOS 4.15
 - Supervisor: 2020.10.0
 - Hardware: Raspberry 3B
 - Node-Red Addon: Version 7.2.7

**BLE Tags**
 - Gigaset G-Tag
 - Gigaset Keeper
