### ISSUE TITLE
MQTT connection issues

### ISSUE THREAD

**Issue by MaxIsMyName** [mKeRix/room-assistant#341]
While I had configured room-assistant to work with home-assistant, it wasn't working as expected with Bluetooth Classic so I removed the MQTT integration. 

Having reinstalled it, and set the login info, I am no longer able to see any events in Home Assistant.

In the logs I see MQTT messages going out:
```11/12/2020, 12:07:10 - debug - EntitiesService: Adding new entity status-cluster-size
11/12/2020, 12:07:10 - debug - HomeAssistantService: Registering entity room-assistant-living-room-pi-status-cluster-size under homeassistant/sensor/room-assistant/living-room-pi-status-cluster-size/config
11/12/2020, 12:07:10 - debug - EntitiesService: Adding new entity status-cluster-leader
11/12/2020, 12:07:10 - debug - HomeAssistantService: Registering entity room-assistant-living-room-pi-status-cluster-leader under homeassistant/sensor/room-assistant/living-room-pi-status-cluster-leader/config
11/12/2020, 12:07:10 - debug - HomeAssistantService: Sending new state 1 for room-assistant-living-room-pi-status-cluster-size
11/12/2020, 12:07:10 - debug - HomeAssistantService: Sending new state none for room-assistant-living-room-pi-status-cluster-leader
```

But when I go to home-assistant, in the entities list for example the living-room-cluster-leader is unavailable.

Here is the config for MQTT on room-assistant:
```yaml
global:
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.xxx:1883'
  mqttOptions:
    username: mqtt-user
    password: mqtt-pass
bluetoothLowEnergy:
  hciDeviceId: 0
  whitelist:
   - SOME_ID
```

Here's the config on home-assistant:
```yaml
logins:
  - username: mqtt-user
    password: mqtt-pass
anonymous: false
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
```

And these are the logs for MQTT, just as I restarted room-assistant:
```
1605183106: New connection from 192.168.1.133 on port 1883.
[INFO] found mqtt-user on local database
1605183107: New client connected from 192.168.1.133 as mqttjs_0617aa5d (p2, c1, k60, u'mqtt-user').
1605183117: Socket error on client mqttjs_0617aa5d, disconnecting.
1605183121: New connection from 192.168.1.133 on port 1883.
1605183121: New client connected from 192.168.1.133 as mqttjs_0f896051 (p2, c1, k60, u'mqtt-user').
1605183160: New connection from 172.30.32.1 on port 1883.
[WARN] Not found homeassistant on local database
1605183161: Socket error on client <unknown>, disconnecting.
1605183189: New connection from 172.30.32.1 on port 1883.
1605183189: Socket error on client <unknown>, disconnecting.
1605183191: New connection from 172.30.32.1 on port 1883.
1605183191: Socket error on client <unknown>, disconnecting.
1605183193: New connection from 172.30.32.1 on port 1883.
1605183193: Socket error on client <unknown>, disconnecting.
1605183197: New connection from 172.30.32.1 on port 1883.
1605183197: Socket error on client <unknown>, disconnecting.
1605183205: New connection from 172.30.32.1 on port 1883.
1605183205: Socket error on client <unknown>, disconnecting.
1605183221: New connection from 172.30.32.1 on port 1883.
1605183221: Socket error on client <unknown>, disconnecting.
1605183253: New connection from 172.30.32.1 on port 1883.
1605183253: Socket error on client <unknown>, disconnecting.
1605183317: New connection from 172.30.32.1 on port 1883.
1605183317: Socket error on client <unknown>, disconnecting.
``` 

I'm a little confused as this exact setup (I think), worked before. 

I'm on 2.13.0.beta1
