### ISSUE TITLE
ExceptionHandler: Cannot assign to read only property

### ISSUE THREAD

**Issue by dennyreiter** [mKeRix/room-assistant#366]
**Describe the bug**
Room Assistant no longer starts, it encounters an exception after loading the intergrations and while trying to start the Nest application

**To reproduce**
Install room-assistant and start.
**Relevant logs**
*** npm install ***
```
npm WARN @nestjs/mapped-types@0.1.1 requires a peer of class-transformer@^0.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nestjs/mapped-types@0.1.1 requires a peer of class-validator@^0.11.1 || ^0.12.0 but none is installed. You must install peer dependencies yourself.
```

*** room-assistant -v***
```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
11/25/2020, 12:08:53 PM - info - IntegrationsModule: Loading integrations: home-assistant, grid-eye
11/25/2020, 12:08:57 PM - info - NestFactory: Starting Nest application...
11/25/2020, 12:08:57 PM - error - ExceptionHandler: Cannot assign to read only property 'hasOwnProperty' of object '#<Object>'
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```
global:
  instanceName: mediaroom
  integrations:
    - homeAssistant
    - gridEye
homeAssistant:
  mqttUrl: 'mqtt://192.168.0.77:1883'
  mqttOptions:
    username: youruser
    password: yourpass
gridEye:
  deltaThreshold: 3
cluster:
  networkInterface: wlan0
  port: 6425
  quorum: 3

```

**Expected behavior**
Room Assistant was running, just with Grid-Eye but the response seemed slow. I did an upgrade and it started spewing unicode garbage characters out to MQTT.  After trying to downgrade to 2.10.1, Grid-Eye didn't seem to do anything.  I have uninstalled and reinstalled, even deleted /opt/nodejs to try and start fresh. The install does complain about missing peer dependencies for nestjs, which I install, but they don't seem to 'stick'

**Environment**
 - room-assistant version: 2.12.0
 - installation type: NodeJS
 - hardware: Raspberry Pi Zero W
 - OS: Linux

**Additional context**
