### ISSUE TITLE
Wrong reading of zero distance to ble device

### ISSUE THREAD

**Issue by KonstantinNosov** [mKeRix/room-assistant#369]
**Describe the bug**
I have 4 instances of room-assistant  with cluster set up.
Occasionally BLE device is reported to be near one of the instances. Distance is zero. And immediately devices returns to the correct room. Sample MQTT messages sequence:
```
room-assistant/sensor/ble-e0102a6895cd/attributes {"distance":0.3,"last_updated_at":"2020-11-26T21:39:29.589Z"}
room-assistant/sensor/ble-e0102a6895cd/state second_floor
room-assistant/sensor/ble-e0102a6895cd/attributes {"distance":0,"last_updated_at":"2020-11-26T21:39:29.618Z"}
room-assistant/sensor/ble-e0102a6895cd/state kitchen
room-assistant/sensor/ble-e0102a6895cd/attributes {"distance":0.3,"last_updated_at":"2020-11-26T21:39:30.717Z"}
room-assistant/sensor/ble-e0102a6895cd/attributes {"distance":0.2,"last_updated_at":"2020-11-26T21:39:31.893Z"}
```
Nether 'kitchen' nor 'second_floor' node was the cluster leader when messages above were sent. But I've observed the same while 'second_floor' node was the leader.

zero distance reading is definitely wrong as the 'second_floor' node in sample above is on another floor and has 2 walls and one ceiling between it and the device while 'kitchen' node is in 2m from he device without any obstacles
 

**Relevant configuration**

kitchen node:
```yaml
bluetoothClassic:
    addresses:
    - 00:1D:A5:00:42:B4
    - 64:D4:BD:5E:7C:A7
    - 70:1F:3C:55:82:76
    hciDeviceId: 0
    interval: 10
    scanTimeLimit: 8
    timeoutCycles: 3
bluetoothLowEnergy:
    hciDeviceId: 0
    maxDistance: 6
    processIBeacon: false
    tagOverrides:
        c80f10525792:
            name: Car
        e0102a6895cd:
            name: knst_miband
    timeout: 10
    whitelist:
    - e0102a6895cd
cluster:
    autoDiscovery: false
    networkInterface: wlan0
    peerAddresses:
    - 192.168.4.118:6425
    - 192.168.4.120:6425
    - 192.168.4.121:6425
    weight: 1
global:
    instanceName: kitchen
    integrations:
    - homeAssistant
    - bluetoothLowEnergy
    - bluetoothClassic
homeAssistant:
    mqttUrl: mqtt://192.168.4.16:1883

```

second floor node
```yaml
bluetoothClassic:
    addresses:
    - 00:1D:A5:00:42:B4
    - 64:D4:BD:5E:7C:A7
    - 70:1F:3C:55:82:76
    hciDeviceId: 0
    interval: 10
    scanTimeLimit: 8
    timeoutCycles: 3
bluetoothLowEnergy:
    hciDeviceId: 0
    maxDistance: 2
    processIBeacon: false
    tagOverrides:
        c80f10525792:
            name: Car
        e0102a6895cd:
            name: knst_miband
    timeout: 10
    whitelist:
    - e0102a6895cd
cluster:
    autoDiscovery: false
    networkInterface: eth0
    peerAddresses:
    - 192.168.4.118:6425
    - 192.168.4.119:6425
    - 192.168.4.121:6425
    weight: 1
global:
    instanceName: second_floor
    integrations:
    - homeAssistant
    - bluetoothLowEnergy
    - bluetoothClassic
homeAssistant:
    mqttUrl: mqtt://192.168.4.16:1883

```

**Expected behavior**
device is reported to be observed by the nearest node 

**Environment**
 - room-assistant version: 2.12.0
 - installation type:  NodeJS 
 - hardware:   Raspberry Pi Zero W 
 - OS:  Linux
