### ISSUE TITLE
BLE Beacon: Home Assistant Constantly Listing Different Rooms and Distances Despite Being Stationary

### ISSUE THREAD

**Issue by opnsrce** [mKeRix/room-assistant#455]
**Describe the bug**
Distance constantly jumping even though tracker is stationary and RA keeps bouncing me between rooms despite not moving

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

**Relevant configuration**

```yaml
all:
  hosts:
    'master-bedroom.local':
      room_assistant_config:
        global:
          instanceName: Master Bedroom
    'levi-office.local':
      room_assistant_config:
        global:
          instanceName: Levi's Office
    '192.168.11.15':
      room_assistant_config:
        global:
          instanceName: Garage
  vars:
    room_assistant_global_config:
      global:
        entities:
          behaviors:
            cc6ed3c0477e417b81e10a62d6504061-2-9999:
              rollingAverage:
                window: 30
              debounce:
                wait: 1
        integrations:
          - homeAssistant
          - bluetoothLowEnergy
      homeAssistant:
        mqttUrl: mqtt://192.168.11.38:1883
        mqttOptions:
          username: <username>
          password: <password
      bluetoothLowEnergy:
        whitelist:
          - cc6ed3c0477e417b81e10a62d6504061-2-9999
        tagOverrides:
          - cc6ed3c0477e417b81e10a62d6504061-2-9999:
            name: Levi's Tracker
```

```yaml
global:
  entities:
    behaviors:
      cc6ed3c0477e417b81e10a62d6504061-2-9999:
        rollingAverage:
          window: 30
        debounce:
          wait: 1
  instanceName: Living Room
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
bluetoothLowEnergy:
  tagOverrides:
    - cc6ed3c0477e417b81e10a62d6504061-2-9999:
      name: Levi's Tracker
  whitelist:
    - cc6ed3c0477e417b81e10a62d6504061-2-9999
homeAssistant:
  mqttOptions:
    password: <username>
    username: <password
    mqttUrl: 'mqtt://192.168.11.38:1883'

```

**Expected behavior**
Home assistant lists my room and distance consistently when I'm stationary

**Environment**
 - room-assistant version: `latest`
 - installation type: NodeJS + Home Assistant
 - hardware: Raspberry Pi, Zero W,
 - OS: Linux

**Additional context**

Here's what the issue looks like in HA. Occasionally, it will correctly list my distance of 0 (I'm inches from the Pi Zero W) but put me in the living room instead of the office. 

![demo](https://user-images.githubusercontent.com/1098790/104828502-e0e06e80-581e-11eb-9070-110d30b39069.gif)

I've checked the logs in the `levi's-office` Pi Zero W and consistently lists my distance as 0. So, I don't know where the other distance updates are coming from. I've tried updating the entity behaviors but nothing seems to work. I'm using Ansible for my deploys, except on the Living Room Instance because that's running on the same Raspberry Pi as my Home Assistant Instance. Additionally, I tried setting the `weight` of each node and the `quorum`

**Comment by mKeRix** [comment]
You've actually already done a lot of the things that would make sense for this issue, but I could think of two more:

- raise the bluetoothLowEnergy `timeout` to something higher (in case your instance misses some advertisements or has intermittent network troubles, which can happen on the Zero W due to the shared chip)
- set the `maxDistance` for your instances for additional fine tuning (requires some trial & error)

Another thing that could be insightful is looking at the detailed entity states in the [room-assistant API](https://www.room-assistant.io/guide/api.html) when this happens. Those will include the most recent received RSSI + calculated distances for each instance together with timestamps.

**Comment by opnsrce** [comment]
> You've actually already done a lot of the things that would make sense for this issue, but I could think of two more:
> 
> * raise the bluetoothLowEnergy `timeout` to something higher (in case your instance misses some advertisements or has intermittent network troubles, which can happen on the Zero W due to the shared chip)
> * set the `maxDistance` for your instances for additional fine tuning (requires some trial & error)
> 
> Another thing that could be insightful is looking at the detailed entity states in the [room-assistant API](https://www.room-assistant.io/guide/api.html) when this happens. Those will include the most recent received RSSI + calculated distances for each instance together with timestamps.

When setting max distance, do I have to redeclare the entire `bluetoothLowEnergy` config from the global settings? Or does RA merge the objects together when building the config?

**Comment by mKeRix** [comment]
The objects are merged, with the instance settings having higher priority than the global ones. The only thing you would need to redeclare completely are lists, as those can’t be merged safely.

**Comment by opnsrce** [comment]
Is there a way to query if a particular instance is acknowledging the `maxDistance` param?

```yaml
all:
  hosts:
    'master-bedroom.local':
      room_assistant_config:
        global:
          instanceName: Master Bedroom
    'levi-office.local':
      room_assistant_config:
        bluetoothLowEnergy:
          maxDistance: 2.5
        global:
          instanceName: Levi's Office
    '192.168.11.15':
      room_assistant_config:
        global:
          instanceName: Garage
  vars:
    room_assistant_global_config:
      global:
        entities:
          behaviors:
            cc6ed3c0477e417b81e10a62d6504061-2-9999:
              rollingAverage:
                window: 30
              debounce:
                wait: 1
        integrations:
          - homeAssistant
          - bluetoothLowEnergy
      homeAssistant:
        mqttUrl: mqtt://192.168.11.38:1883
        mqttOptions:
          username: <user>
          password: <pass>
      bluetoothLowEnergy:
        timeout: 10
        whitelist:
          - cc6ed3c0477e417b81e10a62d6504061-2-9999
        tagOverrides:
          cc6ed3c0477e417b81e10a62d6504061-2-9999:
            name: Levi's Tracker
```

I'm still seeing the distance jump around (but the room doesn't change). And it's jumping to values greater than the set max distance for the office.

**Comment by opnsrce** [comment]
After looking at the logs from the api:

```bash
[
  {
    "attributes": {},
    "id": "bluetooth-classic-inquiries-switch",
    "name": "Master Bedroom Bluetooth Inquiries",
    "distributed": false,
    "state": true
  },
  {
    "attributes": {
      "nodes": [
        "garage",
        "levi-s-office",
        "master-bedroom"
      ]
    },
    "id": "status-cluster-size",
    "name": "Master Bedroom Cluster Size",
    "distributed": false,
    "state": 3
  },
  {
    "attributes": {
      "quorumReached": true
    },
    "id": "status-cluster-leader",
    "name": "Master Bedroom Cluster Leader",
    "distributed": false,
    "state": "master-bedroom"
  },
  {
    "attributes": {},
    "id": "bluetooth-classic-f8-6f-c1-20-05-5e-tracker",
    "name": "Levi’s Apple Watch",
    "distributed": true,
    "state": true
  },
  {
    "attributes": {
      "distance": 0,
      "lastUpdatedAt": "2021-01-18T17:26:26.469Z"
    },
    "id": "bluetooth-classic-f8-6f-c1-20-05-5e",
    "name": "Levi’s Apple Watch Room Presence",
    "distributed": true,
    "distances": {
      "Levi's Office": {
        "lastUpdatedAt": "2021-01-18T17:26:26.469Z",
        "distance": 0,
        "outOfRange": false
      },
      "Master Bedroom": {
        "lastUpdatedAt": "2021-01-18T17:26:29.106Z",
        "distance": 17.5,
        "outOfRange": true
      },
      "Garage": {
        "lastUpdatedAt": "2021-01-18T17:26:22.715Z",
        "distance": 21.3,
        "outOfRange": true
      }
    },
    "timeout": 18,
    "state": "Levi's Office"
  }
]
```

If I'm reading this right, I should be listed as being in my office in HA. But, when I look at my stats in HA, I'm in the Living Room. Could this actually be a bug in Home Assistant?

**Comment by opnsrce** [comment]
The more I dig into this the more I think some of my issues are caused by the fact that my "living room" cluster size is 1 (itself) and the other nodes have a cluster size of 3 (everybody but the living room). I've added the `peerAddresses` config prop but that doesn't seem to do anything. Any idea of what the cause could be for the other nodes not recognizing "living room"? 

Living room is the one instance running on the HA Pi vs all the others being on Pi Zero Ws

**Comment by mKeRix** [comment]
In the Home Assistant add-on configuration, under "Network", is port 6425/udp mapped to port 6425 for you? This is the main communication port used by room-assistant and needs to be available so that the instances may communicate with each other. Depending on how you installed Home Assistant you could also check that your host machine doesn't block the port in the firewall or something (not required if you just use Home Assistant OS).

**Comment by opnsrce** [comment]
Unfortunately, I uninstalled the integration from my HA instance and haven't been able to reinstall it. When I go to add the custom repo `https://github.com/mKeRix/hassio-repo` to HACS, I get `Repostitory structure for master is not compliant`. So, I'm currently working on figuring out what the issue is.

**Comment by mKeRix** [comment]
I think you might be adding the URL to the wrong place - it is a Home Assistant add-on, not a custom integration that is installed via HACS. You can follow the link under Installation in the [README](https://github.com/mKeRix/hassio-repo#installation) to find the right place to put the link into.

**Comment by opnsrce** [comment]
Yep. I absolutely realized that and deleting my last comment :D

Checking the port stuff now.

**Comment by opnsrce** [comment]
![Screen Shot 2021-01-30 at 2 57 27 PM](https://user-images.githubusercontent.com/1098790/106370041-7eea3380-630b-11eb-9ae4-a9e611cc41a9.png)

It looks to be mapped properly. I'm running on a Raspberry pi via the latest Home Assistant OS image. I don't believe the host machine is blocking the port, but I'll also check my router.

**Comment by mKeRix** [comment]
Yeah, that looks good. I think on Home Assistant OS the auto discovery should even work, but if it doesn't the peer addresses should do the trick. In theory you could just provide it on the add-on instance... once it connects to the others they will exchange information. It could look like this:

```yaml
cluster:
  peerAddresses:
    - <pi1-ip>:6425
    - <pi2-ip>:6425
    - <pi3-ip>:6425
```

Just trying to make sure that there were no little indentation errors or something like that last time you tried.

**Comment by opnsrce** [comment]
```yaml
global:
  instanceName: Living Room
  cluster:
    peerAddresses: 
      - 192.168.11.19:6425  
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://192.168.11.38:1883'
  mqttOptions:
    username: <user>
    password: <pass>
bluetoothLowEnergy:
  whitelist:
    - cc6ed3c0477e417b81e10a62d6504061-2-9999
  tagOverrides:
    cc6ed3c0477e417b81e10a62d6504061-2-9999:
      name: Levi's Tracker
```

This is the config for the addon instance. `.19` is the IP of my "office" instance. Both of the cluster sizes for "office" and "living room" say `1`

**Comment by mKeRix** [comment]
The `cluster` block needs to be on top level, try it like this:

```yaml
global:
  instanceName: Living Room
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
cluster:
  peerAddresses: 
    - 192.168.11.19:6425  
homeAssistant:
  mqttUrl: 'mqtt://192.168.11.38:1883'
  mqttOptions:
    username: <user>
    password: <pass>
bluetoothLowEnergy:
  whitelist:
    - cc6ed3c0477e417b81e10a62d6504061-2-9999
  tagOverrides:
    cc6ed3c0477e417b81e10a62d6504061-2-9999:
      name: Levi's Tracker
```
