### ISSUE TITLE
The companion app is not detected

### ISSUE THREAD

**Issue by urechi** [mKeRix/room-assistant#481]
```
all:
  hosts:
    'living-room.local':
      ansible_user: pi
    'kitchen.local':
      ansible_user: pi
    'playroom.local':
      ansible_user: pi
    'guest-bedroom.local':
      ansible_user: pi
    'davids-bedroom.local':
      ansible_user: pi
  vars:
    room_assistant_version: v2.13.0-beta.6
    room_assistant_global_config:
      global:
        integrations:
          - homeAssistant
          - bluetoothLowEnergy
      homeAssistant:
        mqttUrl: mqtt://homeassistant.local:1883
        mqttOptions:
          username: mqtt
          password: ****************
      bluetoothLowEnergy:
        timeout: 60
        allowlist:
          - '84225A06-****-47FD-****-4CCA4B7A8517'
          - '1BAB4DFD-****-4D1E-****-FFA95E2A0DA3'
```

```
pi@living-room:~/room-assistant $ room-assistant -v
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
1/31/2021, 9:22:02 PM - info - IntegrationsModule: Loading integrations: home-assistant, bluetooth-low-energy
(node:1611) DeprecationWarning: You are using a version of Node.js that will reach EOL in April 2021. The support for this version will be dropped in 7.13. Please refer to https://ela.st/nodejs-support for additional information.
1/31/2021, 9:22:06 PM - info - NestFactory: Starting Nest application...
1/31/2021, 9:22:07 PM - info - InstanceLoader: AppModule dependencies initialized
1/31/2021, 9:22:07 PM - info - InstanceLoader: ConfigModule dependencies initialized
1/31/2021, 9:22:07 PM - info - InstanceLoader: NestEmitterModule dependencies initialized
1/31/2021, 9:22:07 PM - info - InstanceLoader: IntegrationsModule dependencies initialized
1/31/2021, 9:22:07 PM - info - InstanceLoader: HttpModule dependencies initialized
1/31/2021, 9:22:07 PM - info - InstanceLoader: DiscoveryModule dependencies initialized
1/31/2021, 9:22:07 PM - info - InstanceLoader: PrometheusModule dependencies initialized
1/31/2021, 9:22:07 PM - info - InstanceLoader: ClusterModule dependencies initialized
1/31/2021, 9:22:07 PM - info - InstanceLoader: TerminusModule dependencies initialized
1/31/2021, 9:22:07 PM - info - InstanceLoader: BluetoothModule dependencies initialized
1/31/2021, 9:22:07 PM - info - InstanceLoader: ScheduleModule dependencies initialized
1/31/2021, 9:22:07 PM - info - InstanceLoader: EntitiesModule dependencies initialized
1/31/2021, 9:22:07 PM - info - InstanceLoader: BluetoothLowEnergyModule dependencies initialized
1/31/2021, 9:22:07 PM - info - InstanceLoader: HomeAssistantModule dependencies initialized
1/31/2021, 9:22:07 PM - info - InstanceLoader: StatusModule dependencies initialized
1/31/2021, 9:22:11 PM - info - RoutesResolver: EntitiesController {/entities}:
1/31/2021, 9:22:11 PM - info - RouterExplorer: Mapped {/entities, GET} route
1/31/2021, 9:22:11 PM - info - RoutesResolver: StatusController {/status}:
1/31/2021, 9:22:11 PM - info - RouterExplorer: Mapped {/status, GET} route
1/31/2021, 9:22:11 PM - info - RoutesResolver: PrometheusController {/metrics}:
1/31/2021, 9:22:11 PM - info - RouterExplorer: Mapped {/metrics, GET} route
1/31/2021, 9:22:15 PM - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://homeassistant.local:1883
1/31/2021, 9:22:15 PM - info - ConfigService: Loading configuration from /opt/nodejs/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/living-room.yml
1/31/2021, 9:22:15 PM - debug - EntitiesService: Adding new entity status-cluster-size
1/31/2021, 9:22:15 PM - debug - HomeAssistantService: Registering entity room-assistant-living-room-status-cluster-size under homeassistant/sensor/room-assistant/living-room-status-cluster-size/config
1/31/2021, 9:22:15 PM - debug - EntitiesService: Adding new entity status-cluster-leader
1/31/2021, 9:22:15 PM - debug - HomeAssistantService: Registering entity room-assistant-living-room-status-cluster-leader under homeassistant/sensor/room-assistant/living-room-status-cluster-leader/config
1/31/2021, 9:22:15 PM - debug - HomeAssistantService: Sending new state 5 for room-assistant-living-room-status-cluster-size
1/31/2021, 9:22:15 PM - debug - HomeAssistantService: Sending new state davids-bedroom for room-assistant-living-room-status-cluster-leader
1/31/2021, 9:22:15 PM - info - ClusterService: Starting mDNS advertisements and discovery
1/31/2021, 9:22:15 PM - info - NestApplication: Nest application successfully started
noble warning: adapter state unauthorized, please run as root or with sudo
               or see README for information on running without root/sudo:
               https://github.com/sandeepmistry/noble#running-on-linux
1/31/2021, 9:22:15 PM - debug - BluetoothService: Adapter 0 went into state unauthorized
1/31/2021, 9:22:15 PM - debug - HomeAssistantService: Sending new attributes {"nodes":["playroom","guest-bedroom","davids-bedroom","kitchen","living-room"]} for room-assistant-living-room-status-cluster-size
1/31/2021, 9:22:15 PM - debug - HomeAssistantService: Sending new attributes {"quorumReached":true} for room-assistant-living-room-status-cluster-leader
1/31/2021, 9:22:45 PM - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting
1/31/2021, 9:22:45 PM - debug - BluetoothService: Resetting HCI adapter 0
1/31/2021, 9:22:50 PM - debug - BluetoothService: Adapter 0 went into state unauthorized
1/31/2021, 9:23:30 PM - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting
1/31/2021, 9:23:30 PM - debug - BluetoothService: Resetting HCI adapter 0
1/31/2021, 9:23:35 PM - debug - BluetoothService: Adapter 0 went into state unauthorized
1/31/2021, 9:24:15 PM - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting
1/31/2021, 9:24:15 PM - debug - BluetoothService: Resetting HCI adapter 0
1/31/2021, 9:24:20 PM - debug - BluetoothService: Adapter 0 went into state unauthorized
```

![IMG_2813](https://user-images.githubusercontent.com/38536263/106398677-30708e00-640c-11eb-8eaa-c7e447a1d524.PNG)
![IMG_0027](https://user-images.githubusercontent.com/38536263/106398679-32d2e800-640c-11eb-8dfe-1c488a5832e0.PNG)
![IMG_0026](https://user-images.githubusercontent.com/38536263/106398681-35354200-640c-11eb-98f8-415bc90ce9f5.PNG)

Any suggestion is very much appreciated.
