### ISSUE TITLE
BLE does not recognize room assistant companion app on iPhone

### ISSUE THREAD

**Issue by gadric** [mKeRix/room-assistant#483]
**Describe the bug**
I set up BLE with iPhone and room assistant companion app. Have configure everything according to the docs. However, the log states ` 2/1/2021, 3:40:28 PM - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting`

**To reproduce**
Steps required to reproduce the issue.

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```
2/1/2021, 3:40:28 PM - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting
2/1/2021, 3:41:13 PM - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting
2/1/2021, 3:41:58 PM - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```
global:
  instanceName: floor
  integrations:
    - homeAssistant
    - bluetoothClassic
    - bluetoothLowEnergy
cluster:
  autoDiscovery: false
  weight: 10
  port: <myport>
  peerAddresses:
    - 'xxx.xxx.xxx.xxx:<myport>'
    - 'yyy.yyy.yyy.yyy:<myport>'
homeAssistant:
  mqttUrl: 'mqtts://zzz.zzz.zzz.zzz:<mqttport>'
  mqttOptions:
    username: 
    password: 
    rejectUnauthorized: false
bluetoothClassic:
  hciDeviceId: 0
  interval: 20
  scanTimeLimit: 5
  timeoutCycles: 5
  minRssi: -30
  addresses:
    - '<btmac1>'
    - '<btmac2>'
bluetoothLowEnergy:
  hciDeviceId: 1
  timeout: 60
  allowlist:
	- <THE-DEVICE-ID-IN-THE-COMPANION-APP>
```

**Expected behavior**
The iPhone with BLE is been detected

**Environment**
 - room-assistant version: 2.13.0
 - installation type: Home Aisstant Addon
 - hardware: Intel NUC10i5, tested with built-in BT and external BT
 - OS: Debian 10 (buster), with backports and all updates. 

**Additional context**

**Comment by urechi** [comment]
Maybe check the last line of your config?

```
global:
  instanceName: floor
  integrations:
    - homeAssistant
    - bluetoothClassic
    - bluetoothLowEnergy
cluster:
  autoDiscovery: false
  weight: 10
  port: <myport>
  peerAddresses:
    - 'xxx.xxx.xxx.xxx:<myport>'
    - 'yyy.yyy.yyy.yyy:<myport>'
homeAssistant:
  mqttUrl: 'mqtts://zzz.zzz.zzz.zzz:<mqttport>'
  mqttOptions:
    username: 
    password: 
    rejectUnauthorized: false
bluetoothClassic:
  hciDeviceId: 0
  interval: 20
  scanTimeLimit: 5
  timeoutCycles: 5
  minRssi: -30
  addresses:
    - '<btmac1>'
    - '<btmac2>'
bluetoothLowEnergy:
  hciDeviceId: 1
  timeout: 60
  allowlist:
    - <THE-DEVICE-ID-IN-THE-COMPANION-APP>
```
Also could you run the two setcap commands mentioned [here](https://www.room-assistant.io/integrations/bluetooth-low-energy.html#requirements)?
