### ISSUE TITLE
Not loading allowlist (Home Assistant Docker)

### ISSUE THREAD

**Issue by IWShady** [mKeRix/room-assistant#486]
**Describe the bug**
I have installed the Home Assistant Addon of Room Assistant v2.13.0-beta6. I installed the companion app on my phone and put the generated ID from it into my config in the allowlist. When the addon restarts it says 

`2/1/2021, 11:05:56 AM - warn - BluetoothLowEnergyService: The allowlist and denylist are empty, no sensors will be created! Please add some of the discovered IDs below to your configuration.`

**To reproduce**
I am not sure if it is reproducible as it seems it may just be me. All I have done so far is created a basic config to just track my phone.

**Relevant logs**

```
2/1/2021, 11:05:56 AM - warn - BluetoothLowEnergyService: The allowlist and denylist are empty, no sensors will be created! Please add some of the discovered IDs below to your configuration.
```
**Relevant configuration**

```
global:
  instanceName: server_room
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
  bluetoothLowEnergy:
    timeout: 60
    allowlist:
      - THE ID FROM THE APP
    tagOverrides:
      THE ID FROM THE APP:
        name: Dads Phone
```

**Expected behavior**
I expected the allowlist to be loaded which would create a sensor within home assistant. 

**Environment**
 - room-assistant version: 2.13.0 beat-6
 - installation type: Hassio
 - hardware: NUC
 - OS: Home Assistant OS 5.10 (bare metal home assistant install using the NUC image)

**Additional context**
I do see the room assistant addon connecting to MQTT and it seems everything is loading except for the allowlist. I am not sure if this is a bug or if I am doing something wrong.

**Comment by officiallybob** [comment]
I can say that I'm getting similar results on my own setup up that I brought up this AM.  Running latest docker version (non-beta). I don't get the warning about the allowlist being empty, but when I watch the logs the behavior is the same as if I did not populate the allowlist. Just constantly monitoring and discovering BLE devices.

Here is my docker-compose:


```
services:
  room-assistant:
    image: mkerix/room-assistant
    container_name: Room-Assistant
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /home/pi/docker/room-assistant:/room-assistant/config
      - /etc/localtime:/etc/localtime:ro

```
      
      
      
And local.yml
  
  
```
global:
  instanceName: RA-LivingRoom
  integrations:
    - bluetoothLowEnergy
    - homeAssistant
bluetoothLowEnergy:
  timeout: 5
  processIBeacon: true
  allowlist:
    - UUIDOFBEACON
homeAssistant:
  mqttUrl: 'mqtt://XXX.XXX.XXX.XXX:1883'
  mqttOptions:
    username: XXXXXXX
    password: XXXXXXX
    rejectUnauthorized: false
```

**Comment by IWShady** [comment]
I installed the non beta version last night but am still seeing the error for the empty allowlist.

**Comment by mKeRix** [comment]
@IWShady The config you posted has the indentation a bit off, `bluetoothLowEnergy` needs to be on the top level. Try it like this:

```yaml
global:
  instanceName: server_room
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
bluetoothLowEnergy:
  timeout: 60
  allowlist:
    - THE ID FROM THE APP
  tagOverrides:
    THE ID FROM THE APP:
      name: Dads Phone
```

@officiallybob If you don't get the warning the config is picked up correctly! room-assistant will list new discoveries even with an allowlist or denylist in place, just to make your life a bit easier when adding new beacons to the ones you already configured. Could you maybe state your exact problem in a new issue?
