### ISSUE TITLE
BluetoothService: Did not detect any low energy advertisements in a while, resetting

### ISSUE THREAD

**Issue by danodemano** [mKeRix/room-assistant#494]
**Describe the bug**
The two pi zero w's I have setup seem to have a permissions issue with the bluetooth adapter. My pi 3 and 4 are working as expected. 

**To reproduce**
Deploy and watch the service status.

**Relevant logs**

```text
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
2/3/2021, 3:53:06 PM - info - IntegrationsModule: Loading integrations: home-assistant, bluetooth-low-energy
(node:2010) DeprecationWarning: You are using a version of Node.js that will reach EOL in April 2021. The support for this version will be dropped in 7.13. Please refer to https://ela.st/nodejs-support for additional information.
2/3/2021, 3:53:10 PM - info - NestFactory: Starting Nest application...
2/3/2021, 3:53:12 PM - info - InstanceLoader: AppModule dependencies initialized
2/3/2021, 3:53:12 PM - info - InstanceLoader: ConfigModule dependencies initialized
2/3/2021, 3:53:12 PM - info - InstanceLoader: NestEmitterModule dependencies initialized
2/3/2021, 3:53:12 PM - info - InstanceLoader: IntegrationsModule dependencies initialized
2/3/2021, 3:53:12 PM - info - InstanceLoader: HttpModule dependencies initialized
2/3/2021, 3:53:12 PM - info - InstanceLoader: DiscoveryModule dependencies initialized
2/3/2021, 3:53:12 PM - info - InstanceLoader: PrometheusModule dependencies initialized
2/3/2021, 3:53:12 PM - info - InstanceLoader: ClusterModule dependencies initialized
2/3/2021, 3:53:12 PM - info - InstanceLoader: TerminusModule dependencies initialized
2/3/2021, 3:53:12 PM - info - InstanceLoader: BluetoothModule dependencies initialized
2/3/2021, 3:53:12 PM - info - InstanceLoader: ScheduleModule dependencies initialized
2/3/2021, 3:53:12 PM - info - InstanceLoader: EntitiesModule dependencies initialized
2/3/2021, 3:53:12 PM - info - InstanceLoader: BluetoothLowEnergyModule dependencies initialized
2/3/2021, 3:53:12 PM - info - InstanceLoader: HomeAssistantModule dependencies initialized
2/3/2021, 3:53:12 PM - info - InstanceLoader: StatusModule dependencies initialized
2/3/2021, 3:53:16 PM - info - RoutesResolver: EntitiesController {/entities}:
2/3/2021, 3:53:16 PM - info - RouterExplorer: Mapped {/entities, GET} route
2/3/2021, 3:53:16 PM - info - RoutesResolver: StatusController {/status}:
2/3/2021, 3:53:16 PM - info - RouterExplorer: Mapped {/status, GET} route
2/3/2021, 3:53:16 PM - info - RoutesResolver: PrometheusController {/metrics}:
2/3/2021, 3:53:16 PM - info - RouterExplorer: Mapped {/metrics, GET} route
2/3/2021, 3:53:18 PM - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://192.168.9.200:1883
2/3/2021, 3:53:18 PM - info - ConfigService: Loading configuration from /opt/nodejs/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/ra-livingroom.yml
2/3/2021, 3:53:18 PM - debug - EntitiesService: Adding new entity status-cluster-size
2/3/2021, 3:53:18 PM - debug - HomeAssistantService: Registering entity room-assistant-ra-livingroom-status-cluster-size under homeassistant/sensor/room-assistant/ra-livingroom-status-cluster-size/config
2/3/2021, 3:53:18 PM - debug - EntitiesService: Adding new entity status-cluster-leader
2/3/2021, 3:53:18 PM - debug - HomeAssistantService: Registering entity room-assistant-ra-livingroom-status-cluster-leader under homeassistant/sensor/room-assistant/ra-livingroom-status-cluster-leader/config
2/3/2021, 3:53:18 PM - debug - HomeAssistantService: Sending new state 4 for room-assistant-ra-livingroom-status-cluster-size
2/3/2021, 3:53:18 PM - debug - HomeAssistantService: Sending new state octopi for room-assistant-ra-livingroom-status-cluster-leader
2/3/2021, 3:53:18 PM - info - ClusterService: Starting mDNS advertisements and discovery
2/3/2021, 3:53:18 PM - info - NestApplication: Nest application successfully started
noble warning: adapter state unauthorized, please run as root or with sudo
               or see README for information on running without root/sudo:
               https://github.com/sandeepmistry/noble#running-on-linux
2/3/2021, 3:53:19 PM - debug - BluetoothService: Adapter 0 went into state unauthorized
2/3/2021, 3:53:19 PM - debug - HomeAssistantService: Sending new attributes {"nodes":["genmon","octopi","ra-den","ra-livingroom"]} for room-assistant-ra-livingroom-status-cluster-size
2/3/2021, 3:53:19 PM - debug - HomeAssistantService: Sending new attributes {"quorumReached":true} for room-assistant-ra-livingroom-status-cluster-leader
2/3/2021, 3:53:19 PM - debug - EntitiesService: Adding new entity ble-426c7565436861726d426561636f6e73-3838-4949-tracker
2/3/2021, 3:53:19 PM - debug - HomeAssistantService: Registering entity room-assistant-ble-426c7565436861726d426561636f6e73-3838-4949-tracker under homeassistant/device_tracker/room-assistant/ble-426c7565436861726d426561636f6e73-3838-4949-tracker/config
2/3/2021, 3:53:19 PM - debug - EntitiesService: Adding new entity ble-426c7565436861726d426561636f6e73-3838-4949
2/3/2021, 3:53:19 PM - debug - HomeAssistantService: Registering entity room-assistant-ble-426c7565436861726d426561636f6e73-3838-4949 under homeassistant/sensor/room-assistant/ble-426c7565436861726d426561636f6e73-3838-4949/config
2/3/2021, 3:53:48 PM - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting
2/3/2021, 3:53:48 PM - debug - BluetoothService: Resetting HCI adapter 0
2/3/2021, 3:53:53 PM - debug - BluetoothService: Adapter 0 went into state unauthorized
2/3/2021, 3:54:33 PM - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting
2/3/2021, 3:54:33 PM - debug - BluetoothService: Resetting HCI adapter 0
2/3/2021, 3:54:38 PM - debug - BluetoothService: Adapter 0 went into state unauthorized

```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```yaml
all:
  hosts:
    #Pi Zero Only RoomAssistant
    '192.168.9.230':
      ansible_user: pi
      ansible_password: <password>
      ansible_sudo_pass: <password>
      name: living_room
      instanceName: living_room
    #Pi Zero Only RoomAssistant
    '192.168.9.231':
      ansible_user: pi
      ansible_password: <password>
      ansible_sudo_pass: <password>
      name: den
      instanceName: den
    #Octoprint
    '192.168.9.33':
      ansible_user: pi
      ansible_password: <password>
      ansible_sudo_pass: <password>
      name: ante_chamber
      instanceName: ante_chamber
    #Genmon
    '192.168.9.219':
      ansible_user: pi
      ansible_password: <password>
      ansible_sudo_pass: <password>
      name: basement
      instanceName: basement
  vars:
    room_assistant_version: latest
    room_assistant_global_config:
      global:
        cluster:
          autoDiscovery: true
          port: 6425
        integrations:
          - homeAssistant
          - bluetoothLowEnergy
      homeAssistant:
        mqttUrl: 'mqtt://192.168.9.200:1883'
      bluetoothLowEnergy:
        timeout: 30
        allowlist:
          - '426c7565436861726d426561636f6e73-3838-4949'
```

**Expected behavior**
Adapter should be able to be used and devices be tracked.

**Environment**
 - room-assistant version: (Unsure how to get this with the Ansible deployment - should be the latest)
 - installation type: Ansible 
 - hardware: Raspberry Pi Zero W
 - OS: Raspbian

**Additional context**
I had manually deployed on a pi zero w which did work. These were brand new Raspbian deployments, only wifi and SSH had been configured and the systems updated. Thanks!
