### ISSUE TITLE
Room Assistant 2.13 and node v14.13.0

### ISSUE THREAD

**Issue by casaerreti** [mKeRix/room-assistant#515]
**Describe the bug**
Installed, do not start

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```
8/2/2021, 16:13:26 - info - NestApplication: Nest application successfully started
/usr/local/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/hci-socket/hci.js:107
        throw e;
        ^

Error: ENODEV, No such device
    at Hci.init (/usr/local/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/hci-socket/hci.js:102:37)
    at NobleBindings.init (/usr/local/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/hci-socket/bindings.js:111:13)
    at /usr/local/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/noble.js:60:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  errno: 19,
  code: 'ENODEV',
  syscall: 'bind'
}
```

**Relevant configuration**

```yaml
global:
  instanceName: Living Room
  integrations:
    - homeAssistant
#    - bluetoothClassic
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.232:1883'
  mqttOptions:
    username: mqtt_user
    password: cz4jh7P3QeX
#bluetoothClassic:
#  addresses:
#    - 84:B5:41:49:A5:B5
bluetoothLowEnergy:
  timeout: 60
  whitelist:
    - c5635f9f0d84
    - a0bb3eafdd8c
  tagOverrides:
    c5635f9f0d84:
      name: Fabio Xiaomi Smart Band
    a0bb3eafdd8c:
      name: FILO TAG 1
```

**Environment**
 - room-assistant version: 2.13
 - installation type: NodeJs
 - hardware: Rpi 1 rev B
 - OS: Raspberry Pi OS

**Additional context**
Installed all the system from scratch. No luck into starting room-assistant
