### ISSUE TITLE
Unhandled Rejection Promise Warning 

### ISSUE THREAD

**Issue by bsmith76s** [mKeRix/room-assistant#534]
Running on a Pi0W node version 14.13.0 and npm version 6.14.8 
Having a hard time getting room-assistant started. This is what I get when I try to start room-assistant using bluetoothLow Energy config. 
```
global:
  instanceName: familyroom
  integrations:
    - bluetoothLowEnergy
    - homeAssistant
bluetoothLowEnergy:
  hciDeviceId: 0
  allowlist:
    - Mac no dash
homeAssistant:
  mqttUrl: 'mqtt://ip.of.mqtt:1883'
  mqttOptions:
    username: user
    password: password
cluster:
  autoDiscovery: false
  networkInterface: eth0
  peerAddresses:
    - ip.of.2nd.pi:6425
```

2/11/2021, 7:25:43 AM - debug - BluetoothService: Adapter 0 went into state poweredOn
2/11/2021, 7:25:43 AM - debug - BluetoothService: Starting scanning for BLE peripherals on adapter 0
2/11/2021, 7:25:43 AM - debug - BluetoothService: Started scanning for BLE peripherals on adapter 0
2/11/2021, 7:25:43 AM - info - BluetoothLowEnergyService: Discovered new BLE peripheral Mac no dash with ID Mac no dash and RSSI -59
(node:1358) UnhandledPromiseRejectionWarning: TypeError: x.toLowerCase is not a function
    at /usr/local/lib/node_modules/room-assistant/dist/integrations/bluetooth-low-energy/bluetooth-low-energy.service.js:171:38
    at Array.map (<anonymous>)
    at BluetoothLowEnergyService.isOnAllowlist (/usr/local/lib/node_modules/room-assistant/dist/integrations/bluetooth-low-energy/bluetooth-low-energy.service.js:171:25)
    at BluetoothLowEnergyService.handleDiscovery (/usr/local/lib/node_modules/room-assistant/dist/integrations/bluetooth-low-energy/bluetooth-low-energy.service.js:91:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1358) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

This error just keeps repeating with increasing rejection id, I'm not sure what to do. I have uninstalled and reinstalled many times over. same issue.

configuration 

`global:
  instanceName: familyroom
  integrations:
    - bluetoothLowEnergy
    - homeAssistant
bluetoothLowEnergy:
  hciDeviceId: 0
  allowlist:
    - 195221221219
homeAssistant:
  mqttUrl: 'mqtt://10.10.51.10:1883'
  mqttOptions:
    username: smithmqtt
    password: SmithHome967!
cluster:
  autoDiscovery: false
  networkInterface: eth0
  peerAddresses:
    - 10.10.51.9:6425`
