### ISSUE TITLE
"allowlist is empty" warning when it isn't empty

### ISSUE THREAD

**Issue by markturner** [mKeRix/room-assistant#548]
**Describe the bug**
Using BLE integration, I have added a couple of devices to the allowlist, but room assistant still warns that allowlist is empty, and doesn't create entities for them. I've tried rebooting the pi this is running on but it doesn't make a difference.

**To reproduce**
Add devices to allowlist, run `room-assistant`command

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```text
warn - BluetoothLowEnergyService: The allowlist and denylist are empty, no sensors will be created! Please add some of the discovered IDs below to your configuration.
```

**Relevant configuration**
Here is my config file, with two devices in the allowlist, one is the companion ios app:

```yaml
global:
  instanceName: downstairs
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.84:1883'
  mqttOptions:
    username: homeassistant
    password: <password>
blueoothLowEnergy:
  hciDevice: 0
  timeout: 60
  allowlist:
    - B8CC4A37-E943-4236-8281-EA49F42DB5D5
    - f018983bd243
```

**Expected behavior**
These devices should be recognised, no warning about empty allowlist

**Environment**
 - room-assistant version: 2.13.1
 - installation type: NodeJS
 - hardware:Raspberry Pi Zero W
 - OS: raspi linux
