### ISSUE TITLE
not_home persists when new distances set

### ISSUE THREAD

**Issue by Alfiegerner** [mKeRix/room-assistant#562]
**Describe the bug**
Hi, I'm trying to work through some not_homes I'm getting with the HomeAssistant android app feature I've done.

One of the things I've noticed is that not_home can persist even if new distances are reported as attributes.

I've replicated this with a smaller set of instance than I normally run, 4 instead of 9 and watched it with all 4 instances in debug with only 1 'sending' attributes.

Here is  a view from HA which shows attributes changing (from 5.4 to 6.4 , 6.3 and back to 6.4 again): 
https://photos.app.goo.gl/4PDQhNZw5sSqVXoFA

Here is a view from MQTT Explorer where we can see attributes (i.e. distance) changing:
![image](https://user-images.githubusercontent.com/596188/109371490-0ececd80-790a-11eb-9558-4deeb09a0d0c.png)

For the same period from MQTT Explorer we can see state has been set as not_home:
![image](https://user-images.githubusercontent.com/596188/109371533-45a4e380-790a-11eb-89c9-af8919dead42.png)

I'll gather logs to attach as well.
**To reproduce**
Steps required to reproduce the issue.

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.
Will attach logs.
```text
```

**Relevant configuration**
Paste the relevant parts of your configuration below.
Ansible host.yml:
```yaml
all:
  hosts:
# pi zero parents bedroom
    '192.168.86.91':
      room_assistant_config:
        global:
          instanceName: parents_bedroom
        cluster:
          weight: 1
#laptop office
    '192.168.86.106':
       room_assistant_config:
         global:
           instanceName: office
         cluster:
           weight: 100
#pi 3b black
    '192.168.86.44':
      room_assistant_config:
        global:
          instanceName: kitchen
        cluster:
          weight: 9
#pi zero bathroom
    '192.168.86.231':
       room_assistant_config:
         global:
           instanceName: bathroom
         cluster:
           weight: 2
  vars:
    ansible_user: pi
    room_assistant_version: "{{ version }}"
    room_assistant_global_config:
      global:
        instanceName: home
        integrations:
          - homeAssistant
          - bluetoothLowEnergy
      cluster:
        autodiscovery: false
        quorum: 3
        peerAddresses:
          - 192.168.86.91:6425
          - 192.168.86.106:6425
          - 192.168.86.44:6425
          - 192.168.86.231:6425
      bluetoothLowEnergy:
        processIBeacon: true
        timeout: 60
        whitelist:
          - .*-100-.*
        whitelistRegex: true
      homeAssistant:
        mqttUrl: mqtt://192.168.86.106:1883
        mqttOptions:
          username: homeassistant
          password: home_pa555
```

**Expected behavior**
not_homes to not persist if distance attribute is being updated.

**Environment**
 - room-assistant version: 2.13.1
 - installation type: nodeJS
 - hardware: Laptop, pi 3b, pi zero
 - OS: Linux

**Additional context**
