### ISSUE TITLE
Unable to create a cluster with two nodes

### ISSUE THREAD

**Issue by brunolinsalves** [mKeRix/room-assistant#570]
**Describe the bug**
Hi,

I am unable to create a cluster of room-assistant with two nodes (rpi3-hassio and rpi0w-docker). 
no matter what I do, it create two clusters with one node each.
The both nodes are on the same network (192.168.68.123 and 192.168.68.145, netmask 255.255.255.0) and there is no firewall between them. I use a tplink deco m5 router. I can ping to each other.

Please, someone can help me ? What am I doing wrong ?

Ps: I followed some youtube tutorials, exactly as it is, and it is not working.

**To reproduce**

...

**Relevant logs**

I snapshot the logs and attached in this thread.

**Relevant configuration**

On the rpi3, that uses hassio, the config is: 

```
global:
  cluster:
    autoDiscovery: false
    port: 6425
    peerAddresses:
      - 192.168.68.145:6425
  instanceName: livingroom
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.68.123:1883'
  mqttOptions:
    username: password
    password: password
bluetoothClassic:
  minRssi: -20
  hciDeviceId: 0 
  addresses:
    - 'XX:XX:XX:XX:XX:XX'
    - 'XX:XX:XX:XX:XX:YY'
```

On the rpi0, that uses docker, the config is: 

```
global:
  cluster:
    autoDiscovery: false
    networkInterface: wlan0
    port: 6425
    peerAddresses:
      - 192.168.68.123:6425
  instanceName: bedroom
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.68.123:1883'
  mqttOptions:
    username: user
    password: password
bluetoothClassic:
  minRssi: -20
  hciDeviceId: 0
  addresses:
    - 'XX:XX:XX:XX:XX:XX'
    - 'XX:XX:XX:XX:XX:YY'
```

**Expected behavior**

I would expect only onde cluster, with two nodes. But, instead, I got two clusters with only one node...

**Environment**
 - room-assistant version: 2.14.0
 - installation type: rpi3-Hass.io and rpi0w-Docker
 - hardware: Raspberry Pi3 and Raspberry Pi Zero W
 - OS: HassioOS and Raspbian OS

**Additional context**

Attached logs from both nodes and a snapshot of mqttexplorer

<img width="719" alt="rpi 3 - hassio" src="https://user-images.githubusercontent.com/209446/109978831-08ab6900-7cdd-11eb-8b7f-7364ca216264.png">

<img width="946" alt="rpi 0" src="https://user-images.githubusercontent.com/209446/109978826-077a3c00-7cdd-11eb-9265-33f7a06da77f.png">

<img width="752" alt="mqttexplorer" src="https://user-images.githubusercontent.com/209446/109979195-6475f200-7cdd-11eb-917b-b6a755b46570.png">

**Comment by mKeRix** [comment]
I think your main problem is that your `cluster` block is nested, while it should be on top level. Try to re-write your configs so that they look like this:

```yaml
global:
  instanceName: livingroom
  integrations:
    - homeAssistant
    - bluetoothClassic
cluster:
  autoDiscovery: false
  port: 6425
  peerAddresses:
    - 192.168.68.145:6425
```
