### ISSUE TITLE
bluetoothClassic looks not working

### ISSUE THREAD

**Issue by LucasJanin** [mKeRix/room-assistant#582]
**Describe the bug**
BluetoothClassic looks not working.
No issue with bluetoothLowEnergy (iPhone 11 + iOS RoomAssistant app)
For now, I have only one instance (testing phase)

**To reproduce**
Just starting Room Assistant Docker and check log + MQTT via MQTT Explorer

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

The only reference to bluetoothClassic in my log is:
```
3/7/2021, 5:17:11 PM - info - IntegrationsModule: Loading integrations: home-assistant, bluetooth-classic, bluetooth-low-energy
3/7/2021, 5:17:12 PM - info - InstanceLoader: BluetoothClassicModule dependencies initialized
```
I have many logs for BluetoothLowEnergy:
```
3/7/2021, 10:49:08 PM - info - BluetoothLowEnergyService: Discovered companion app with ID XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXXX for tag YYYYYYYYYY
3/7/2021, 10:52:42 PM - info - BluetoothLowEnergyService: Discovered new BLE peripheral ZZZZZZZ with ID VVVVVVVVVV and RSSI -84
```

**Relevant configuration**
My docket config

```
sudo docker run -d \
--name=room-assistant \
--net=host \
--restart always \
--volume /var/run/dbus:/var/run/dbus \
--volume /home/pi/Docker/room-assistant/config:/room-assistant/config \
-e "TZ=America/Montreal" \
--cap-add=NET_ADMIN \
mkerix/room-assistant:latest
```
Config file:
```yaml
global:
  instanceName: Basement
  integrations:
    - homeAssistant
    - bluetoothClassic
    - bluetoothLowEnergy

homeAssistant:
  mqttUrl: 'mqtt://192.168.1.xxx:1883'

bluetoothClassic:
  adresses:
    - 'XX:XX:XX:XX:XX:XX' # Apple Watch
    - 'XX:XX:XX:XX:XX:XX' # iPad

bluetoothLowEnergy:
  allowlist:
    - XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXXX # iPhone
```

**Expected behavior**
See the bluetoothClassic, like the bluetoothLowEnergy

**Environment**
 - room-assistant version: 2.14.0
 - installation type: Docker
 - hardware: Raspberry Pi 4
 - OS: Linux
