### ISSUE TITLE
BLE iBeacon Not Working After Upgrade to v2.14

### ISSUE THREAD

**Issue by AML225** [mKeRix/room-assistant#586]
**Describe the bug**
After updating to Room-Assistant v2.14 BLE iBeacon now longer shows up in API, however MQTT/Home Assistant reports device tracker as last known state "Home" and sensor as last known room, even when iBeacon is not home. No configuration changes were made.

**To reproduce**
Updated all three RPI Zero W NPMs, NodeJS, and Room-Assistant

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```
pi@livingroom:~ $ room-assistant -v
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
09/03/2021, 01:10:24 - info - IntegrationsModule: Loading integrations: none
09/03/2021, 01:10:27 - info - NestFactory: Starting Nest application...
09/03/2021, 01:10:28 - info - InstanceLoader: AppModule dependencies initialized
09/03/2021, 01:10:28 - info - InstanceLoader: ConfigModule dependencies initialized
09/03/2021, 01:10:28 - info - InstanceLoader: NestEmitterModule dependencies initialized
09/03/2021, 01:10:28 - info - InstanceLoader: IntegrationsModule dependencies initialized
09/03/2021, 01:10:28 - info - InstanceLoader: HttpModule dependencies initialized
09/03/2021, 01:10:28 - info - InstanceLoader: DiscoveryModule dependencies initialized
09/03/2021, 01:10:28 - info - InstanceLoader: PrometheusModule dependencies initialized
09/03/2021, 01:10:28 - info - InstanceLoader: ClusterModule dependencies initialized
09/03/2021, 01:10:28 - info - InstanceLoader: TerminusModule dependencies initialized
09/03/2021, 01:10:28 - info - InstanceLoader: ScheduleModule dependencies initialized
09/03/2021, 01:10:28 - info - InstanceLoader: EntitiesModule dependencies initialized
09/03/2021, 01:10:28 - info - InstanceLoader: StatusModule dependencies initialized
09/03/2021, 01:10:31 - info - RoutesResolver: EntitiesController {/entities}:
09/03/2021, 01:10:31 - info - RouterExplorer: Mapped {/entities, GET} route
09/03/2021, 01:10:31 - info - RoutesResolver: StatusController {/status}:
09/03/2021, 01:10:31 - info - RouterExplorer: Mapped {/status, GET} route
09/03/2021, 01:10:31 - info - RoutesResolver: PrometheusController {/metrics}:
09/03/2021, 01:10:31 - info - RouterExplorer: Mapped {/metrics, GET} route
09/03/2021, 01:10:31 - info - ConfigService: Loading configuration from /opt/nodejs/lib/node_modules/room-assistant/dist/config/definitions/default.js
09/03/2021, 01:10:31 - warn - ConfigService: No configuration found in /home/pi/config
09/03/2021, 01:10:31 - debug - EntitiesService: Adding new entity status-cluster-size
09/03/2021, 01:10:31 - debug - EntitiesService: Adding new entity status-cluster-leader
09/03/2021, 01:10:32 - info - ClusterService: Starting mDNS advertisements and discovery
09/03/2021, 01:10:32 - info - NestApplication: Nest application successfully started
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::6415
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at ExpressAdapter.listen (/opt/nodejs/lib/node_modules/room-assistant/node_modules/@nestjs/platform-express/adapters/express-adapter.js:45:32)
    at NestApplication.listen (/opt/nodejs/lib/node_modules/room-assistant/node_modules/@nestjs/core/nest-application.js:149:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 6415
}
```

**Relevant configuration**

All three instances have the same config, only differences are peer addresses and cluster weighting. 
```
global:
  cluster:
    autoDiscovery: false
    networkInterface: wlan0
    port: 6425
    peerAddresses:
      - 192.168.1.24:6425
      - 192.168.1.31:6425
    weight: 99
    quorum: 2
  instanceName: livingroom
  integrations:
    - homeAssistant
    - bluetoothClassic
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.9:1883'
  mqttOptions:
    username: mqtt_user
    password: <password>
bluetoothClassic:
  addresses:
    - 'A0:FB:C5:DB:19:65'
    - 'B4:56:E3:CA:E1:81'
bluetoothLowEnergy:
  whitelist:
    - 7777772E6B6B6D636E2E636F6D000001-0-0
  onlyIBeacon: true
  timeout: 60
entities:
  behaviors:
    ble-7777772e6b6b6d636e2e636f6d000001-0-0-tracker:
      debounce:
        wait: 5
        maxWait: 10
      rollingAverage:
        window: 10
```

**Expected behavior**
Prior to updating NPM, NodeJs, and Room-Assistant BLE and Bluetooth Classic devices were working as expected. No other configuration changes were made. 

**Environment**
 - room-assistant version: v2.14
 - installation type: NodeJS
 - hardware: 3x RPI Zero Ws
 - OS: Raspbian

**Additional context**
Confirmed iBeacon still works with "KBeacon" app on iPhone. Setup was stable for several weeks prior to updating to v2.14. 

Commands used to update RPis (can't remember exact order I did this in):
```
npm install -g npm@7.6.1
wget -O - https://gist.githubusercontent.com/mKeRix/88b7b81e9bca044f74de1dc51696efb2/raw/799a20bca44cc61d8f8ae93878f2f28af8365a69/getNodeLTS.sh | bash
sudo npm i --global --unsafe-perm room-assistant
```
