### ISSUE TITLE
Configuration file with docker

### ISSUE THREAD

**Issue by thundergreen** [mKeRix/room-assistant#59]
How can i modify the configuration file when I run docker ?

**Comment by thundergreen** [comment]
Sorry I am dumb.. could you just give me a small writeup how to do this? Sorry for this noob question but i am absolutely new to docker.. How would a config file look like anbd how to use the env variable..

Help is reaaallyy appreciated :)

**Comment by mKeRix** [comment]
I think the easiest way would be using docker-compose, then you just need to create file called `docker-compose.yml` like this in a folder somewhere on your machine:

```yml
version: '2'
services:
  room-assistant:
    image: mkerix/room-assistant:latest-arm32
    restart: always
    network_mode: host
    environment:
      SERVICES: mqtt,ble
      ROOM: your-room-name
      MQTT_URL: mqtt://127.0.0.1
      MQTT_USERNAME: username
      MQTT_PASSWORD: password
```

Then navigate to that folder in your command line and run `docker-compose up`.

Alternatively you can also run room-assistant without creating that config file directly from the command line:

```bash
docker run --network=host --restart=unless-stopped -d --name room-assistant -e SERVICES=mqtt,ble -e ROOM=your-room-name -e MQTT_URL=mqtt://127.0.0.1 -e MQTT_USERNAME=username -e MQTT_PASSWORD=password mkerix/room-assistant:latest-arm32
```

This config gets you started with what you need for detecting presence around your house using Docker and a Raspberry Pi. Make sure to replace all the sample values with the stuff you need. If you're not running on a Raspberry Pi remove the `-arm32` from the image name. For all the other settings check the [wiki](https://github.com/mKeRix/room-assistant/wiki/Configuration) or ask again in here. :)
