### ISSUE TITLE
ConfigService error on 2.15.0

### ISSUE THREAD

**Issue by balonchiks** [mKeRix/room-assistant#599]
**Describe the bug**
Since upgrade to 2.15.0 i noticed this in the logs: `ConfigService: "global.cluster" is not allowed`. Same config works without issues in previous versions so looks like it is introduced in 2.15.0. Also, looks like room-assistant is still working fine even with this error, so it might be that the issue does not affect it and is only a warning.

**To reproduce**
start room assistance with the cluster: in the config

**Relevant logs**
`- error - ConfigService: "global.cluster" is not allowed [Value: {"autoDiscovery":false,"networkInterface":"eth0","port":6425,"peerAddresses":["xxx","xxx"],"weight":20}].`

**Relevant configuration**
Paste the relevant parts of your configuration below.

```
global:
  cluster:
    autoDiscovery: false
    networkInterface: eth0
    port: 6425
    peerAddresses:
      - xxxx:6425
      - xxxx:6425
    weight: 20
  instanceName: xxxx
  integrations:
    - homeAssistant
    - bluetoothClassic
    - mqtt
```

**Environment**
 - room-assistant version: **2.15.0**
 - installation type: [e.g. NodeJS, Docker, Hass.io] **docker**
 - hardware: [e.g. Raspberry Pi Zero W, NUC] **Pi Zero W**
 - OS: [e.g. Linux, Windows, macOS] **Linux**
