### ISSUE TITLE
Message on console: hci0 advertising data length corrected

### ISSUE THREAD

**Issue by hvorragend** [mKeRix/room-assistant#600]
**Describe the bug**
I am having a huge amount of these lines in my HomeAssistant host:

`hci0 advertising data length corrected`

**To reproduce**
Just open a SSH session. 

**Relevant logs**
No relevant logs. Just these messages. 

**Relevant configuration**
I am using two Gigaset GTags. 
And a CSL Bluetooth dongle. 

```
global:
  instanceName: hwr
  integrations:
    - bluetoothLowEnergy
    - homeAssistant
bluetoothLowEnergy:
  timeout: 60
  updateFrequency: 60
  allowlist:
  - 'xxxx'
  - 'xxxx'
  
```

**Expected behavior**
No dmesg output. I cannot use the bash. Login not possible. 

**Environment**
 - room-assistant version: Current version: 2.13.0-beta.6 
 - installation type: HassOS
 - hardware: amd64 in Proxmox PVE
 - OS: HassOS

**Additional context**
none
