### ISSUE TITLE
state of bluetoothLowEnergy is not reported in MQTT

### ISSUE THREAD

**Issue by balonchiks** [mKeRix/room-assistant#604]
**Describe the bug**
Since some time ago, the state of the `bluetoothLowEnergy` sensors is not reported in MQTT which leads to incorrect state in home assistance. this has been working fine for a couple of weeks, and only started being like this recently. i've tried reverting back to 2.13.0 with no luck and exactly the same behaviour. See the image below, only `status` is reported, but not `state`.

![image](https://user-images.githubusercontent.com/31212478/111447484-c4bd5880-870d-11eb-93da-475c45f4dc6d.png)

the `bluetoothClassic` sensors do work as intended and the state is being reported correctly:

![image](https://user-images.githubusercontent.com/31212478/111447671-f2a29d00-870d-11eb-91e5-29e332d3f9c5.png)

It is also worth mentioning that in the API the state is reported correctly for both my `bluetoothLowEnergy` devices, so it must have been something with publishing the state to mqtt.

i am using the latest (2.15.0) version with the `homeAssistant` integration and not using the `mqtt` integration as i don't need it and the `homeAssistant` one has been working fine.

It is worth mentioning that i am using `bluetoothLowEnergy` on a different `hciDevice` than the `bluetoothClassic` integration.

I have tried deleting the 'ble-' topics from MQTT, restarting MQTT and so on with no luck, the sensors are being recreted but the 'state' is not being published.

Is there something that I am doing wrong? Thank you!

**Relevant configuration**
Paste the relevant parts of your configuration below.

```
homeAssistant:
  mqttUrl: 'mqtt://x.x.x.x.:1883'
  mqttOptions:
    username: roomassistant-corridor
bluetoothLowEnergy:
  hciDeviceId: 1
  timeout: 30
  updateFrequency: 8
  allowlist:
    - 6E178B6A-064D-485E-8053-A713908A177C
    - fda50693a4e24fb1afcfc6eb07647825-12321-23432
```

**Environment**
 - room-assistant version: 2.15.0
 - installation type: Docker
 - hardware: Raspberry Pi Zero W
