### ISSUE TITLE
Error on startup - cannot read property 'address'of undefined

### ISSUE THREAD

**Issue by riddledaxis** [mKeRix/room-assistant#622]
**Describe the bug**
I had to replace 1 of my Pi Zero's that I was running in a cluster, and when I went to recreate the cluster after replacing the Pi Zero W, this issue occured on the Pi 3b+. 

Thought it might be because the new Pi Zero W was running a newer version of RA, so upgraded the Pi 3b+ to version 2.15.1 and reapplied the Bluetooth permissions. 

But I am still getting the error.

The 2 Pi Zero W's are working fine with the same config apart from their instance name and peerAddresses, so not sure what the issue is?

**To reproduce**
I initially restarted the service and this error occurred, so I manually ran with room-assistant -v to see what was happening

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
3/26/2021, 13:49:06 - info - IntegrationsModule: Loading integrations: home-assistant, bluetooth-low-energy
3/26/2021, 13:49:07 - info - NestFactory: Starting Nest application...
3/26/2021, 13:49:07 - info - InstanceLoader: AppModule dependencies initialized
3/26/2021, 13:49:07 - info - InstanceLoader: ConfigModule dependencies initialized
3/26/2021, 13:49:07 - info - InstanceLoader: NestEmitterModule dependencies initialized
3/26/2021, 13:49:07 - info - InstanceLoader: IntegrationsModule dependencies initialized
3/26/2021, 13:49:07 - info - InstanceLoader: HttpModule dependencies initialized
3/26/2021, 13:49:07 - info - InstanceLoader: DiscoveryModule dependencies initialized
3/26/2021, 13:49:07 - info - InstanceLoader: PrometheusModule dependencies initialized
3/26/2021, 13:49:07 - info - InstanceLoader: TerminusModule dependencies initialized
3/26/2021, 13:49:07 - error - ExceptionHandler: Cannot read property 'address' of undefined
```

**Relevant configuration**
Paste the relevant parts of your configuration below.
```
global:
  instanceName: lounge
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://10.0.2.3:1883'
  mqttOptions:
    username: ***user***
    password: ***password***
bluetoothLowEnergy:
  hciDeviceId: 0
  whitelist:
    - 5484D0A9-2990-4705-9B96-DFE155B1CFF1
    - 5A84F99A-0E10-425E-B9E4-40D31D2B3D42
    - 5515043C-C3BD-4E87-A626-4BF2A0D5E916
  maxDistance: 2.3
  timeout: 60
cluster:
  networkInterface: eth0
  port: 6425
  weight: 10
  quorum: 2
  peerAddresses:
    - 10.0.20.27:6425
    - 10.0.20.31:6425
```

**Expected behaviour**
I expect RA to start up and load in the integrations and then detect my iPhone + iPad companion apps when they are within Bluetooth le range.

**Environment**
 - room-assistant version: 2.15.1
 - installation type: NodeJS
 - hardware: Raspberry Pi 3b+
 - OS: Raspbian Lite 
 
**Additional context**

![image](https://user-images.githubusercontent.com/47009467/112658486-58e49980-8e4b-11eb-8e24-b20059ad8e9e.png)

![image](https://user-images.githubusercontent.com/47009467/112658070-f25f7b80-8e4a-11eb-918e-36974298f21c.png)
