### ISSUE TITLE
Xiaomi Mi Flora no battery status report

### ISSUE THREAD

**Issue by jeroenterheerdt** [mKeRix/room-assistant#638]
**Describe the bug**
No battery status reported to Home Assistant when using the xiaomiMi integration.

**To reproduce**
1. Set up room assistant and integrate with HA
2. Set up xiaomiMi integration and add sensor for Plant Monitor
3. Observe data coming in, but not battery status

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```text
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```yaml
global:
  integrations:
    - homeAssistant
    - xiaomiMi
homeAssistant:
  mqttUrl: 'mqtt://homeassistant.local:1883'
  mqttOptions:
    username: [USER]
    password: ***

xiaomiMi:
  sensors:
    - name: Plant Monitor
      address: ****
```

**Expected behavior**
I expect battery status to be reported.

**Environment**
 - room-assistant version: 2.15.1
 - installation type: NodeJS
 - hardware:  Raspberry Pi Zero W
 - OS:Linux

**Additional context**
