### ISSUE TITLE
2.16.0 detects BLE phones only for several minutes, than marks as Away

### ISSUE THREAD

**Issue by andreypolyak** [mKeRix/room-assistant#649]
**Describe the bug**
I am using Room Assistant to track two iPhones using BLE. I useone Raspberry Pi Zero W and one Raspberry Pi 3B with internal Bluetooth adapters. After updating Room Assistant on both PIs to 2.16.0 I noticed that Room Assistant no longer have stable tracking of phones when they are at home. Here how it looks in Home Assistant:
![Graph](https://user-images.githubusercontent.com/7446762/114540616-6b8a0b80-9c5e-11eb-8e2b-7c828504fabd.png)
![History](https://user-images.githubusercontent.com/7446762/114540624-6e84fc00-9c5e-11eb-8d24-5fd28325d125.png)

The problem occurs with two phones and on two PIs. I tried to restart Room Assistant service, PIs, MQTT Broker, HA, iPhones, Room Assistant companion apps.

I have relatively small apartment, before 99% of time both PIs tracked the phones when they were at home. 

The only thing that changed (apart from updating to 2.16.0) is that I started to use ids under the tagOverrides elements in the config.

**Relevant configuration**
On both PIs I have the same configuration, except for names and ids under the tagOverrides element.
```yaml
global:
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
cluster:
  autoDiscovery: false
homeAssistant:
  sendAttributes: true
  mqttUrl: 'mqtt://192.168.1.178:1883'
  mqttOptions:
    username: %username%
    password: %password%
bluetoothLowEnergy:
  timeout: 120
  updateFrequency: 1
  allowlist:
    - '%uid-for-first-phone%'
    - '%uid-for-second-phone%'
  tagOverrides:
    '%uid-for-first-phone%':
      name: BLE Kitchen Andrey iPhone 11 Pro Max
      id: kitchen_andrey_iphone_11_pro_max
    '%uid-for-second-phone%':
      name: BLE Kitchen Katya iPhone 12 Pro Max
      id: kitchen_katya_iphone_12_pro_max
```

**Environment**
 - room-assistant version: 2.16.0
 - installation type: NodeJS
 - hardware: Raspberry Pi Zero W, Raspberry Pi 3B
 - OS: Raspbian GNU/Linux 10 (buster)

**Comment by mKeRix** [comment]
Did you update the TestFlight app as well by chance, possibly via auto update? That update was released around the same time, I wonder if that may also be the cause of your issues.

Apart from that, do you have any errors in the logs or anything that seems fishy when you run room-assistant in verbose mode?

**Comment by andreypolyak** [comment]
Hi @mKeRix,
1. No the TestFlight app was not updated. However, I updated it right now but it didn't help.
2. I'm attaching the logs with the sample run: [verbose-log.txt](https://github.com/mKeRix/room-assistant/files/6306850/verbose-log.txt)
Timeline there:
- 22:26:19 -- started
- 22:27:55 -- discovered first iPhone
- 22:30:43 -- discovered second iPhone
- 22:31:55 -- lost first iPhone
- 22:32:43 -- lost second iPhone

I can't see any critical errors in the logs. But I noticed that the first iPhone was marked as being home for 4 minutes and the second iPhone for 2 minutes. Can it somehow be related to timeout parameter which I set as 120 in the config?

Thanks!

**Comment by andreypolyak** [comment]
Tried running it without timeout parameter in the config: 
[verbose-log.txt](https://github.com/mKeRix/room-assistant/files/6306915/verbose-log.txt).
- 22:44:01 -- discovered first iPhone
- 22:44:02 -- discovered second iPhone
- 22:46:01 -- lost first iPhone
- 22:46:02 -- lost second iPhone

So once again both phones are lost after two minutes.

**Comment by C0NTi** [comment]
I too am seeing similar behaviour, btle tracking works on fresh start but soon stops working and like @andreypolyak i am also using the name and id overrides.

**Comment by mKeRix** [comment]
The logs don't show anything super out of the ordinary, first one shows a few timeouts, but that could also happen during normal operation. If you can, could you try:

- removing the id override from the config temporarily? (my working test setup uses a name override, but not the id one - I want to see if this difference causes this for you)
- downgrading to v2.15.1 (`sudo npm i --global --unsafe-perm room-assistant@2.15.1` for NodeJS installs) and checking if that solves it

**Comment by andreypolyak** [comment]
Hi @mKeRix,
I tried to remove id override and it helped, both Phones are tracked as expected.

**Comment by mKeRix** [comment]
There seems to be a bug with the id overrides for BLE then. I'll put this to the top of the roadmap so that I take a look at fixing it soon-ish.

**Comment by haltug** [comment]
I have the same issue as above. I used all kind of different configurations, with and w/o id overrides. The issue is somewhere else. I am tracking two Iphones. One Iphone is detected and the other one was working for several hours on fresh start and then disappeared. 

No indication of the phone in the logs, couldnt see anything suspicious. As said It worked for a while on the one phone in the beginning but couldnt be detected anymore after some time. Reinstallation was of no help.

**Environment**
- iphone XS Max & 11 Pro Max (latest room-companion app)
- room-assistant version: 2.16.0
- hardware: 3x Raspberry Pi Zero W (NodeJS installation)

```yaml
all:
  hosts:
    '192.168.10.75':
      ansible_user: three
      ansible_password: *****
      room_assistant_config: 
        global:
          instanceName: Wohnzimmer
        cluster:
          networkInterface: wlan0
          port: 6425
          autoDiscovery: false
          weight: 1
          timeout: 120
          peerAddresses:
            - 192.168.10.80:6425
            - 192.168.10.85:6425        
        bluetoothLowEnergy:
          timeout: 120
          hciDeviceId: 0
          updateFrequency: 15
          onlyIBeacon: false
          rssiFactor: 0.8
          allowlist:
            - 'e0897eb735f8'
            - 'f0c371a9ccda'
            - 'C69DFEA2-DB41-4E67-8D56-644F8AA67ED8'
            - '0814D663-0581-4AFD-99FF-CCCA0B01C595'
          tagOverrides:
            0814D663-0581-4AFD-99FF-CCCA0B01C595:
              name: tu_iphone
              measuredPower: -40
            C69DFEA2-DB41-4E67-8D56-644F8AA67ED8:
              name: ha_iphone
              measuredPower: -38
    '192.168.10.80':
      ansible_user: four
      ansible_password: *****
      room_assistant_config:       
        global:
          instanceName: Ankleidezimmer
        cluster:
          networkInterface: wlan0
          port: 6425
          autoDiscovery: false
          weight: 2
          timeout: 120
          peerAddresses:
            - 192.168.10.75:6425
            - 192.168.10.85:6425           
        bluetoothLowEnergy:
          timeout: 120
          hciDeviceId: 0
          maxDistance: 2.5
          updateFrequency: 15
          onlyIBeacon: false
          allowlist:
            - 'e0897eb735f8'
            - 'f0c371a9ccda'
            - 'C69DFEA2-DB41-4E67-8D56-644F8AA67ED8'
            - '0814D663-0581-4AFD-99FF-CCCA0B01C595'
          tagOverrides:
            0814D663-0581-4AFD-99FF-CCCA0B01C595:
              name: tu_iphone
              measuredPower: -50
            C69DFEA2-DB41-4E67-8D56-644F8AA67ED8:
              name: ha_iphone
              measuredPower: -46
    '192.168.10.85':
      ansible_user: five
      ansible_password: *****
      room_assistant_config:       
        global:
          instanceName: Schlafzimmer
        cluster:
          networkInterface: wlan0
          port: 6425
          autoDiscovery: false
          weight: 3
          timeout: 120
          peerAddresses:
            - 192.168.10.75:6425
            - 192.168.10.80:6425
        bluetoothLowEnergy:
          timeout: 120
          hciDeviceId: 0
          maxDistance: 2.5
          updateFrequency: 15
          onlyIBeacon: false
          allowlist:
            - 'e0897eb735f8'
            - 'f0c371a9ccda'
            - 'C69DFEA2-DB41-4E67-8D56-644F8AA67ED8'
            - '0814D663-0581-4AFD-99FF-CCCA0B01C595'
          tagOverrides:
            0814D663-0581-4AFD-99FF-CCCA0B01C595:
              name: tu_iphone
              measuredPower: -50
            C69DFEA2-DB41-4E67-8D56-644F8AA67ED8:
              name: ha_iphone
              measuredPower: -54
  vars:
    room_assistant_global_config:
      global:
        integrations:
          - homeAssistant
          - bluetoothLowEnergy
      logger:
        loki:
          enabled: false
          host: 'http://192.168.10.20:3100'
      homeAssistant:
        mqttUrl: 'mqtt://192.168.10.10:1883'
        qos: 1
        mqttOptions:
          username: ******
          password: ******
```
