### ISSUE TITLE
Docker Install

### ISSUE THREAD

**Issue by bsmith76s** [mKeRix/room-assistant#650]
**Describe the bug**
This is my 4th node and second docker install of Room-assistant. I used the config file from the working Docker installation changing instance name and IP's in peer addresses, I also used same docker-compose configuration.  Both docker installations are running on RPI4.  I keep getting stuck at this part and have found very little help searching web. I get the following message in **Relevant logs** section when running docker-compse up. 

**To reproduce**
run command 
docker-compose up

**Relevant logs**
Room-Assistant    | *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Room-Assistant    | *** WARNING *** Please fix your application to use the native API of Avahi!
Room-Assistant    | *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
Room-Assistant    | *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Room-Assistant    | *** WARNING *** Please fix your application to use the native API of Avahi!
Room-Assistant    | *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
Room-Assistant    | 4/15/2021, 12:09:58 AM - info - IntegrationsModule: Loading integrations: bluetooth-low-energy, home-assistant
Room-Assistant    | 4/15/2021, 12:09:59 AM - info - NestFactory: Starting Nest application...
Room-Assistant    | 4/15/2021, 12:09:59 AM - info - InstanceLoader: AppModule dependencies initialized
Room-Assistant    | 4/15/2021, 12:09:59 AM - info - InstanceLoader: ConfigModule dependencies initialized
Room-Assistant    | 4/15/2021, 12:09:59 AM - info - InstanceLoader: NestEmitterModule dependencies initialized
Room-Assistant    | 4/15/2021, 12:09:59 AM - info - InstanceLoader: IntegrationsModule dependencies initialized
Room-Assistant    | 4/15/2021, 12:09:59 AM - info - InstanceLoader: HttpModule dependencies initialized
Room-Assistant    | 4/15/2021, 12:09:59 AM - info - InstanceLoader: DiscoveryModule dependencies initialized
Room-Assistant    | 4/15/2021, 12:09:59 AM - info - InstanceLoader: PrometheusModule dependencies initialized
Room-Assistant    | 4/15/2021, 12:09:59 AM - info - InstanceLoader: TerminusModule dependencies initialized
Room-Assistant    | 4/15/2021, 12:09:59 AM - error - ExceptionHandler: Cannot read property 'address' of undefined
Room-Assistant exited with code 1
`

**Relevant configuration**
```
global:
  instanceName: instance name
  integrations:
    - bluetoothLowEnergy
    - homeAssistant
bluetoothLowEnergy:
  hciDeviceId: 0
  timeout: 10
  maxDistance: 5
  allowlist:
    - "185221222119"
    - 5c456d7e5f78
    - dc0efde56203
homeAssistant:
  mqttUrl: 'mqtt://IP.IP.IP.10:1883'
  mqttOptions:
    username: user
    password: password
cluster:
  autoDiscovery: false
  networkInterface: eth0
#  port: 6425
  weight: 5
  peerAddresses:
    - IP.IP.IP.7:6425
    - IP.IP.IP.6:6425
    - IP.IP.IP.5:6425
 

docker compose config
version: '3'
services:
  room-assistant:
    image: mkerix/room-assistant
    container_name: Room-Assistant
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /home/pi/room-assistant/config:/room-assistant/config ```

**Environment**
 - room-assistant version: [latest]
 - installation type: Docker
 - hardware: Raspberry Pi 4 with 10" touch screen panel
 - OS: Raspberry pi OS

**Comment by screenager-be** [comment]
same issue here
this is my config:
```
---
global:
  instanceName: office
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://mqtt.local.host:1883'
#  mqttOptions:
#    username: youruser
#    password: yourpass
bluetoothClassic:
  addresses:
    - "mac address"
```

docker-compose-file: 
```
version: '3'
network:
  proxy:
    external: true
services:
  rass:
    container_name: rass
    image: mkerix/room-assistant
    restart: unless-stopped
#    network_mode: host
    networks:
      - proxy
    environment:
      - TZ=Europe/Brussels
      - PUID=xxxx
      - PGID=xxxx      
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /path/to/config:/room-assistant/config
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy" 
      - "traefik.http.routers.rass-secure.entrypoints=websecure"
      - "traefik.http.routers.rass-secure.rule=Host(`rass.local.host`)"
```

Hardware:
Raspberry Pi 4 8GB
Ubuntu Server 20.04.02 LTS
