### ISSUE TITLE
Failing to reconnect to HA

### ISSUE THREAD

**Issue by beloso** [mKeRix/room-assistant#654]
**Describe the bug**

I am running a single host on my house (it's a small house xD).
I am running Room-Assistant via docker. I also run Home-Assistant and Mosquitto with docker.
I am noticing that my device trackers are losing state information occasionally.

**To reproduce**

 I am pinpointing it to HA restarts and/or Mosquitto restarts. For example today the mosquitto container updated itself.
HA is not able to recognise device state since then.

**Relevant logs**

```text
4/12/2021, 6:44:39 PM - info - HomeAssistantService: Re-connected to broker
4/12/2021, 6:44:39 PM - info - EntitiesService: Refreshing entity states
4/15/2021, 1:01:12 AM - error - HomeAssistantService: connect ECONNREFUSED 192.168.x.x:1883
4/15/2021, 1:01:13 AM - error - HomeAssistantService: connect ECONNREFUSED 192.168.x.x:1883
4/15/2021, 1:01:15 AM - info - HomeAssistantService: Re-connected to broker
4/15/2021, 1:01:15 AM - info - EntitiesService: Refreshing entity states
```

**Relevant configuration**

```yaml
---
global:
  instanceName: "Antas Studio"
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.x.x:1883'
bluetoothClassic:
  interval: 30
  addresses:
    - A4:D9:31:BD:F4:ZZ
    - 60:BE:C4:C8:FA:ZZ
```

My docker containers

```yaml
  # Home Assistant Core - Home Automation
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    restart: always
    depends_on:
      - mariadb
      - adguard
      - mosquitto
    network_mode: host
    volumes:
      - $DOCKERDIR/homeassistant/config:/config
      - $DOCKERDIR/shared:/shared
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      # Diun
      - "diun.enable=true"

  # Mosquitto - MQTT Broker
  # dexec mosquitto /bin/sh -> mosquitto_passwd -b /mosquitto/config/passwd username passwd
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - $MOSQUITTO_HTTP_PORT:1883 #http
      # - $MOSQUITTO_HTTPS_PORT:8883 #https
      - $MOSQUITTO_WEBSOCKET_PORT:9001 #websockets
    command: mosquitto -c /mosquitto-no-auth.conf
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      ## Watchtower
      - "com.centurylinklabs.watchtower.enable=true"

  # Room Assistant
  roomassistant:
    image: mkerix/room-assistant
    container_name: roomassistant
    restart: always
    security_opt:
      - no-new-privileges:true
    depends_on:
      - mosquitto
      - homeassistant
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - $DOCKERDIR/roomassistant/config:/room-assistant/config
      - /var/run/dbus:/var/run/dbus
    labels:
      ## Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
```

<img width="1804" alt="Screenshot 2021-04-15 at 19 23 12" src="https://user-images.githubusercontent.com/450923/114921216-36c6b180-9e22-11eb-962f-6f23045830b8.png">

**Expected behavior**

When ever room assistant reconnects to HA/Mosquitto I'd expect the entities to be properly available in HA.

**Environment**

 - room-assistant version: 2.16.0
 - installation type: Docker
 - hardware: NUC
 - OS: Ubuntu 20.04
