### ISSUE TITLE
NUC Seeing Tile Pro, Room-Assistant Add-On in HASS OS Not

### ISSUE THREAD

**Issue by michaelmcdonald** [mKeRix/room-assistant#665]
**Describe the bug**
I'm running Room Assistant on an Intel NUC (HASS OS directly on the NVME drive) and a RPi Zero W (configs for the room assistant install on each can be found below). The NUC, using `bluetoothctl` and the following series of commands can find the MAC of the Tile Pro:

```
$bluetoothctl
[bluetooth]# menu scan
[bluetooth]# clear
[bluetooth]# transport le
[bluetooth]# duplicated-data on
[bluetooth]# back
[bluetooth]# scan on
```

_information omitted since a TON of devices popped up_

```
[CHG] Device CD:C0:99:DD:F2:71 RSSI: -46
[CHG] Device CD:C0:99:DD:F2:71 ServiceData Key: 0000feed-0000-1000-8000-00805f9b34fb
[CHG] Device CD:C0:99:DD:F2:71 ServiceData Value:
  02 00 90 0e 0b 58 bb 07 a2 b9                    .....X....
```

```
[DEL] Device CD:C0:99:DD:F2:71 CD-C0-99-DD-F2-71
```

So it obviously sees the Tile. The room assistant logs however never show it as being found and constantly display the following:

```
BluetoothService: Did not detect any low energy advertisements in a while, resetting
```

Within home assistant I have a card though that shows the Tile as connecting to the RPi Zero W (which is called "Garage"), even though it's sitting next to the NUC (which should have a strong connection / RSSI:

![Screen Shot 2021-04-22 at 08 19 30](https://user-images.githubusercontent.com/4342041/115715156-e2519380-a345-11eb-8e2d-077d441cfa20.png)

I'm not sure what I'm doing wrong on the NUC such that it is not detecting the Tile. Any thoughts?

**To reproduce**
Install HASS OS directly to the NUC drive, setup room assistant, and see if it can detect a Tile Pro.

**Relevant logs**
Logs from the NUC directly after restarting room-assistant:

```text
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:27:31] INFO: Setting up Home Assistant configuration
[09:27:31] INFO: Copying room-assistant configuration from /config/room_assistant
[09:27:31] INFO: Starting room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
4/22/2021, 9:27:32 AM - info - IntegrationsModule: Loading integrations: home-assistant, bluetooth-low-energy
4/22/2021, 9:27:32 AM - info - NestFactory: Starting Nest application...
4/22/2021, 9:27:32 AM - info - InstanceLoader: AppModule dependencies initialized
4/22/2021, 9:27:32 AM - info - InstanceLoader: ConfigModule dependencies initialized
4/22/2021, 9:27:32 AM - info - InstanceLoader: NestEmitterModule dependencies initialized
4/22/2021, 9:27:32 AM - info - InstanceLoader: IntegrationsModule dependencies initialized
4/22/2021, 9:27:32 AM - info - InstanceLoader: HttpModule dependencies initialized
4/22/2021, 9:27:32 AM - info - InstanceLoader: DiscoveryModule dependencies initialized
4/22/2021, 9:27:32 AM - info - InstanceLoader: PrometheusModule dependencies initialized
4/22/2021, 9:27:32 AM - info - InstanceLoader: ClusterModule dependencies initialized
4/22/2021, 9:27:32 AM - info - InstanceLoader: TerminusModule dependencies initialized
4/22/2021, 9:27:32 AM - info - InstanceLoader: BluetoothModule dependencies initialized
4/22/2021, 9:27:32 AM - info - InstanceLoader: ScheduleModule dependencies initialized
4/22/2021, 9:27:32 AM - info - InstanceLoader: EntitiesModule dependencies initialized
4/22/2021, 9:27:32 AM - info - InstanceLoader: BluetoothLowEnergyModule dependencies initialized
4/22/2021, 9:27:32 AM - info - InstanceLoader: HomeAssistantModule dependencies initialized
4/22/2021, 9:27:32 AM - info - InstanceLoader: StatusModule dependencies initialized
4/22/2021, 9:27:32 AM - info - RoutesResolver: EntitiesController {/entities}:
4/22/2021, 9:27:32 AM - info - RouterExplorer: Mapped {/entities, GET} route
4/22/2021, 9:27:32 AM - info - RoutesResolver: StatusController {/status}:
4/22/2021, 9:27:32 AM - info - RouterExplorer: Mapped {/status, GET} route
4/22/2021, 9:27:32 AM - info - RoutesResolver: PrometheusController {/metrics}:
4/22/2021, 9:27:32 AM - info - RouterExplorer: Mapped {/metrics, GET} route
4/22/2021, 9:27:32 AM - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://192.168.1.148:1883
4/22/2021, 9:27:32 AM - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/default.json, config/local.yml (Current: /room-assistant)
4/22/2021, 9:27:32 AM - error - ClusterService: Failed to start mdns discovery (dns service error: unknown)
4/22/2021, 9:27:32 AM - info - NestApplication: Nest application successfully started
4/22/2021, 9:27:33 AM - info - ClusterService: Added 192.168.1.88:6425 to the cluster with id garage
4/22/2021, 9:28:02 AM - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting
```

**Relevant configuration**
**NUC**

```yaml
global:
  instanceName: NUC
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
cluster:
  port: 6425
  peerAddresses:
    - 192.168.1.88:6425
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.148:1883'
  mqttOptions:
    username: mqtt
    password: mqtt
bluetoothLowEnergy:
  timeout: 120
  updateFrequency: 5
  maxDistance: 15
  hciDeviceId: 0
  allowlist:
    - cdc099ddf271
```

**RPi Zero W**

```yaml
global:
  instanceName: Garage
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
cluster:
  port: 6425
  peerAddresses:
    - 192.168.1.148:6425
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.148:1883'
  mqttOptions:
    username: mqtt
    password: mqtt
bluetoothLowEnergy:
  timeout: 120
  updateFrequency: 5
  maxDistance: 15
  hciDeviceId: 0
  allowlist:
    - cdc099ddf271
 ```

**Expected behavior**
Both the NUC and the RPi Zero W should see the Tile, and whichever the Tile is closer to should present as the tile being "present" in that room.

**Environment**
 - room-assistant version: On NUC: 2.16.0; on RPi Zero W: 2.16.0
 - installation type: Hass OS directly to NVME for NUC, direct room-assistant install to SD card for RPi Zero W
 - hardware: Raspberry Pi Zero W, NUC

**Comment by mKeRix** [comment]
The issue here seems to be that the room-assistant add-on does not seem to hook into the Bluetooth adapter properly at all, although I can't see any obvious issues with your setup that would cause this. I'm a bit perplex honestly - and unfortunately, since the HA add-on currently does not offer the verbose logging mode as an option, I can't really think of more ways to debug aside from what you've already done.

Do you see the same issue if you remove the `hciDeviceId` option from the config on the NUC? I'm wondering if maybe the add-on has a different id mapped, but no error is shown. Not specifying it would let the add-on just pick a default.

**Comment by michaelmcdonald** [comment]
I removed the `hciDeviceId` line from my config, restarted HA, but still no luck. Updated config for reference:

```
global:
  instanceName: NUC
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
cluster:
  port: 6425
  peerAddresses:
    - 192.168.1.88:6425
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.148:1883'
  mqttOptions:
    username: mqtt
    password: mqtt
bluetoothLowEnergy:
  timeout: 120
  updateFrequency: 5
  maxDistance: 15
  allowlist:
    - cdc099ddf271
 ```

I powered off the RPi Zero W so now the Tile has nothing to connect to _but_ the NUC and it still shows as "not home":

![Screen Shot 2021-04-25 at 21 25 38](https://user-images.githubusercontent.com/4342041/116017176-e7943400-a60c-11eb-9cad-d32d777eb53f.png)

I can see when I access the Bash container on HASS OS that `hci0` should be the correct device ID (so, theoretically, my previous config _should_ have worked):

```
bash-5.0# hciconfig
hci0:	Type: Primary  Bus: USB
	BD Address: 0C:DD:24:D3:F5:DF  ACL MTU: 1021:4  SCO MTU: 96:6
	UP RUNNING PSCAN
	RX bytes:16690805 acl:0 sco:0 events:1208113 errors:0
	TX bytes:18023756 acl:0 sco:0 commands:1199001 errors:1
```

Checking out our friend `dmesg` shows lines and lines of this:

```
[1582003.962131] debugfs: File 'le_min_key_size' in directory 'hci0' already present!
```

However that seems to be a red herring as discussed in this thread:

https://github.com/mKeRix/room-assistant/discussions/377

Performing the following commands still shows that the NUC _can_ see the Tile, but Home Assistant / Room Assistant do not for some reason:

```
bash-5.0# bluetoothctl
[bluetooth]# menu scan
[bluetooth]# clear
[bluetooth]# transport le
[bluetooth]# duplicate-data on
[bluetooth]# back
[bluetooth]# scan on

< _OUTPUT OMITTED_ >

[CHG] Device CD:C0:99:DD:F2:71 RSSI: -25
[CHG] Device CD:C0:99:DD:F2:71 ServiceData Key: 0000feed-0000-1000-8000-00805f9b34fb
[CHG] Device CD:C0:99:DD:F2:71 ServiceData Value:
  02 00 b7 87 9c aa 3c de 46 99                    ......<.F.
```

--------------------------------------------------------------------------------

Any other thoughts? Appreciate the help!
