### ISSUE TITLE
error - ExceptionHandler: Cannot read property 'address' of undefined

### ISSUE THREAD

**Issue by gbdavidx** [mKeRix/room-assistant#668]
I installed a fresh version of room-assistant on a pi w 

+ room-assistant@2.16.0
updated 1 package in 134.76s
pi@livingroom2:~/room-assistant $ sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)
pi@livingroom2:~/room-assistant $ sudo setcap cap_net_raw+eip $(eval readlink -f `which hcitool`)
pi@livingroom2:~/room-assistant $ sudo setcap cap_net_admin+eip $(eval readlink -f `which hciconfig`)
pi@livingroom2:~/room-assistant $ room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
24/04/2021, 00:13:13 - info - IntegrationsModule: Loading integrations: home-assistant, bluetooth-classic
24/04/2021, 00:13:18 - info - NestFactory: Starting Nest application...
24/04/2021, 00:13:19 - info - InstanceLoader: AppModule dependencies initialized
24/04/2021, 00:13:19 - info - InstanceLoader: ConfigModule dependencies initialized
24/04/2021, 00:13:19 - info - InstanceLoader: NestEmitterModule dependencies initialized
24/04/2021, 00:13:19 - info - InstanceLoader: IntegrationsModule dependencies initialized
24/04/2021, 00:13:19 - info - InstanceLoader: HttpModule dependencies initialized
24/04/2021, 00:13:19 - info - InstanceLoader: DiscoveryModule dependencies initialized
24/04/2021, 00:13:19 - info - InstanceLoader: PrometheusModule dependencies initialized
24/04/2021, 00:13:19 - info - InstanceLoader: TerminusModule dependencies initialized
24/04/2021, 00:13:19 - error - ExceptionHandler: Cannot read property 'address' of undefined
pi@livingroom2:~/room-assistant $

```

global:
  instanceName: livingroom2
  integrations:
    - homeAssistant
    - bluetoothClassic
#bluetoothLowEnergy:
#  allowlist:
#  - '88644071676E'
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.123:1883'
  mqttOptions:
    username: user
    password: passwd
bluetoothClassic:
  timeoutCycles: 2.5
  interval: 6
  addresses:
    - '90:81:2A:1C:6F:27' #davids applewatch
  minRssi:
    '90:81:2A:1C:6F:27': -1
cluster:
  autoDiscovery: true
  networkInterface: true
  port: 6425
  peerAddresses:
    - 192.168.1.190:6425
```
