### ISSUE TITLE
BLE attributes not reported without a cluster section in config

### ISSUE THREAD

**Issue by mariwing** [mKeRix/room-assistant#705]
**Describe the bug**
I have one instance of room assistant running on one RPI 3. I have one iPhone with the companion app. I have setup room assistant with integration Home Assistant and Bluetooth low energy. BLE is only tracking the companion app.

The attributes for the companion app is not reported on MQTT so the state and additional attributes is missing. Only status online is reported.

After looking at this issue https://github.com/mKeRix/room-assistant/issues/604#issuecomment-801379020 I added 

cluster:
  quorom: 1

After restart the state and attributes appears. 

**To reproduce**
Setup one instance of room assistant on the network and do not include a cluster section. The quorum reached attribute on the status-cluster-leader entity stays at false and no state or attributes are observerd on mqtt bus.

**Relevant configuration**
This config is working and reports quorum reached = true and state and attributes for the companion app. Remove the cluster section and it stops reporting state and attribute and quorum reached attribute stays at false. 

```yaml
global:
  instanceName: Soverom
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
cluster:
  weight: 1000
  quorum: 1
  autoDiscovery: true
homeAssistant:
  mqttUrl: 'mqtt://homeassistant.local:1883'
  mqttOptions:
    username: mqtt
    password: hC94syGH2omh
  sendMqttRoom: true
  sendAttributes: true
bluetoothLowEnergy:
  timeout: 120
  updateFrequency: 15
  allowlist:
    - 120E4FAB-6AC2-4DB4-8312-46690F755BD7
  tagOverrides:
    120E4FAB-6AC2-4DB4-8312-46690F755BD7:
      name: 'Marius iPhone Soverom'
```

**Expected behavior**
When running one instance a cluster section should not be needed for BLE to report state and attributes or it should be documented for the ble integration that a cluster section is mandatory.

**Environment**
 - room-assistant version: 2.17.0
 - installation type: NodeJS
 - hardware: PI3
 - OS: Linux

**Additional context**
The mqttroom stuff is not sent either without the cluster config section
