### ISSUE TITLE
Documentation must be easier to read

### ISSUE THREAD

**Issue by Nihvel** [mKeRix/room-assistant#707]
**Describe the bug**
A section of the documentation in _entities.md_ is not clear.

On "Rolling average", the sample configuration shows undocumented text.
```
entities:
  behaviors:
    bluetooth-classic-xx-tracker:
      rollingAverage:
        window: 300
```

What is bluetooth-classic-**xx**-tracker?
The **xx** stands for the device's name, followed by **_tracker**. But this is something the user sees when room-assistant connects to Home Assistant and creates the sensor. 
The same user changed on Home Assistant the entity_id for this sensor. Should the user now use the new name of the sensor?

**Change request**
Use the diamond operators when the documentation refers to a variable or a piece of code the user must change.

Example:
```
entities:
  behaviors:
    bluetooth-classic-<xx-tracker>:
      rollingAverage:
        window: 300
```
Where `<xx-tracker>` is the entity_id in Home Assistant.
