### ISSUE TITLE
Cannot set entity id with tagOverride using 'id:'

### ISSUE THREAD

**Issue by Scott8586** [mKeRix/room-assistant#732]
**Describe the bug**
Cannot use 'id' to set entity id in tagOverride block for BLE

**To reproduce**
See Configuration, start room-assistant -v

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```text
25/05/2021, 09:17:04 - info - BluetoothLowEnergyService: Discovered new BLE peripheral 426c7565436861726d426561636f6e70-3838-4949 with ID 426c7565436861726d426561636f6e70-3838-4949 and RSSI -98
(node:3034) UnhandledPromiseRejectionWarning: TypeError: Cannot set property id of #<IBeacon> which has only a getter
    at BluetoothLowEnergyService.applyOverrides (/opt/nodejs/lib/node_modules/room-assistant/dist/integrations/bluetooth-low-energy/bluetooth-low-energy.service.js:257:24)
    at BluetoothLowEnergyService.handleDiscovery (/opt/nodejs/lib/node_modules/room-assistant/dist/integrations/bluetooth-low-energy/bluetooth-low-energy.service.js:95:24)
(Use `node --trace-warnings ...` to show where the warning was created)
(
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```yaml
bluetoothLowEnergy:
  hciDeviceId: 0
  updateFrequency: 20
  onlyIBeacon: true
  allowlist:
    - 426c7565436861726d426561636f6e70-3838-4949
  tagOverrides:
    '426c7565436861726d426561636f6e70-3838-4949':
      id: audi_q7_bt_tracker
      name: Audi Q7 BT
```

**Expected behavior**
expected to be able to set entity_id, instead get error.  Removing 'id:' line results in working configuration, but does not set the entity_id 

**Environment**
 - room-assistant version: 2.17.0
 - installation type: NodeJS
 - hardware: Raspberry Pi Zero W
 - OS: Raspbian GNU/Linux 9 (stretch)

**Additional context**
Not sure about this part, but other beacons of this type set the entity_id to the "name" I've given the beacon (e.g. here it would/should have been "AudiQ7", and the device tracker entity would have shown up as device_tracker.audiq7_tracker automatically.  Here that didn't happen so I tried to set the entity_id using the tagOverride block, but that didn't work either, hence the bug report.

Also I note that the tagOverride array elements seem to be case sensitive, that threw me for a while - it should be documented.
