### ISSUE TITLE
MQTT distance not reset if not reachable for BLE

### ISSUE THREAD

**Issue by dflvunoooooo** [mKeRix/room-assistant#825]
**Describe the bug**
The MQTT message containing the distances from all nodes stays at the last measured value for a node with integration bluetooth low energy. And `outOfRange` is not set. One can see, that the `lastUpdatedAt` value didn't change since 10 minutes either. The graph shows it as well.

![Screenshot_20210720_115836](https://user-images.githubusercontent.com/32816598/126304936-8072d4e4-35f5-460b-9cbf-50a5ad6ba553.png)

**To reproduce**
Get the measured device in range of all nodes, either at once or in turn doesn't matter. After that, go somewhere, were one node will not be able to measure the distance for that device. Now read the MQTT-messages.

**Relevant logs**
A MQTT-message:

```
distances: 
  Kueche: object
    lastUpdatedAt: "2021-07-20T09:59:14.347Z"
    distance: 31.1
    outOfRange: false
  Bad: object
    lastUpdatedAt: "2021-07-20T09:59:49.733Z"
    distance: 12.2
    outOfRange: false
  Wohnzimmer: object
    lastUpdatedAt: "2021-07-20T09:32:30.031Z"
    distance: 11.2
    outOfRange: false
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```
global:
  instanceName: Kueche
  integrations:
    - bluetoothLowEnergy
    - homeAssistant
    - mqtt
cluster:
  timeout: 120
mqtt:
  mqttUrl: mqtt://IP
  mqttOptions:
    username: mqtt-user
    password: ***password***
  retain: false
homeAssistant:
  mqttUrl: mqtt://IP
  mqttOptions:
    username: mqtt-user
    password: ***password***

bluetoothLowEnergy:
  allowlist:
    - 90b7384d5dc045979bf9f13823456d55-100-1
    - 6767d851ad39426eb25b710b3456a270-100-1
    - a09e1a34566e
  updateFrequency: 5
  tagOverrides:
    90b7384d5dc045979bf9f13823456d55-100-1:
      name: PH-1-BLE
    6767d851ad39426eb25b710b3456a270-100-1:
      name: XZ1-BLE
    a09e1a34566e:
      name: Polar-Vantage-M
```

**Expected behavior**
I would expect that either the `outOfRange` is set or/and the distance value is not kept.

**Environment**
 - room-assistant version: 2.16.0
 - installation type: NodeJS 14.17.3
 - hardware: Raspberry Pi 4

 - Arch Linux ARM

**Additional context**
Mapybe this is a desired behaviour and i am missing something. Please tell me if so.
