### ISSUE TITLE
Starting room-assistant on home assistant os fails

### ISSUE THREAD

**Issue by CHlLL7** [mKeRix/room-assistant#854]
**Describe the bug**
After updating to the latest home assistant version I can not start room-assistant anymore.
I tried rolling back home assistant version, uninstall and install add-on again, restart but I still get the same error.
**To reproduce**
Start room assistant from Home Assistant Supervisor.
**Relevant logs**

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:00:19] INFO: Setting up Home Assistant configuration
[16:00:19] INFO: Copying room-assistant configuration from /config/room_assistant
[16:00:19] INFO: Starting room-assistant
/room-assistant/entrypoint.sh: line 24: exec: room-assistant: not found
[cmd] /room-assistant/entrypoint.sh exited 127
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Relevant configuration**

/config/room_assistant/local.yml:

```
global:
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
cluster:
  autoDiscovery: false
  networkInterface: eth0
  port: 6425
  peerAddresses:
    - 192.168.1.58:6425
  instanceName: livingroom
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.33:1883'
  mqttOptions:
    username: xxx
    password: xxx
bluetoothLowEnergy:
  timeout: 60
  allowlist:
  - 'xxx-xxx-xxx-xxx-xxx'
  - 'xxx-xxx-xxx'
  maxDistance: 7
  tagOverrides:
    xxx-xxx-xxx-xxx-xxx:
      name: iPhone1
    xxx-xxx-xxx:
      name: Phone2
```

**Expected behavior**
Start the add-on
**Environment**
 - room-assistant version: 2.18.4
 - installation type: Home Assistant OS add-on
 - hardware: Raspberry Pi 4
 - OS: Home Assistant OS
