### ISSUE TITLE
Constant crashing after updating bluez/bluetooth packages Pi4

### ISSUE THREAD

**Issue by iceman23e** [mKeRix/room-assistant#870]
**Describe the bug**
After updating bluez and bluetooth packages on my Pi4, room-assistant continually crashes. Most times it lasts only a couple seconds before crashing, but occasionally it will make it a couple minutes. It has been running rock solid for months with no issues before updating these packages. I've tried downgraded the four upgraded packages, but that doesn't seem to work. Also tried downgrading bluez-firmware.

**To reproduce**
Not sure, but update bluez and bluetooth packages.

**Relevant logs**

```
room-assistant[2004]: 8/10/2021, 6:52:09 PM - error - BluetoothService: Inquiring RSSI via BT Classic failed: Command failed: hcitool -i hci0 cc "xx" && hcitool -i hci0 rssi "xx"
room-assistant[2004]: Can't create connection: Operation not permitted
room-assistant[2004]: Get connection info failed: No such file or directory
```

**Relevant configuration**

```
global:
  instanceName: Living
  integrations:
    - homeAssistant
    - bluetoothClassic
    - gridEye
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.142:1883'
  mqttOptions:
    username: xx
    password: xx
bluetoothClassic:
  minRssi: -25
  addresses:
    - 'xx'
    - 'xx'
gridEye:
  deltaThreshold: 3
  heatmap:
    enabled: true
cluster:
  weight: 20
  port: 6425
  peerAddresses:
    - 192.168.1.121:6425
    - 192.168.1.142:6425
    - 192.168.1.167:6425
```

**Expected behavior**
To not crash

**Environment**
 - room-assistant version: 2.18.4
 - installation type: NodeJS
 - hardware: Pi4
 - OS: Raspbian lite
