### ISSUE TITLE
2.19.0 refuses to start on 1 out of 2 identical RPi3s

### ISSUE THREAD

**Issue by hugalafutro** [mKeRix/room-assistant#917]
**Describe the bug**
Noticed new build is out, updated 1 rpi3 everything worked well, second one doesn't come up. Both run same raspbian, same version of docker and docker-compose, identical docker-compose.yml and config/local.yml

**To reproduce**
just did docker-compose pull & docker-compose up -d, nothing else

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7e8d5634
```
and this just keeps repeating as the container keeps resetting with the hex code changing each time. As this is going on, this appears in dmesg:
```
[ 1712.012314] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x01adb210
[ 1714.103334] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x01aab210
[ 1715.063039] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x01b1b210
[ 1716.202502] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x01a9b210
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```
global:
  instanceName: kitchen
  integrations:
    - homeAssistant
    - bluetoothLowEnergy

homeAssistant:
  mqttUrl: 'mqtt://192.168.1.228:1883'
  mqttOptions:
    username: mosquitto
    password: mosquitto
  discoveryPrefix: homeassistant

bluetoothLowEnergy:
  allowlist:
    - fda56693a4e24ff1afcfc6eb07647825-16065-26349
  tagOverrides:
    fda56693a4e24ff1afcfc6eb07647825-16065-26349:
      name: keys_feasybeacon
```

**Expected behavior**
Was hoping 2nd instance would come up np same as 1st one.

**Environment**
 - room-assistant version: 2.19.0
 - installation type: docker
 - hardware: raspberry pi 3b+
 - OS: Linux 5.10.60-v7+

**Additional context**
docker-compose.yml:
```
version: '3'
services:
  room-assistant:
    container_name: room-assistant_pi-hole
    image: mkerix/room-assistant:latest
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - /var/run/dbus:/var/run/dbus
      - ./config:/room-assistant/config
    restart: unless-stopped
```

downgrading to `mkerix/room-assistant:2.18.4` image, container comes up straight away with same config.
