### ISSUE TITLE
2.19.0 version crashing in Docker version

### ISSUE THREAD

**Issue by B1n00** [mKeRix/room-assistant#922]
**Describe the bug**
Docker version of the latest release keep crashing while running in docker

**To reproduce**
Launch docker version of the 2.19.0 version of room-assistant

**Relevant logs**

```
room-assistant_1  | 
room-assistant_1  | 
room-assistant_1  | #
room-assistant_1  | # Fatal error in , line 0
room-assistant_1  | # unreachable code
room-assistant_1  | #
room-assistant_1  | #
room-assistant_1  | #
room-assistant_1  | #FailureMessage Object: 0xbed125f4
pi_room-assistant_1 exited with code 133
```

**Relevant configuration**

```
room-assistant:
    image: mkerix/room-assistant:2.19.0
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/dbus:/var/run/dbus
      - type: volume
        source: room-assistant
        target: /room-assistant/config
        volume:
          nocopy: true
```
**Expected behavior**
room-assistant 2.19.0 running

**Environment**
RPI 4
