### ISSUE TITLE
Raspberry pi zero w with dongle stops reporting / all stop reporting

### ISSUE THREAD

**Issue by JeroenTuinstra** [mKeRix/room-assistant#924]
I am trying for a couple of weeks now to get room presence working. I bought 4 raspberry pi zero w with extra Bluetooth dongles.
Presence has been more than sketchy. The following things constantly happen.

Home Assistant reports either my BLE iphone as away or unavailable
My Apple Watch through Bluetooth Classic the same. 

In my Room assistant companion app they are reported correctly. So why is this information not passed on to Home Assistant. It seems after a reboot that they work for a couple of minutes (maybe 10) and then both entities are reporting wrong again (not in the app, but in Home Assistant). 

I am kindof at a loss what to do. I have replaced one zero with a raspberry pi 3 b+, and am thinking of replacing all the zero's with 3 or 4 pi's. But I am not sure even pi 3 accurately reports the status. 

This is my config file:
```
cluster:
  port: 6415
  peerAddresses:
    - 192.168.10.75:6415
    - 192.168.10.77:6415
    - 192.168.10.79:6415
    - 192.168.10.80:6415
    - 192.168.10.81:6415
  autoDiscovery: true
  weight: 30
global:
  instanceName: bedroom
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://mqttaddress:1883'
  mqttOptions:
    username: loginname
    password: password
bluetoothLowEnergy:
  hciDeviceId: 0
  allowlist:
    - 1E808694-68E0-433E-A010-BC850C8481F0
    - 4A89AB27-F043-4A8F-B357-5FA63302DC36
  maxDistance: 5
  tagOverrides:
    1E808694-68E0-433E-A010-BC850C8481F0:
      name: Iphone Jeroen BLE
    4A89AB27-F043-4A8F-B357-5FA63302DC36:
      name: Iphone Isaac BLE
bluetoothClassic:
  hciDeviceId: 1
  minRssi: -5
  addresses:
    - '64:d2:c4:7a:72:c2'
  entityOverrides:
    '64:d2:c4:7a:72:c2':
      name: Apple Watch Jeroen BT
```

On 2 of the raspberry pi zero's I constantly get this error when running room-assistant in verbal mode: 
```
BluetoothService: Command failed: hcitool -i hci1 cc "64:d2:c4:7a:72:c2" && hcitool -i hci1 rssi "64:d2:c4:7a:72:c2"
Can't create connection: Input/output error
Get connection info failed: No such file or directory
```
Connection to MQTT broker is fine. New instances are reported to Home Assistant, just their status not.
