### ISSUE TITLE
Docker impossible get configuration file

### ISSUE THREAD

**Issue by RobertusIT** [mKeRix/room-assistant#961]
**Describe the bug**
Impossible to config local.yml

**To reproduce**
room assistant start with default config

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```
[16:50:33] INFO: Copying room-assistant configuration from /config/room_assistant

[16:50:33] INFO: Starting room-assistant

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.

*** WARNING *** Please fix your application to use the native API of Avahi!

*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>

*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.

*** WARNING *** Please fix your application to use the native API of Avahi!

*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>

11/8/2021, 4:50:34 PM - info - IntegrationsModule: Loading integrations: home-assistant

11/8/2021, 4:50:35 PM - info - NestFactory: Starting Nest application...

11/8/2021, 4:50:35 PM - info - InstanceLoader: AppModule dependencies initialized

11/8/2021, 4:50:35 PM - info - InstanceLoader: ConfigModule dependencies initialized

11/8/2021, 4:50:35 PM - info - InstanceLoader: NestEmitterModule dependencies initialized

11/8/2021, 4:50:35 PM - info - InstanceLoader: IntegrationsModule dependencies initialized

11/8/2021, 4:50:35 PM - info - InstanceLoader: DiscoveryModule dependencies initialized

11/8/2021, 4:50:35 PM - info - InstanceLoader: PrometheusModule dependencies initialized

11/8/2021, 4:50:35 PM - info - InstanceLoader: EventsModule dependencies initialized

11/8/2021, 4:50:35 PM - info - InstanceLoader: TerminusModule dependencies initialized

11/8/2021, 4:50:35 PM - info - InstanceLoader: ClusterModule dependencies initialized

11/8/2021, 4:50:35 PM - info - InstanceLoader: ScheduleModule dependencies initialized

11/8/2021, 4:50:35 PM - info - InstanceLoader: EntitiesModule dependencies initialized

11/8/2021, 4:50:35 PM - info - InstanceLoader: HomeAssistantModule dependencies initialized

11/8/2021, 4:50:35 PM - info - InstanceLoader: StatusModule dependencies initialized

11/8/2021, 4:50:35 PM - info - RoutesResolver: EntitiesController {/entities}:

11/8/2021, 4:50:35 PM - info - RouterExplorer: Mapped {/entities, GET} route

11/8/2021, 4:50:35 PM - info - RoutesResolver: StatusController {/status}:

11/8/2021, 4:50:35 PM - info - RouterExplorer: Mapped {/status, GET} route

11/8/2021, 4:50:35 PM - info - RoutesResolver: PrometheusController {/metrics}:

11/8/2021, 4:50:35 PM - info - RouterExplorer: Mapped {/metrics, GET} route

11/8/2021, 4:50:35 PM - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/local.yml (Current: /room-assistant)

11/8/2021, 4:50:35 PM - error - HomeAssistantService: connect ECONNREFUSED 127.0.0.1:1883

11/8/2021, 4:50:35 PM - error - ClusterService: Failed to start mdns discovery (dns service error: unknown)

11/8/2021, 4:50:35 PM - info - NestApplication: Nest application successfully started

11/8/2021, 4:50:37 PM - info - ClusterService: changeme has been elected as leader

11/8/2021, 4:50:37 PM - info - HomeAssistantService: Refreshing entity states
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```
![image](https://user-images.githubusercontent.com/11599774/140784353-ee37be3b-6a25-4d18-a8f0-8aa0b28bc4bc.png)
global:
  instanceName: SALONE-NUC
  integrations:
    - homeAssistant
    - bluetoothClassic
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://192.168.178.56:1883'
  mqttOptions:
    username: mqtt_user
    password: mqtt_user
bluetoothClassic:
#  hciDeviceId: 0
#  interval: 10
#  timeoutCycles: 2.5
#  minRssi:
#    '64:A2:F9:31:XX:XX': -10
#    default: -20
  addresses:
    - '64:A2:F9:31:0B:B9'
#  entityOverrides:
#   '64:A2:F9:31:XX:XX':
#    id: ONE-PLUS6
#    name: oneplus_6
bluetoothLowEnergy:
  allowlist:
    - c7XX80fXXfXX
  tagOverrides:
    c72c80ff2fdc:
      name: Mi Band 6
```

**Expected behavior**
I can't start room assistant in docker with my yaml

**Environment**
 - room-assistant version: mkerix/room-assistant-amd64:latest
 - installation type: Docker
 - hardware: NUC
 - OS: Proxmox - lxc container with TurnKey GNU/Linux 16.1 (Debian 10/Buster) and docker with room assistant

**Comment by hellcry37** [comment]
Check not to have [TABS] in that config, i am 99% that is the issue here, there is no bug.

If you read about YAML you will know it will not handle [TAB]

**Comment by RobertusIT** [comment]
> Check not to have [TABS] in that config, i am 99% that is the issue here, there is no bug.
> 
> If you read about YAML you will know it will not handle [TAB]

In first, thanks to reply

Sorry but what do you means about TABS ?

I searched without success, I'm not an expert about docker and portainer, but anyway I didn't find any "tabs" features

**Comment by hellcry37** [comment]
edit your yaml file (config) delete all white spaces and put them back but only with space bar, do not use TAB from your keyboard

**Comment by RobertusIT** [comment]
> edit your yaml file (config) delete all white spaces and put them back but only with space bar, do not use TAB from your keyboard

I have tried without success, and when i start room assistant, my config file, come back to default

**Comment by hellcry37** [comment]
check docker mounts, from what i sow not sure are ok
https://user-images.githubusercontent.com/11599774/140784353-ee37be3b-6a25-4d18-a8f0-8aa0b28bc4bc.png

**Comment by RobertusIT** [comment]
> check docker mounts, from what i sow not sure are ok https://user-images.githubusercontent.com/11599774/140784353-ee37be3b-6a25-4d18-a8f0-8aa0b28bc4bc.png

in according to https://www.room-assistant.io/guide/configuration.html#configuring-with-docker

![image](https://user-images.githubusercontent.com/11599774/141201589-b38ae9f6-1d27-4689-9630-e369a75ea0cb.png)

same story

```
[22:08:20] ERROR: Something went wrong contacting the API

[22:08:20] INFO: Creating default room-assistant configuration under /config/room_assistant

[22:08:20] INFO: Copying room-assistant configuration from /config/room_assistant

[22:08:20] INFO: Starting room-assistant

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.

*** WARNING *** Please fix your application to use the native API of Avahi!

*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>

*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.

*** WARNING *** Please fix your application to use the native API of Avahi!

*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>

11/10/2021, 10:08:21 PM - info - IntegrationsModule: Loading integrations: home-assistant

11/10/2021, 10:08:22 PM - info - NestFactory: Starting Nest application...

11/10/2021, 10:08:22 PM - info - InstanceLoader: AppModule dependencies initialized

11/10/2021, 10:08:22 PM - info - InstanceLoader: ConfigModule dependencies initialized

11/10/2021, 10:08:22 PM - info - InstanceLoader: NestEmitterModule dependencies initialized

11/10/2021, 10:08:22 PM - info - InstanceLoader: IntegrationsModule dependencies initialized

11/10/2021, 10:08:22 PM - info - InstanceLoader: DiscoveryModule dependencies initialized

11/10/2021, 10:08:22 PM - info - InstanceLoader: PrometheusModule dependencies initialized

11/10/2021, 10:08:22 PM - info - InstanceLoader: EventsModule dependencies initialized

11/10/2021, 10:08:22 PM - info - InstanceLoader: TerminusModule dependencies initialized

11/10/2021, 10:08:22 PM - info - InstanceLoader: ClusterModule dependencies initialized

11/10/2021, 10:08:22 PM - info - InstanceLoader: ScheduleModule dependencies initialized

11/10/2021, 10:08:22 PM - info - InstanceLoader: EntitiesModule dependencies initialized

11/10/2021, 10:08:22 PM - info - InstanceLoader: HomeAssistantModule dependencies initialized

11/10/2021, 10:08:22 PM - info - InstanceLoader: StatusModule dependencies initialized

11/10/2021, 10:08:22 PM - info - RoutesResolver: EntitiesController {/entities}:

11/10/2021, 10:08:22 PM - info - RouterExplorer: Mapped {/entities, GET} route

11/10/2021, 10:08:22 PM - info - RoutesResolver: StatusController {/status}:

11/10/2021, 10:08:22 PM - info - RouterExplorer: Mapped {/status, GET} route

11/10/2021, 10:08:22 PM - info - RoutesResolver: PrometheusController {/metrics}:

11/10/2021, 10:08:22 PM - info - RouterExplorer: Mapped {/metrics, GET} route

11/10/2021, 10:08:22 PM - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/local.yml (Current: /room-assistant)

11/10/2021, 10:08:22 PM - error - HomeAssistantService: connect ECONNREFUSED 127.0.0.1:1883

11/10/2021, 10:08:22 PM - error - ClusterService: Failed to start mdns discovery (dns service error: unknown)

11/10/2021, 10:08:22 PM - info - NestApplication: Nest application successfully started

11/10/2021, 10:08:24 PM - info - ClusterService: changeme has been elected as leader

11/10/2021, 10:08:24 PM - info - HomeAssistantService: Refreshing entity state
```

**Comment by hellcry37** [comment]
ok so this:
error - HomeAssistantService: connect ECONNREFUSED 127.0.0.1:1883

says your instance of room assistant can't connect to mqtt broker

[22:08:20] INFO: Creating default room-assistant configuration under /config/room_assistant
[22:08:20] INFO: Copying room-assistant configuration from /config/room_assistant
this say in container path is /config/room_assistant but yours is /room_assistant/config ( this is curious because I have same paths and mine works /room_assistant/config, something fishy here )

to fix mqtt error, check mqtt container logs I think is set not to accept connections from anything except localhost, look in conf

**Comment by hellcry37** [comment]
here is a good conf take from it:
part of docker-compose file
```yaml
version: '3.7'
services:
  room-assistant:
    image: mkerix/room-assistant
    container_name: room-assistant
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - 'TZ=Europe/Bucharest'
    volumes:
      - '/var/run/dbus:/var/run/dbus'
      - '/home/my-user/room-assistant/config:/room-assistant/config'
```
Note network_mode!

**Comment by RobertusIT** [comment]
> here is a good conf take from it: part of docker-compose file
> 
> ```yaml
> version: '3.7'
> services:
>   room-assistant:
>     image: mkerix/room-assistant
>     container_name: room-assistant
>     restart: unless-stopped
>     network_mode: host
>     cap_add:
>       - NET_ADMIN
>     environment:
>       - 'TZ=Europe/Bucharest'
>     volumes:
>       - '/var/run/dbus:/var/run/dbus'
>       - '/home/my-user/room-assistant/config:/room-assistant/config'
> ```
> 
> Note network_mode! Translate this for your container config

![image](https://user-images.githubusercontent.com/11599774/141264991-9c606d79-985b-471e-9f8d-23ea82ff58fc.png)

net is already on

folder are:

![image](https://user-images.githubusercontent.com/11599774/141265055-a2671fae-fe88-47ff-9162-f39703b2eafc.png)

inside lxc docker:

```
root@ROOM ~# cd /mnt/
root@ROOM /mnt# ls
 101.conf   103.conf   109.conf   frigate  'local - Copia.yml'   media     room-assistant   template
 102.conf   108.conf   dump       images    lost+found           private   snippets         vzsnap0
root@ROOM /mnt# cd room-assistant/
root@ROOM /mnt/room-assistant# ls
config
root@ROOM /mnt/room-assistant# cd config/
root@ROOM .../room-assistant/config# ls
local.yml
root@ROOM .../room-assistant/config# 
root@ROOM .../room-assistant/config# cat local.yml 
# You don't need to add the MQTT details for Home Assistant with the add-on installation, it will be auto-discovered!
global:
  instanceName: SALONENUC
  integrations:
    - homeAssistant
    - bluetoothClassic
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://192.168.178.56:1883'
  mqttOptions:
    username: mqtt_user
    password: mqtt_user
bluetoothClassic:
  addresses:
    - '64:A2:F9:31:0B:B9'
bluetoothLowEnergy:
  allowlist:
    - c7XX80fXXfXX
  tagOverrides:
    c72c80ff2fdc:
      name: Mi Band 6root@ROOM .../room-assistant/config# 
root@ROOM .../room-assistant/config# ls -la
total 4
drwxr-xr-x 2 root root   0 Nov 11 08:33 .
drwxr-xr-x 2 root root   0 Nov 11 08:33 ..
-rwxr-xr-x 1 root root 518 Nov 10 21:24 local.yml
root@ROOM .../room-assistant/config# 
```

So folder is mounted into lxc docker for room assistant.

Reboot room assistant and:

```
root@ROOM .../room-assistant/config# cat local.yml 
# You don't need to add the MQTT details for Home Assistant with the add-on installation, it will be auto-discovered!
global:
  instanceName: changeme
  integrations:
    - homeAssistant
root@ROOM .../room-assistant/config# 
```

So delete my config and replace with default, isn't normal
